Repository pgsql-jp/jpug-doc, pull requests merged in 2018-04, with the labels that each got.

#1218 protocol.sgmlのPostgreSQL 10.3対応です。
  doc/src/sgml/protocol.sgml
Labels: 再レビュー待ち

#1221 runtime.sgmlの10.3対応です
  doc/src/sgml/runtime.sgml
Labels: レビュー待ち

#1219 update pg_ctl-ref for 10.3
  doc/src/sgml/ref/pg_ctl-ref.sgml
Labels: 他にも誰か見て（レビュー済み）

#1225 create_trigger.sgmlのPostgreSQL 10.3対応です。
  doc/src/sgml/ref/create_trigger.sgml
Labels: 再レビュー待ち

#1224 create_policy.sgmlのPostgreSQL 10.3対応です。
  doc/src/sgml/ref/create_policy.sgml
Labels: 再レビュー待ち

#1227 pgbench.sgmlのPostgreSQL 10.3対応です。
  doc/src/sgml/ref/pgbench.sgml
Labels: レビュー待ち

#1228 pgupgrade.sgmlのPostgreSQL 10.3対応です。
  doc/src/sgml/ref/pgupgrade.sgml
Labels: 再レビュー待ち

#1233 remove extra tabs
  doc/src/sgml/release-10.sgml
Labels: レビュー待ち

#1235 remove extra trailing whitespace
  doc/src/sgml/advanced.sgml
  doc/src/sgml/amcheck.sgml
  doc/src/sgml/auth-delay.sgml
  doc/src/sgml/auto-explain.sgml
  doc/src/sgml/charset.sgml
  doc/src/sgml/client-auth.sgml
  doc/src/sgml/config.sgml
  doc/src/sgml/cube.sgml
  doc/src/sgml/datatype.sgml
  doc/src/sgml/ddl.sgml
  doc/src/sgml/ecpg.sgml
  doc/src/sgml/errcodes.sgml
  doc/src/sgml/func.sgml
  doc/src/sgml/high-availability.sgml
  doc/src/sgml/indexam.sgml
  doc/src/sgml/information_schema.sgml
  doc/src/sgml/installation.sgml
  doc/src/sgml/jpug-doc.sgml
  doc/src/sgml/libpq.sgml
  doc/src/sgml/manage-ag.sgml
  doc/src/sgml/monitoring.sgml
  doc/src/sgml/nls.sgml
  doc/src/sgml/ref/create_cast.sgml
  doc/src/sgml/ref/create_function.sgml
  doc/src/sgml/ref/drop_subscription.sgml
  doc/src/sgml/ref/drop_trigger.sgml
  doc/src/sgml/ref/pg_basebackup.sgml
  doc/src/sgml/ref/set_transaction.sgml
  doc/src/sgml/ref/vacuumdb.sgml
  doc/src/sgml/release-8.1.sgml
  doc/src/sgml/release-8.2.sgml
  doc/src/sgml/release-8.3.sgml
  doc/src/sgml/release-8.4.sgml
  doc/src/sgml/release-9.1.sgml
  doc/src/sgml/release-9.2.sgml
  doc/src/sgml/release-9.3.sgml
  doc/src/sgml/release-9.4.sgml
  doc/src/sgml/release-9.5.sgml
  doc/src/sgml/release-9.6.sgml
  doc/src/sgml/storage.sgml
  doc/src/sgml/syntax.sgml
  doc/src/sgml/vacuumlo.sgml
  doc/src/sgml/xfunc.sgml
Labels: レビュー待ち

#1237 重複して入ってしまっていた部分の削除
  doc/src/sgml/func.sgml
  doc/src/sgml/func1.sgml
  doc/src/sgml/func2.sgml
  doc/src/sgml/func3.sgml
  doc/src/sgml/func4.sgml
Labels: レビュー待ち

#1238 update errcodes for 10.3
  src/backend/utils/errcodes.txt.ja
Labels: レビュー待ち
