Repository pgsql-jp/jpug-doc, pull requests merged in 2018-03, with the labels that each got.

#1182 Postgresql10貢献者既存メンバー分
  doc/src/sgml/jpug-doc.sgml
Labels: レビュー待ち

#1197 update lobj to 10.3
  doc/src/sgml/lobj.sgml
Labels: レビュー待ち

#1199 high-availability.sgmlのtypo修正と訳の改善です。
  doc/src/sgml/high-availability.sgml
Labels: 再レビュー待ち

#1194 update contrib* to 10.3
  doc/src/sgml/contrib-spi.sgml
  doc/src/sgml/contrib.sgml
Labels: レビュー待ち

#1196 update ecpg to 10.3
  doc/src/sgml/ecpg.sgml
Labels: 他にも誰か見て（レビュー済み）

#1200 fdwhandler の10.3対応
  doc/src/sgml/fdwhandler.sgml
Labels: 再レビュー待ち

#1193 10.3対応
  doc/src/sgml/recovery-config.sgml
Labels: 再レビュー待ち

#1213 sourcerepo.sgmlのPostgreSQL 10.3対応です。
  doc/src/sgml/sourcerepo.sgml
Labels: レビュー待ち

#1198 update plpgsql to 10.3
  doc/src/sgml/plpgsql.sgml
Labels: レビュー待ち

#1201 update to 10.3 - part 6
  doc/src/sgml/maintenance.sgml
  doc/src/sgml/perform.sgml
Labels: レビュー待ち

#1204 update prepare_transaction to 10.3
  doc/src/sgml/ref/prepare_transaction.sgml
Labels: レビュー待ち

#1202 config.sgmlのPostgreSQL 10.3対応です。
  doc/src/sgml/config.sgml
Labels: レビュー待ち

#1203 release note 10.1、10.2、10.3 の翻訳
  doc/src/sgml/release-10.sgml
Labels: 再レビュー待ち

#1206 user-manag.sgmlの10.3対応
  doc/src/sgml/user-manag.sgml
Labels: レビュー待ち

#1205 extend.sgmlのPostgreSQL 10.3対応です。
  doc/src/sgml/extend.sgml
Labels: レビュー待ち

#1211 dblink.sgmlのPostgreSQL 10.3対応です。
  doc/src/sgml/dblink.sgml
Labels: 再レビュー待ち

#1222 一括変換漏れ修正
  doc/src/sgml/release-10.sgml
Labels: レビュー待ち

#1209 libpq.sgmlのPostgreSQL 10.3対応です。
  doc/src/sgml/libpq.sgml
Labels: 他にも誰か見て（レビュー済み）

#1223 情況->状況に変更。
  doc/src/sgml/backup.sgml
Labels: レビュー待ち

#1214 unify translation of 'interface'
  doc/src/sgml/acronyms.sgml
  doc/src/sgml/bgworker.sgml
  doc/src/sgml/config.sgml
  doc/src/sgml/release-9.6.sgml
  doc/src/sgml/release-old.sgml
  doc/src/sgml/sepgsql.sgml
Labels: レビュー待ち

#1215 rules.sgmlのPostgreSQL 10.3対応です。
  doc/src/sgml/rules.sgml
Labels: 他にも誰か見て（レビュー済み）
