Repository pgsql-jp/jpug-doc, pull requests merged in 2018-12, with the labels that each got.

#1342 11.1対応（新たに翻訳したところは無し）
  doc/src/sgml/isn.sgml
  doc/src/sgml/oid2name.sgml
  doc/src/sgml/uuid-ossp.sgml
Labels: レビュー待ち

#1343 11.1対応
  doc/src/sgml/external-projects.sgml
Labels: レビュー待ち

#1340 backup.sgmlのPostgreSQL 11.1対応です。
  doc/src/sgml/backup.sgml
Labels: レビュー待ち

#1344 update xaggr for 11.1
  doc/src/sgml/xaggr.sgml
Labels: 再レビュー待ち

#1350 arrary.sgmlのPostgreSQL 11.1対応です。
  doc/src/sgml/array.sgml
Labels: 再レビュー待ち

#1347 high-availability.sgmlのPostgreSQL 11.1対応です。
  doc/src/sgml/high-availability.sgml
Labels: レビュー待ち

#1359 update refresh... and seclabel for 11.1
  doc/src/sgml/ref/refresh_materialized_view.sgml
  doc/src/sgml/ref/security_label.sgml
Labels: レビュー待ち

#1346 cubeの11.1対応です。
  doc/src/sgml/cube.sgml
Labels: マージ待ち（レビュー済み）

#1352 update typeconv and unaccent for 11.1
  doc/src/sgml/typeconv.sgml
  doc/src/sgml/unaccent.sgml
Labels: 他にも誰か見て（レビュー済み）

#1358 sql_features.txt.jaとerrcodes.txt.jaの11対応です。
  src/backend/catalog/sql_features.txt.ja
  src/backend/utils/errcodes.txt.ja
Labels: 再レビュー待ち
