Repository pgsql-jp/jpug-doc, pull requests merged in 2018-10, with the labels that each got.

#1316 update syntax and typeconv for 10.5
  doc/src/sgml/syntax.sgml
  doc/src/sgml/typeconv.sgml
Labels: 再レビュー待ち

#1320 update create_function for 10.5
  doc/src/sgml/ref/create_function.sgml
Labels: レビュー待ち

#1326 親テーブルトリガ動作の記述で行レベル・文レベルの記載違いがあったものを修正
  doc/src/sgml/trigger.sgml
Labels: レビュー待ち

#1322 remove extra white space at line end
  doc/src/sgml/release-10.sgml
  doc/src/sgml/release-9.3.sgml
  doc/src/sgml/release-9.4.sgml
  doc/src/sgml/release-9.5.sgml
  doc/src/sgml/release-9.6.sgml
Labels: レビュー待ち

#1327 synchronous_standby_namesの誤訳の修正です。
  doc/src/sgml/config.sgml
Labels: 再レビュー待ち

#1328 ddl.sgmlのPostgreSQL 10.5対応です。
  doc/src/sgml/ddl.sgml
Labels: 他にも誰か見て（レビュー済み）
