Repository pgsql-jp/jpug-doc, pull requests merged in 2019-03, with the labels that each got.

#1412 update pgstattuple for 11.1
  doc/src/sgml/pgstattuple.sgml
Labels: レビュー待ち

#1414 update installation for 11.1
  doc/src/sgml/installation.sgml
Labels: マージ待ち（レビュー済み）

#1417 WAL関連ツールの説明を 11.1 むけ翻訳
  doc/src/sgml/ref/pg_receivewal.sgml
  doc/src/sgml/ref/pg_recvlogical.sgml
  doc/src/sgml/ref/pg_resetwal.sgml
  doc/src/sgml/ref/pg_rewind.sgml
Labels: マージ待ち（レビュー済み）

#1419 pg_class.relfrozenxid に関して、以前からの訳文について修正です。
  doc/src/sgml/catalogs.sgml
Labels: レビュー待ち

#1424 pgstattuple 内 pgstatindex に関する説明の微修正
  doc/src/sgml/pgstattuple.sgml
Labels: レビュー待ち

#1418 protocol.sgml の 11.1 むけ翻訳
  doc/src/sgml/protocol.sgml
Labels: 再レビュー待ち

#1422 runtime.sgmlのPostgreSQL 11.1対応です。
  doc/src/sgml/runtime.sgml
Labels: 再レビュー待ち

#1423 logical-replication.sgmlの11.1対応
  doc/src/sgml/logical-replication.sgml
Labels: マージ待ち（レビュー済み）

#1420 sources.sgml と regress.sgml の PG11.1対応翻訳
  doc/src/sgml/regress.sgml
  doc/src/sgml/sources.sgml
Labels: 再レビュー待ち

#1428 fix missing comment tags
  doc/src/sgml/runtime.sgml
Labels: レビュー待ち

#1411 update information_schema for 11.1
  doc/src/sgml/information_schema.sgml
Labels: 再レビュー待ち

#1421 spi.sgml を PG11.1 むけに翻訳アップデート
  doc/src/sgml/spi.sgml
Labels: 再レビュー待ち

#1431 たまたま見つけた誤訳の訂正です。
  doc/src/sgml/protocol.sgml
Labels: レビュー待ち

#1416 lobj.sgmlのPostgreSQL 11.1対応です。
  doc/src/sgml/lobj.sgml
Labels: 再レビュー待ち

#1426 create_function.sgml - update for 11.1
  doc/src/sgml/ref/create_function.sgml
Labels: マージ待ち（レビュー済み）

#1432 fix a missing comment tag
  doc/src/sgml/lobj.sgml
Labels: レビュー待ち

#1410 Translate release note 9.3.25 to 9.6.11
  doc/src/sgml/release-9.3.sgml
  doc/src/sgml/release-9.4.sgml
  doc/src/sgml/release-9.5.sgml
  doc/src/sgml/release-9.6.sgml
Labels: レビュー待ち

#1402 datatype.sgmlのversion11対応です
  doc/src/sgml/datatype.sgml
Labels: 再レビュー待ち
