Repository pgsql-jp/jpug-doc, pull requests merged in 2019-02, with the labels that each got.

#1370 update bgworker for 11.1
  doc/src/sgml/bgworker.sgml
Labels: 再レビュー待ち

#1374 chaset.sgmlのPostgreSQL 11.1対応です。
  doc/src/sgml/charset.sgml
Labels: 再レビュー待ち

#1394 ref/の11.1軽微な修正対応
  doc/src/sgml/ref/create_publication.sgml
  doc/src/sgml/ref/create_view.sgml
  doc/src/sgml/ref/ecpg-ref.sgml
  doc/src/sgml/ref/reassign_owned.sgml
Labels: レビュー待ち

#1396 queries.sgmlの11.1対応です。
  doc/src/sgml/queries.sgml
Labels: レビュー待ち

#1375 fdwhandler.sgmlのPostgreSQL 11.1対応です。
  doc/src/sgml/fdwhandler.sgml
Labels: マージ待ち（レビュー済み）

#1383 ecpg.sgml を PostgreSQL 11.1 むけに翻訳
  doc/src/sgml/ecpg.sgml
Labels: レビュー待ち

#1369 client-auth.sgmlの11.1対応です。
  doc/src/sgml/client-auth.sgml
Labels: マージ待ち（レビュー済み）

#1398 file-fdw.sgml を PG 11.1 むけに翻訳
  doc/src/sgml/file-fdw.sgml
Labels: レビュー待ち

#1399 update create_opclass, create_operator and do for 11.1
  doc/src/sgml/ref/create_opclass.sgml
  doc/src/sgml/ref/create_operator.sgml
  doc/src/sgml/ref/do.sgml
Labels: レビュー待ち

#1403 fix typos in config
  doc/src/sgml/config.sgml
  doc/src/sgml/config1.sgml
  doc/src/sgml/config2.sgml
Labels: レビュー待ち

#1385 「SQLの拡張」と「ユーザ定義関数」の PostgreSQL 11.1 対応翻訳
  doc/src/sgml/extend.sgml
  doc/src/sgml/xfunc.sgml
Labels: 再レビュー待ち

#1360 10.6 リリースノート翻訳
  doc/src/sgml/release-10.sgml
Labels: レビュー待ち

#1380 docguide.sgmlのPostgreSQL 11.1対応です。
  doc/src/sgml/docguide.sgml
Labels: 再レビュー待ち

#1382 pgtrgm.sgml を 11.1 むけに翻訳
  doc/src/sgml/pgtrgm.sgml
Labels: マージ待ち（レビュー済み）

#1395 rules.sgmlの11.1対応です。
  doc/src/sgml/rules.sgml
Labels: 他にも誰か見て（レビュー済み）

#1354 func.sgmlのPostgreSQL 11対応です。
  doc/src/sgml/func.sgml
  doc/src/sgml/func1.sgml
  doc/src/sgml/func2.sgml
  doc/src/sgml/func3.sgml
  doc/src/sgml/func4.sgml
Labels: 再レビュー待ち

#1408 fix unclosed comment
  doc/src/sgml/func.sgml
  doc/src/sgml/func4.sgml
Labels: レビュー待ち

#1413 pg_statsのmost_common_elem_freqs列の説明を修正
  doc/src/sgml/catalogs.sgml
Labels: レビュー待ち

#1400 xindex.sgml の翻訳 PG11.1対応
  doc/src/sgml/xindex.sgml
Labels: 再レビュー待ち

#1361 bki.sgmlのPostgreSQL 11.1対応です。
  doc/src/sgml/bki.sgml
Labels: マージ待ち（レビュー済み）

#1406 gist.sgmlの11.1対応です。
  doc/src/sgml/gist.sgml
Labels: 再レビュー待ち

#1401 pgprewarm.sgmlのPostgreSQL 11.1対応です。
  doc/src/sgml/pgprewarm.sgml
Labels: 他にも誰か見て（レビュー済み）

#1404 バックアップ／リストアのコマンドについて PG11 むけ翻訳
  doc/src/sgml/ref/pg_basebackup.sgml
  doc/src/sgml/ref/pg_dump.sgml
  doc/src/sgml/ref/pg_dumpall.sgml
  doc/src/sgml/ref/pg_restore.sgml
Labels: レビュー待ち

#1384 PL/pgSQL ほか、PL言語のページを 11.1 むけ翻訳
  doc/src/sgml/plperl.sgml
  doc/src/sgml/plpgsql.sgml
  doc/src/sgml/plpython.sgml
  doc/src/sgml/pltcl.sgml
Labels: マージ待ち（レビュー済み）

#1405 indexam.sgmlとindices.sgmlの11.1対応です。
  doc/src/sgml/indexam.sgml
  doc/src/sgml/indices.sgml
Labels: 再レビュー待ち
