Repository pgsql-jp/jpug-doc, pull requests merged in 2019-12, with the labels that each got.

#1585 update pg_restore for 12
  doc/src/sgml/ref/pg_restore.sgml
Labels: マージ待ち（レビュー済み）

#1587 update reindexdb for 12
  doc/src/sgml/ref/reindexdb.sgml
Labels: マージ待ち（レビュー済み）

#1588 protocol.sgmlのPostgreSQL 12.0対応です。
  doc/src/sgml/protocol.sgml
Labels: 再レビュー待ち

#1586 update pg_basebackup for 12
  doc/src/sgml/ref/pg_basebackup.sgml
Labels: 再レビュー待ち

#1590 update install-windows for 12
  doc/src/sgml/install-windows.sgml
Labels: レビュー待ち

#1591 update pgstatstatements for 12
  doc/src/sgml/pgstatstatements.sgml
Labels: レビュー待ち

#1589 queries.sgmlの12.0対応です。
  doc/src/sgml/queries.sgml
Labels: マージ待ち（レビュー済み）

#1594 update pg_rewind etc for 12
  doc/src/sgml/ref/alter_index.sgml
  doc/src/sgml/ref/create_aggregate.sgml
  doc/src/sgml/ref/pg_rewind.sgml
Labels: マージ待ち（レビュー済み）

#1582 func.sgmlのPostgreSQL 12.0対応です。
  doc/src/sgml/func.sgml
  doc/src/sgml/func0.sgml
  doc/src/sgml/func1.sgml
  doc/src/sgml/func2.sgml
  doc/src/sgml/func3.sgml
  doc/src/sgml/func4.sgml
Labels: 他にも誰か見て（レビュー済み）, 指摘事項あり

#1595 12.0 リリースノートの翻訳を追加。
  doc/src/sgml/release-12.sgml
Labels: 他にも誰か見て（レビュー済み）

#1602 remove extra space
  doc/src/sgml/bgworker.sgml
  doc/src/sgml/release-12.sgml
Labels: レビュー待ち

#1600 update vacuumlo for 12
  doc/src/sgml/vacuumlo.sgml
Labels: レビュー待ち

#1599 backup.sgml の 12.0 の変更点を翻訳
  doc/src/sgml/backup.sgml
Labels: レビュー待ち

#1603 update pg_archcleanup for 12
  doc/src/sgml/ref/pgarchivecleanup.sgml
Labels: レビュー待ち

#1593 perform.sgmlのPostgreSQL 12.0対応です。
  doc/src/sgml/perform.sgml
Labels: 再レビュー待ち

#1614 テーブルの一つ余分な/row,rowを削除
  doc/src/sgml/func.sgml
Labels: レビュー待ち

#1615 余分な行の削除
  doc/src/sgml/func.sgml
Labels: レビュー待ち

#1598 datatype.sgmlの12対応
  doc/src/sgml/datatype.sgml
Labels: 再レビュー待ち

#1592 update user-manag for 12
  doc/src/sgml/user-manag.sgml
Labels: 再レビュー待ち

#1597 update alter/create_domain for 12
  doc/src/sgml/ref/alter_domain.sgml
  doc/src/sgml/ref/create_domain.sgml
Labels: マージ待ち（レビュー済み）
