Repository pgsql-jp/jpug-doc, pull requests merged in 2019-04, with the labels that each got.

#1439 fix brackets in wal.sgml
  doc/src/sgml/wal.sgml
Labels: レビュー待ち

#1449 fix refmiscinfo
  doc/src/sgml/ref/abort.sgml
  doc/src/sgml/ref/alter_foreign_data_wrapper.sgml
  doc/src/sgml/ref/alter_server.sgml
  doc/src/sgml/ref/alter_tsconfig.sgml
  doc/src/sgml/ref/alter_tsdictionary.sgml
  doc/src/sgml/ref/alter_tsparser.sgml
  doc/src/sgml/ref/alter_tstemplate.sgml
  doc/src/sgml/ref/alter_user_mapping.sgml
  doc/src/sgml/ref/alter_view.sgml
  doc/src/sgml/ref/create_foreign_data_wrapper.sgml
  doc/src/sgml/ref/create_opfamily.sgml
  doc/src/sgml/ref/create_server.sgml
  doc/src/sgml/ref/create_tsconfig.sgml
  doc/src/sgml/ref/create_tsdictionary.sgml
  doc/src/sgml/ref/create_tsparser.sgml
  doc/src/sgml/ref/create_tstemplate.sgml
  doc/src/sgml/ref/create_user_mapping.sgml
  doc/src/sgml/ref/discard.sgml
  doc/src/sgml/ref/drop_collation.sgml
  doc/src/sgml/ref/drop_extension.sgml
  doc/src/sgml/ref/drop_foreign_data_wrapper.sgml
  doc/src/sgml/ref/drop_foreign_table.sgml
  doc/src/sgml/ref/drop_opfamily.sgml
  doc/src/sgml/ref/drop_owned.sgml
  doc/src/sgml/ref/drop_server.sgml
  doc/src/sgml/ref/drop_tsconfig.sgml
  doc/src/sgml/ref/drop_tsdictionary.sgml
  doc/src/sgml/ref/drop_tsparser.sgml
  doc/src/sgml/ref/drop_tstemplate.sgml
  doc/src/sgml/ref/drop_user_mapping.sgml
  doc/src/sgml/ref/reassign_owned.sgml
  doc/src/sgml/ref/refresh_materialized_view.sgml
  doc/src/sgml/ref/rollback.sgml
  doc/src/sgml/ref/values.sgml
Labels: レビュー待ち

#1425 spgist.sgml を 11.1 むけに翻訳修正
  doc/src/sgml/spgist.sgml
Labels: 再レビュー待ち

#1429 parallel.sgml を 11.1 むけ翻訳
  doc/src/sgml/parallel.sgml
Labels: マージ待ち（レビュー済み）

#1433 update reindex for 11.1
  doc/src/sgml/ref/reindex.sgml
Labels: 再レビュー待ち

#1434 update grant and insert for 11.1
  doc/src/sgml/ref/grant.sgml
  doc/src/sgml/ref/insert.sgml
Labels: マージ待ち（レビュー済み）

#1435 update create*_trigger for 11.1
  doc/src/sgml/ref/create_event_trigger.sgml
  doc/src/sgml/ref/create_trigger.sgml
Labels: マージ待ち（レビュー済み）

#1436 textsearch.sgmlのPostgreSQL 11.1対応です。
  doc/src/sgml/textsearch.sgml
Labels: レビュー待ち

#1437 pg_verify_checksums for 11.1
  doc/src/sgml/ref/pg_verify_checksums.sgml
Labels: レビュー待ち

#1448 update ref/call.sgml for 11.1
  doc/src/sgml/ref/call.sgml
Labels: 他にも誰か見て（レビュー済み）

#1452 alter_domain.sgml - update for 11.1
  doc/src/sgml/ref/alter_domain.sgml
Labels: レビュー待ち

#1438 update initdb for 11.1
  doc/src/sgml/ref/initdb.sgml
Labels: 再レビュー待ち

#1430 syntax.sgmlのPostgreSQL 11.1対応です。
  doc/src/sgml/syntax.sgml
Labels: 再レビュー待ち

#1440 trigger.sgmlのPostgreSQL 11.1対応です。
  doc/src/sgml/trigger.sgml
Labels: レビュー待ち

#1443 logicaldecoding.sgml を PG11.1 むけ翻訳
  doc/src/sgml/logicaldecoding.sgml
Labels: レビュー待ち

#1451 create_aggregate.sgmlのPostgreSQL 11.1対応です。
  doc/src/sgml/ref/create_aggregate.sgml
Labels: マージ待ち（レビュー済み）

#1450 monitoring.sgmlのPostgreSQL 11.1対応です。
  doc/src/sgml/monitoring.sgml
Labels: マージ待ち（レビュー済み）

#1444 libpq.sgml 11.1 むけ翻訳修正
  doc/src/sgml/libpq.sgml
Labels: レビュー待ち

#1445 update ddl.sgml for 11.1
  doc/src/sgml/ddl.sgml
Labels: 指摘事項あり

#1446 perform.sgmlのPostgreSQL 11.1対応です。
  doc/src/sgml/perform.sgml
Labels: 他にも誰か見て（レビュー済み）

#1442 PROCEDURE、ROUTINE のリファレンスを11.1むけ翻訳
  doc/src/sgml/ref/alter_procedure.sgml
  doc/src/sgml/ref/alter_routine.sgml
  doc/src/sgml/ref/create_procedure.sgml
  doc/src/sgml/ref/drop_procedure.sgml
  doc/src/sgml/ref/drop_routine.sgml
Labels: 再レビュー待ち

#1447 ALTER/CREATE TABLE/INDEX リファレンスの PG11.1 翻訳対応
  doc/src/sgml/ref/alter_index.sgml
  doc/src/sgml/ref/alter_table.sgml
  doc/src/sgml/ref/create_index.sgml
  doc/src/sgml/ref/create_table.sgml
Labels: 再レビュー待ち

#1456 adminpackの11.1対応です。
  doc/src/sgml/adminpack.sgml
Labels: 再レビュー待ち
