Repository pgsql-jp/jpug-doc, pull requests merged in 2019-09, with the labels that each got.

#1537 config.sgmlのPostgreSQL 11.5対応です。
  doc/src/sgml/config.sgml
  doc/src/sgml/config2.sgml
Labels: 再レビュー待ち

#1542 fix unmatched parentheses
  doc/src/sgml/backup.sgml
  doc/src/sgml/config.sgml
  doc/src/sgml/config1.sgml
  doc/src/sgml/fdwhandler.sgml
  doc/src/sgml/func.sgml
  doc/src/sgml/func2.sgml
  doc/src/sgml/json.sgml
  doc/src/sgml/libpq.sgml
  doc/src/sgml/monitoring.sgml
  doc/src/sgml/perform.sgml
  doc/src/sgml/pgstattuple.sgml
  doc/src/sgml/plpgsql.sgml
  doc/src/sgml/ref/create_aggregate.sgml
  doc/src/sgml/ref/create_table.sgml
  doc/src/sgml/ref/pg_ctl-ref.sgml
  doc/src/sgml/syntax.sgml
  doc/src/sgml/wal.sgml
  doc/src/sgml/xaggr.sgml
Labels: レビュー待ち

#1541 logical-replication を 11.5 むけに翻訳修正
  doc/src/sgml/logical-replication.sgml
Labels: レビュー待ち

#1545 Issues#1544の対応
  doc/src/sgml/ref/pg_resetwal.sgml
Labels: 指摘事項あり

#1552 REL_11_5との差分チェックによりみつかった問題修正
  doc/src/sgml/func.sgml
  doc/src/sgml/func2.sgml
  doc/src/sgml/lobj.sgml
  doc/src/sgml/release-11.sgml
  doc/src/sgml/spi.sgml
Labels: レビュー待ち

#1543 update ddl for 11.5
  doc/src/sgml/ddl.sgml
Labels: 他にも誰か見て（レビュー済み）

#1548 varianceの索引生成
  doc/src/sgml/func.sgml
Labels: 指摘事項あり

#1551 idx_scanの翻訳の修正
  doc/src/sgml/monitoring.sgml
Labels: 指摘事項あり

#1553 原文がコメントアウトされていなかった箇所の修正
  doc/src/sgml/bki.sgml
Labels: レビュー待ち
