Repository pgsql-jp/jpug-doc, pull requests merged in 2019-06, with the labels that each got.

#1473 update copy and initdb for 11.3
  doc/src/sgml/ref/copy.sgml
  doc/src/sgml/ref/initdb.sgml
Labels: 再レビュー待ち

#1470 update installation for 11.3
  doc/src/sgml/installation.sgml
Labels: マージ待ち（レビュー済み）

#1475 update pgbench and pgupgrade for 11.3
  doc/src/sgml/ref/pgbench.sgml
  doc/src/sgml/ref/pgupgrade.sgml
Labels: マージ待ち（レビュー済み）

#1480 high-availability.sgmlのPostgreSQL 11.3対応です。
  doc/src/sgml/high-availability.sgml
Labels: レビュー待ち

#1485 Issue 1471対応です。
  doc/src/sgml/monitoring.sgml
Labels: 再レビュー待ち

#1476 fdwhandler.sgmlのPostgreSQL 11.3対応です。
  doc/src/sgml/fdwhandler.sgml
Labels: 他にも誰か見て（レビュー済み）, 再レビュー待ち

#1477 func.sgmlのPostgreSQL 11.3対応です。
  doc/src/sgml/func.sgml
  doc/src/sgml/func4.sgml
Labels: 他にも誰か見て（レビュー済み）, 再レビュー待ち

#1481 monitoring.sgmlのPostgreSQL 11.3対応です。
  doc/src/sgml/monitoring.sgml
Labels: レビュー待ち

#1479 リリースノート 11.2, 11.3 の翻訳
  doc/src/sgml/release-11.sgml
Labels: 再レビュー待ち

#1482 perform.sgmlのPostgreSQL 11.3対応です。
  doc/src/sgml/perform.sgml
Labels: レビュー待ち

#1499 uncommented English in perform
  doc/src/sgml/perform.sgml
Labels: レビュー待ち

#1489 update some unassigned files to 11.3 (2)
  doc/src/sgml/ref/create_type.sgml
  doc/src/sgml/ref/drop_owned.sgml
Labels: レビュー待ち

#1490 update maintenance for 11.3
  doc/src/sgml/maintenance.sgml
Labels: レビュー待ち

#1491 custom-scan.sgmlのPostgreSQL 11.3対応です。
  doc/src/sgml/custom-scan.sgml
Labels: レビュー待ち

#1501 update ddl for 11.3
  doc/src/sgml/ddl.sgml
Labels: マージ待ち（レビュー済み）

#1504 削除済みファイルを除外
  doc/src/sgml/release-10.sgml
  doc/src/sgml/release-7.4.sgml
  doc/src/sgml/release-8.0.sgml
  doc/src/sgml/release-8.1.sgml
  doc/src/sgml/release-8.2.sgml
  doc/src/sgml/release-8.3.sgml
  doc/src/sgml/release-8.4.sgml
  doc/src/sgml/release-9.0.sgml
  doc/src/sgml/release-9.1.sgml
  doc/src/sgml/release-9.2.sgml
  doc/src/sgml/release-9.3.sgml
  doc/src/sgml/release-9.4.sgml
  doc/src/sgml/release-9.5.sgml
  doc/src/sgml/release-9.6.sgml
  doc/src/sgml/release-old.sgml
Labels: レビュー待ち

#1493 update create_foreign_table for 11.3
  doc/src/sgml/ref/create_foreign_table.sgml
Labels: レビュー待ち

#1494 update alter_large_object for 11.3
  doc/src/sgml/ref/alter_large_object.sgml
Labels: レビュー待ち

#1505 ddl.sgmlの原文のインデントが変わってしまっているのを修正
  doc/src/sgml/ddl.sgml
Labels: レビュー待ち

#1498 dblink.sgmlのPostgreSQL 11.3対応です。
  doc/src/sgml/dblink.sgml
Labels: レビュー待ち

#1496 update problems for 11.3
  doc/src/sgml/problems.sgml
Labels: マージ待ち（レビュー済み）

#1497 update some unassigned files to 11.3 (3)
  doc/src/sgml/legal.sgml
  doc/src/sgml/postgres-fdw.sgml
Labels: マージ待ち（レビュー済み）

#1484 いくつかのファイルについて 11.1 から 11.3 の変更部分を翻訳
  doc/src/sgml/extend.sgml
  doc/src/sgml/file-fdw.sgml
  doc/src/sgml/libpq.sgml
  doc/src/sgml/plpgsql.sgml
  doc/src/sgml/protocol.sgml
  doc/src/sgml/ref/alter_table.sgml
  doc/src/sgml/ref/create_table.sgml
  doc/src/sgml/ref/pg_basebackup.sgml
  doc/src/sgml/ref/pg_dump.sgml
  doc/src/sgml/ref/pg_rewind.sgml
  doc/src/sgml/ref/psql-ref.sgml
Labels: マージ待ち（レビュー済み）

#1478 config.sgmlのPostgreSQL 11.3対応です。
  doc/src/sgml/config.sgml
  doc/src/sgml/config1.sgml
  doc/src/sgml/config2.sgml
  doc/src/sgml/config3.sgml
Labels: 再レビュー待ち

#1507 release.sgml 11.3 修正部を翻訳
  doc/src/sgml/release.sgml
Labels: マージ待ち（レビュー済み）

#1492 datetime.sgmlのPostgreSQL 11.3対応です。
  doc/src/sgml/datetime.sgml
Labels: 再レビュー待ち

#1487 update 'update' for 11.3
  doc/src/sgml/ref/update.sgml
Labels: 再レビュー待ち

#1503 indices.sgmlの11.3対応です。
  doc/src/sgml/indices.sgml
Labels: 再レビュー待ち
