Repository pgsql-jp/jpug-doc, pull requests merged in 2019-07, with the labels that each got.

#1506 datatype.sgmlの11.3対応
  doc/src/sgml/datatype.sgml
Labels: マージ待ち（レビュー済み）

#1511 update spgist for 11.4
  doc/src/sgml/spgist.sgml
Labels: レビュー待ち

#1512 pgtrgm.sgmlの11.4対応です。
  doc/src/sgml/pgtrgm.sgml
Labels: レビュー待ち

#1509 update information_schema and storage for 11.4
  doc/src/sgml/information_schema.sgml
  doc/src/sgml/storage.sgml
Labels: マージ待ち（レビュー済み）

#1516 原文がそのまま表示されていた部分の修正
  doc/src/sgml/backup.sgml
  doc/src/sgml/high-availability.sgml
  doc/src/sgml/libpq.sgml
  doc/src/sgml/runtime.sgml
Labels: レビュー待ち

#1517 fix punctuation
  doc/src/sgml/client-auth.sgml
Labels: レビュー待ち

#1510 func.sgmlのPostgreSQL 11.4対応です。
  doc/src/sgml/func.sgml
  doc/src/sgml/func3.sgml
  doc/src/sgml/func4.sgml
Labels: 再レビュー待ち

#1513 datatype.sgmlの11.4対応
  doc/src/sgml/datatype.sgml
Labels: 他にも誰か見て（レビュー済み）, 指摘事項あり

#1519 fix typo in "ALTER TABLE"
  doc/src/sgml/ref/alter_table.sgml
Labels: レビュー待ち

#1520 datatype.sgmlの削除漏れ
  doc/src/sgml/datatype.sgml
Labels: レビュー待ち

#1518 斉藤さんの指摘によりconfig.sgmlの未翻訳部分を翻訳しました。
  doc/src/sgml/config.sgml
  doc/src/sgml/config3.sgml
Labels: 再レビュー待ち

#1523 軽微な修正
  doc/src/sgml/func.sgml
  doc/src/sgml/ref/alter_sequence.sgml
  doc/src/sgml/ref/pg_rewind.sgml
  doc/src/sgml/ref/pgupgrade.sgml
  doc/src/sgml/rules.sgml
  doc/src/sgml/seg.sgml
  doc/src/sgml/tablesample-method.sgml
  doc/src/sgml/xaggr.sgml
Labels: レビュー待ち

#1524 create_index.sgmlのPostgreSQL 11.4対応です。
  doc/src/sgml/ref/create_index.sgml
Labels: レビュー待ち

#1525 fix 'authors'
  doc/src/sgml/bloom.sgml
Labels: レビュー待ち

#1521 update ddl.sgml for 11.4
  doc/src/sgml/ddl.sgml
Labels: 再レビュー待ち

#1514 PostgreSQL11翻訳貢献者リスト
  doc/src/sgml/jpug-doc.sgml
Labels: レビュー待ち
