Repository pgsql-jp/jpug-doc, pull requests merged in 2019-01, with the labels that each got.

#1357 update update and vacuum for 11.1
  doc/src/sgml/ref/update.sgml
  doc/src/sgml/ref/vacuum.sgml
Labels: レビュー待ち

#1351 update user-manag and wal for 11.1
  doc/src/sgml/user-manag.sgml
  doc/src/sgml/wal.sgml
Labels: 他にも誰か見て（レビュー済み）

#1353 update storage for 11.1
  doc/src/sgml/storage.sgml
Labels: 他にも誰か見て（レビュー済み）

#1355 translate standalone-install for 11.1
  doc/src/sgml/standalone-install.xml
Labels: 他にも誰か見て（レビュー済み）, 再レビュー待ち

#1341 config.sgmlのPostgreSQL 11対応です。
  doc/src/sgml/config.sgml
  doc/src/sgml/config0.sgml
  doc/src/sgml/config1.sgml
  doc/src/sgml/config2.sgml
  doc/src/sgml/config3.sgml
Labels: 他にも誰か見て（レビュー済み）, 指摘事項あり

#1366 minor fix for postgres-fdw
  doc/src/sgml/postgres-fdw.sgml
Labels: レビュー待ち

#1362 bloom.sgmlのPostgresSQL 11対応です。
  doc/src/sgml/bloom.sgml
Labels: レビュー待ち

#1363 update pgupgrade and prepare for 11.1
  doc/src/sgml/ref/pgupgrade.sgml
  doc/src/sgml/ref/prepare.sgml
Labels: 他にも誰か見て（レビュー済み）

#1364 update lock and pg_ctl-ref for 11.1
  doc/src/sgml/ref/lock.sgml
  doc/src/sgml/ref/pg_ctl-ref.sgml
Labels: レビュー待ち

#1365 update alter_extension and opfamily for 11.1
  doc/src/sgml/ref/alter_extension.sgml
  doc/src/sgml/ref/alter_opfamily.sgml
Labels: レビュー待ち

#1348 リリースノート 11.0、11.1 翻訳
  doc/src/sgml/release-11.sgml
  doc/src/sgml/release.sgml
Labels: 再レビュー待ち

#1371 update analyze, comment and copy for 11.1
  doc/src/sgml/ref/analyze.sgml
  doc/src/sgml/ref/comment.sgml
  doc/src/sgml/ref/copy.sgml
Labels: 他にも誰か見て（レビュー済み）

#1373 catalogs.sgmlのPostgreSQL 11.1対応です。
  doc/src/sgml/catalogs.sgml
Labels: 再レビュー待ち

#1372 btree-gin.sgmlのPostgreSQL 11.1対応です。
  doc/src/sgml/btree-gin.sgml
Labels: マージ待ち（レビュー済み）

#1390 history.sgmlの11.1対応です。
  doc/src/sgml/history.sgml
Labels: レビュー待ち

#1389 gin.sgmlの11.1対応です。
  doc/src/sgml/gin.sgml
Labels: レビュー待ち
