Repository pgsql-jp/jpug-doc, pull requests merged in 2020-08, with the labels that each got.

#1731 monitoring.sgml内の表27.1 動的統計情報ビューの改善です
  doc/src/sgml/monitoring.sgml
Labels: マージ待ち（レビュー済み）

#1736 config.sgmlの修正と同期しました。
  doc/src/sgml/config0.sgml
Labels: レビュー待ち

#1691 update installation and rangetype for 12.3
  doc/src/sgml/installation.sgml
  doc/src/sgml/rangetypes.sgml
Labels: マージ待ち（レビュー済み）

#1737 xfunc.sgmlの12.3対応です。
  doc/src/sgml/xfunc.sgml
Labels: 再レビュー待ち

#1744 PostgreSQL 12.3のconfig.sgmlに修正が入ったので分割ファイルも同期しました。
  doc/src/sgml/config0.sgml
  doc/src/sgml/config3.sgml
Labels: レビュー待ち

#1748 update seg and textsearch
  doc/src/sgml/seg.sgml
  doc/src/sgml/textsearch.sgml
Labels: レビュー待ち

#1749 update for 12.4 - part 2
  doc/src/sgml/ref/pg_restore.sgml
  doc/src/sgml/ref/pgupgrade.sgml
  doc/src/sgml/ref/reindexdb.sgml
  doc/src/sgml/runtime.sgml
Labels: レビュー待ち

#1750 update create_database for 12.4
  doc/src/sgml/ref/create_database.sgml
Labels: レビュー待ち

#1751 update for 12.4 - part 3
  doc/src/sgml/plperl.sgml
  doc/src/sgml/plpgsql.sgml
  doc/src/sgml/pltcl.sgml
Labels: レビュー待ち

#1753 client-auth.sgml の12.4対応です。
  doc/src/sgml/client-auth.sgml
Labels: レビュー待ち

#1754 indices.sgml の12.4対応です。
  doc/src/sgml/indices.sgml
Labels: レビュー待ち

#1757 update install-windows etc. for 12.4
  doc/src/sgml/install-windows.sgml
  doc/src/sgml/intro.sgml
  doc/src/sgml/libpq.sgml
Labels: レビュー待ち

#1758 update dfunc etc. for 12.4
  doc/src/sgml/dfunc.sgml
  doc/src/sgml/external-projects.sgml
  doc/src/sgml/features.sgml
Labels: レビュー待ち

#1759 update bki and cube for 12.4
  doc/src/sgml/bki.sgml
  doc/src/sgml/cube.sgml
Labels: レビュー待ち

#1760 update maintenance for 12.4
  doc/src/sgml/maintenance.sgml
Labels: レビュー待ち

#1761 update advanced for 12.4
  doc/src/sgml/advanced.sgml
Labels: レビュー待ち

#1762 nls.sgmlの12.4対応です（URL修正のみ）。
  doc/src/sgml/nls.sgml
Labels: レビュー待ち

#1764 update biblio for 12.4
  doc/src/sgml/biblio.sgml
Labels: レビュー待ち
