Repository pgsql-jp/jpug-doc, pull requests merged in 2020-06, with the labels that each got.

#1686 update install-win for 12.3
  doc/src/sgml/install-windows.sgml
Labels: マージ待ち（レビュー済み）

#1687 update create/drop/re-index for 12.3
  doc/src/sgml/ref/create_index.sgml
  doc/src/sgml/ref/drop_index.sgml
  doc/src/sgml/ref/reindex.sgml
Labels: マージ待ち（レビュー済み）

#1688 update mvcc for 12.3
  doc/src/sgml/mvcc.sgml
Labels: マージ待ち（レビュー済み）

#1683 update truncate and update for 12.3
  doc/src/sgml/ref/truncate.sgml
  doc/src/sgml/ref/update.sgml
Labels: 再レビュー待ち

#1682 update libpq for 12.3
  doc/src/sgml/libpq.sgml
Labels: マージ待ち（レビュー済み）

#1689 update pgbuffercache for 12.3
  doc/src/sgml/pgbuffercache.sgml
Labels: 再レビュー待ち

#1692 update grant for 12.3
  doc/src/sgml/ref/grant.sgml
Labels: 他にも誰か見て（レビュー済み）

#1693 client-auth.sgml の12.3対応です
  doc/src/sgml/client-auth.sgml
Labels: 他にも誰か見て（レビュー済み）

#1690 cataogs.sgmlのPostgreSQL 12.3対応です。
  doc/src/sgml/catalogs.sgml
Labels: 再レビュー待ち

#1695 update ecpg-ref for 12.3
  doc/src/sgml/ref/ecpg-ref.sgml
Labels: マージ待ち（レビュー済み）

#1697 update create_table for 12.3
  doc/src/sgml/ref/create_table.sgml
Labels: マージ待ち（レビュー済み）

#1698 update copy for 12.3
  doc/src/sgml/ref/copy.sgml
Labels: マージ待ち（レビュー済み）

#1696 update delete for 12.3
  doc/src/sgml/ref/delete.sgml
Labels: マージ待ち（レビュー済み）

#1699 update alter_table for 12.3
  doc/src/sgml/ref/alter_table.sgml
Labels: レビュー待ち

#1700 update alter_def.._priv.. for 12.3
  doc/src/sgml/ref/alter_default_privileges.sgml
Labels: マージ待ち（レビュー済み）

#1703 update alter_subsc.. and create_trigger for 12.3
  doc/src/sgml/ref/alter_subscription.sgml
  doc/src/sgml/ref/create_trigger.sgml
Labels: マージ待ち（レビュー済み）

#1704 update ltree for 12.3
  doc/src/sgml/ltree.sgml
Labels: マージ待ち（レビュー済み）

#1705 update manage-ag for 12.3
  doc/src/sgml/manage-ag.sgml
Labels: マージ待ち（レビュー済み）

#1706 fix translation of "cluster"
  doc/src/sgml/config.sgml
  doc/src/sgml/config1.sgml
Labels: マージ待ち（レビュー済み）

#1707 indices.sgmlの12.3対応です
  doc/src/sgml/indices.sgml
Labels: レビュー待ち

#1714 修正 #1712
  doc/src/sgml/ref/pgbench.sgml
Labels: レビュー待ち

#1715 修正 #1713
  doc/src/sgml/config.sgml
  doc/src/sgml/config2.sgml
Labels: レビュー待ち

#1716 wal.sgmlの12.3対応です。
  doc/src/sgml/backup.sgml
  doc/src/sgml/syntax.sgml
  doc/src/sgml/wal.sgml
Labels: レビュー待ち
