Repository pgsql-jp/jpug-doc, pull requests merged in 2020-01, with the labels that each got.

#1604 update alter_table for 12
  doc/src/sgml/ref/alter_table.sgml
Labels: マージ待ち（レビュー済み）

#1608 update pg_dumpall for 12
  doc/src/sgml/ref/pg_dumpall.sgml
Labels: マージ待ち（レビュー済み）

#1609 update oid2name for 12
  doc/src/sgml/oid2name.sgml
Labels: レビュー待ち

#1606 update create_index for 12
  doc/src/sgml/ref/create_index.sgml
Labels: マージ待ち（レビュー済み）

#1607 update create_fn and pg_dump for 12
  doc/src/sgml/ref/create_function.sgml
  doc/src/sgml/ref/pg_dump.sgml
Labels: マージ待ち（レビュー済み）

#1611 update vacuum and vacuumdb for 12
  doc/src/sgml/ref/vacuum.sgml
  doc/src/sgml/ref/vacuumdb.sgml
Labels: レビュー待ち

#1612 update auto-explain for 12
  doc/src/sgml/auto-explain.sgml
Labels: レビュー待ち

#1613 update spgist for 12
  doc/src/sgml/spgist.sgml
Labels: レビュー待ち

#1621 minor fix of func
  doc/src/sgml/func.sgml
  doc/src/sgml/func4.sgml
Labels: レビュー待ち

#1622 config.sgmlで前からの修正漏れがありました。
  doc/src/sgml/config.sgml
  doc/src/sgml/config3.sgml
Labels: レビュー待ち

#1610 update prepare for 12
  doc/src/sgml/plpgsql.sgml
  doc/src/sgml/protocol.sgml
  doc/src/sgml/ref/prepare.sgml
  doc/src/sgml/release-12.sgml
Labels: 再レビュー待ち

#1616 update ecpg for 12
  doc/src/sgml/ecpg.sgml
Labels: マージ待ち（レビュー済み）

#1619 update maintenance for 12
  doc/src/sgml/maintenance.sgml
Labels: レビュー待ち

#1620 update commit for 12
  doc/src/sgml/ref/commit.sgml
Labels: レビュー待ち

#1601 ddl.sgmlのPostgreSQL 12.0対応です。
  doc/src/sgml/ddl.sgml
Labels: 他にも誰か見て（レビュー済み）

#1624 update rollback for 12
  doc/src/sgml/ref/rollback.sgml
Labels: レビュー待ち

#1625 update storage for 12
  doc/src/sgml/storage.sgml
Labels: レビュー待ち

#1618 bki.sgml を PG12対応翻訳しました
  doc/src/sgml/bki.sgml
Labels: 他にも誰か見て（レビュー済み）

#1627 update spi for 12
  doc/src/sgml/spi.sgml
Labels: マージ待ち（レビュー済み）

#1623 catalogs.sgmlのPostgreSQL 12.0対応です。
  doc/src/sgml/catalogs.sgml
Labels: マージ待ち（レビュー済み）

#1617 runtime.sgmlのPostgreSQL 12.0対応です。
  doc/src/sgml/runtime.sgml
Labels: 再レビュー待ち

#1626 PG12 で追加された tableam.sgml を翻訳。
  doc/src/sgml/tableam.sgml
Labels: 再レビュー待ち
