Repository pgsql-jp/jpug-doc, pull requests merged in 2020-11, with the labels that each got.

#1780 extensionの12.4対応です。
  doc/src/sgml/extend.sgml
Labels: マージ待ち（レビュー済み）

#1784 remove an extra space
  doc/src/sgml/extend.sgml
Labels: レビュー待ち

#1785 Update backup.sgml
  doc/src/sgml/backup.sgml
Labels: レビュー待ち

#1787 Fix backup 12.4
  doc/src/sgml/backup.sgml
Labels: レビュー待ち

#1777 logical-replication.sgmlの12.4対応
  doc/src/sgml/logical-replication.sgml
Labels: マージ待ち（レビュー済み）

#1782 datetimeの12.4対応
  doc/src/sgml/datetime.sgml
Labels: 他にも誰か見て（レビュー済み）

#1788 翻訳の改善、誤訳の修正
  doc/src/sgml/wal.sgml
Labels: レビュー待ち

#1791 pull requestに対して自動でラベルを付ける
  .github/workflows/pr-label.yml
Labels: レビュー待ち

#1790 ブランチのマージによりはじかれた12.4の差分を再度適用
  doc/src/sgml/func.sgml
  doc/src/sgml/func1.sgml
  doc/src/sgml/func2.sgml
  doc/src/sgml/func3.sgml
  doc/src/sgml/func4.sgml
Labels: レビュー待ち

#1792 pltcl.sgmlの13.1対応です
  doc/src/sgml/pltcl.sgml
Labels: レビュー待ち

#1794 legal.sgmlの13.1対応です。
  doc/src/sgml/legal.sgml
Labels: レビュー待ち

#1797 タイポ修正
  doc/src/sgml/runtime.sgml
Labels: レビュー待ち

#1798 翻訳の改善
  doc/src/sgml/runtime.sgml
Labels: レビュー待ち

#1799 indices.sgml の13.1対応です。
  doc/src/sgml/indices.sgml
Labels: レビュー待ち

#1801 fix typo in brin
  doc/src/sgml/brin.sgml
Labels: レビュー待ち

#1806 update tsm-system-rows for 13.1
  doc/src/sgml/tsm-system-rows.sgml
Labels: レビュー待ち

#1807 update vacuumlo for 13.1
  doc/src/sgml/vacuumlo.sgml
Labels: レビュー待ち

#1808 update tsm-system-time for 13.1
  doc/src/sgml/tsm-system-time.sgml
Labels: レビュー待ち

#1803 update alter_collation etc. for 13.1
  doc/src/sgml/ref/alter_collation.sgml
  doc/src/sgml/ref/alter_function.sgml
  doc/src/sgml/ref/alter_index.sgml
Labels: レビュー待ち

#1809 sources.sgmlの13.1対応です。
  doc/src/sgml/sources.sgml
Labels: レビュー待ち

#1810 update wal for 13.1
  doc/src/sgml/wal.sgml
Labels: レビュー待ち
