Repository pgsql-jp/jpug-doc, pull requests merged in 2020-02, with the labels that each got.

#1628 update plpgsql for 12
  doc/src/sgml/plpgsql.sgml
Labels: レビュー待ち

#1629 PG12で追加された pg_checksums.sgml を翻訳。
  doc/src/sgml/ref/pg_checksums.sgml
Labels: 指摘事項あり

#1632 fix 'alone' word
  doc/src/sgml/func.sgml
  doc/src/sgml/func4.sgml
  doc/src/sgml/indices.sgml
Labels: マージ待ち（レビュー済み）

#1631 update reindex for 12
  doc/src/sgml/ref/reindex.sgml
Labels: 再レビュー待ち

#1630 Update charset for 12
  doc/src/sgml/charset.sgml
Labels: 他にも誰か見て（レビュー済み）

#1633 update xfunc for 12
  doc/src/sgml/xfunc.sgml
Labels: レビュー待ち

#1605 update textsearch for 12
  doc/src/sgml/textsearch.sgml
Labels: 再レビュー待ち
