Repository pgsql-jp/jpug-doc, pull requests merged in 2020-05, with the labels that each got.

#1659 remove an extra white space
  doc/src/sgml/ref/create_table.sgml
Labels: レビュー待ち

#1661 information_schema.sgml の翻訳漏れ
  doc/src/sgml/information_schema.sgml
Labels: レビュー待ち

#1662 logicaldecoding.sgml の12.0対応修正漏れ
  doc/src/sgml/logicaldecoding.sgml
Labels: レビュー待ち

#1658 monitoring.sgml の PostgreSQL 12対応翻訳です。
  doc/src/sgml/monitoring.sgml
Labels: 再レビュー待ち

#1660 func.sgmlの12.0の修正漏れ追加
  doc/src/sgml/func.sgml
Labels: マージ待ち（レビュー済み）

#1663 typo修正
  doc/src/sgml/ref/create_table.sgml
Labels: レビュー待ち

#1664 原文が消えていたのを復帰
  doc/src/sgml/monitoring.sgml
Labels: レビュー待ち

#1665 table column をテーブル列からtable columnに変更
  doc/src/sgml/ddl.sgml
Labels: レビュー待ち

#1677 update legal for 12.3
  doc/src/sgml/legal.sgml
Labels: レビュー待ち

#1678 update create_role for 12.3
  doc/src/sgml/ref/create_role.sgml
Labels: レビュー待ち

#1676 update pgbench etc. for 12.3
  doc/src/sgml/ref/pgarchivecleanup.sgml
  doc/src/sgml/ref/pgbench.sgml
  doc/src/sgml/ref/pgtestfsync.sgml
Labels: マージ待ち（レビュー済み）

#1681 update ref/refresh... etc. for 12.3
  doc/src/sgml/ref/refresh_materialized_view.sgml
  doc/src/sgml/ref/security_label.sgml
  doc/src/sgml/ref/set_role.sgml
Labels: レビュー待ち

#1680 update rules and runtime for 12.3
  doc/src/sgml/rules.sgml
  doc/src/sgml/runtime.sgml
Labels: マージ待ち（レビュー済み）

#1684 update revoke and select for 12.3
  doc/src/sgml/ref/revoke.sgml
  doc/src/sgml/ref/select.sgml
Labels: マージ待ち（レビュー済み）

#1685 wrong translation of "false positive"
  doc/src/sgml/amcheck.sgml
  doc/src/sgml/bloom.sgml
  doc/src/sgml/config.sgml
  doc/src/sgml/config2.sgml
Labels: マージ待ち（レビュー済み）
