Repository pgsql-jp/jpug-doc, pull requests merged in 2020-04, with the labels that each got.

#1646 features.sgml の PostgreSQL 12対応翻訳
  doc/src/sgml/features.sgml
Labels: 再レビュー待ち

#1644 update psql-ref for 12
  doc/src/sgml/acronyms.sgml
  doc/src/sgml/ref/psql-ref.sgml
Labels: マージ待ち（レビュー済み）

#1653 fix typo in libpq
  doc/src/sgml/libpq.sgml
Labels: レビュー待ち

#1647 update regress for 12
  doc/src/sgml/regress.sgml
Labels: レビュー待ち

#1648 update pgbench for 12
  doc/src/sgml/ref/pgbench.sgml
Labels: レビュー待ち

#1649 update planstats for 12
  doc/src/sgml/planstats.sgml
Labels: 再レビュー待ち

#1650 translate limits for 12
  doc/src/sgml/limits.sgml
Labels: 再レビュー待ち

#1651 update libpq for 12
  doc/src/sgml/libpq.sgml
Labels: 再レビュー待ち

#1635 indices.sgmlの12.0対応です。
  doc/src/sgml/indices.sgml
Labels: 再レビュー待ち

#1655 fix typos in libpq
  doc/src/sgml/libpq.sgml
Labels: 再レビュー待ち

#1652 CREATE TABLE リファレンスの PostgreSQL 12対応翻訳
  doc/src/sgml/ref/create_table.sgml
Labels: 再レビュー待ち

#1654 json.sgmlの12.0対応です。
  doc/src/sgml/json.sgml
Labels: 再レビュー待ち

#1657 アクセッサ演算子をアクセサ演算子に変更
  doc/src/sgml/func.sgml
  doc/src/sgml/func2.sgml
  doc/src/sgml/func3.sgml
Labels: レビュー待ち
