Repository pgsql-jp/jpug-doc, pull requests merged in 2020-07, with the labels that each got.

#1709 datatype.sgmlの12.3対応
  doc/src/sgml/datatype.sgml
Labels: 他にも誰か見て（レビュー済み）

#1708 config.sgmlのPostgreSQL 12.3対応です。
  doc/src/sgml/config.sgml
  doc/src/sgml/config0.sgml
  doc/src/sgml/config1.sgml
  doc/src/sgml/config2.sgml
  doc/src/sgml/config3.sgml
Labels: 再レビュー待ち

#1710 update textsearch for 12.3
  doc/src/sgml/textsearch.sgml
Labels: マージ待ち（レビュー済み）

#1718 Typoの修正です。
  doc/src/sgml/config.sgml
  doc/src/sgml/config2.sgml
Labels: レビュー待ち

#1719 fix typo in config
  doc/src/sgml/config.sgml
  doc/src/sgml/config3.sgml
Labels: レビュー待ち

#1721 high-availability.sgmlのPostgreSQL 12.3対応です。
  doc/src/sgml/high-availability.sgml
Labels: レビュー待ち

#1722 monitoring.sgmlのPostgreSQL 12.3対応です。
  doc/src/sgml/monitoring.sgml
Labels: レビュー待ち

#1725 remove extra white space
  doc/src/sgml/config.sgml
  doc/src/sgml/config3.sgml
Labels: レビュー待ち

#1720 func.sgmlのPostgreSQL 12.3対応です。
  doc/src/sgml/func.sgml
  doc/src/sgml/func1.sgml
  doc/src/sgml/func2.sgml
  doc/src/sgml/func3.sgml
  doc/src/sgml/func4.sgml
Labels: レビュー待ち

#1711 12.3 リリースノート翻訳です。
  doc/src/sgml/release-12.sgml
Labels: 指摘事項あり

#1717 ddl.sgmlのPostgreSQL 12.3対応です。
  doc/src/sgml/ddl.sgml
Labels: 再レビュー待ち

#1724 perform.sgmlのPostgreSQL 12.3対応です。
  doc/src/sgml/perform.sgml
Labels: 再レビュー待ち

#1726 postgres-fdw.sgmlの12.3対応です。
  doc/src/sgml/postgres-fdw.sgml
Labels: マージ待ち（レビュー済み）

#1727 trigger.sgmlの12.3対応です。
  doc/src/sgml/trigger.sgml
Labels: マージ待ち（レビュー済み）

#1728 sources.sgmlの12.3対応です。
  doc/src/sgml/sources.sgml
Labels: マージ待ち（レビュー済み）

#1730 extend.sgmlの12.3対応です。
  doc/src/sgml/extend.sgml
Labels: マージ待ち（レビュー済み）
