Repository pgsql-jp/jpug-doc, pull requests merged in 2020-10, with the labels that each got.

#1774 update acronyms etc. for 12.4
  doc/src/sgml/acronyms.sgml
  doc/src/sgml/earthdistance.sgml
Labels: レビュー待ち

#1773 Doc ja 12 4 release
  doc/src/sgml/release-12.sgml
Labels: 指摘事項あり

#1763 update mvcc for 12.4
  doc/src/sgml/mvcc.sgml
Labels: 再レビュー待ち

#1778 fdwhandlerの12.4対応
  doc/src/sgml/fdwhandler.sgml
Labels: マージ待ち（レビュー済み）

#1775 update create_extension for 12.4
  doc/src/sgml/ref/create_extension.sgml
Labels: マージ待ち（レビュー済み）
