Repository pgsql-jp/jpug-doc, pull requests merged in 2021-06, with the labels that each got.

#1923 logical-replication.sgmlのマージ時に消してしまった箇所の復活
  doc/src/sgml/logical-replication.sgml
Labels: レビュー待ち

#1922 extend.sgmlのマージ時に消してしまった箇所の復活です。
  doc/src/sgml/extend.sgml
Labels: レビュー待ち

#1925 remove extra ws from extend
  doc/src/sgml/extend.sgml
Labels: レビュー待ち

#1927 不要なタブを削除しました。
  doc/src/sgml/intarray.sgml
Labels: レビュー待ち

#1857 リリースノートの13, 13.1 バージョン対応翻訳。
  doc/src/sgml/release-13.sgml
Labels: 再レビュー待ち

#1931 para内のコメント-翻訳の形式を修正
  doc/src/sgml/backup.sgml
  doc/src/sgml/bki.sgml
  doc/src/sgml/charset.sgml
  doc/src/sgml/config.sgml
Labels: レビュー待ち

#1932 マージ等で重複してしまった箇所の削除
  doc/src/sgml/ref/alter_default_privileges.sgml
  doc/src/sgml/ref/create_table.sgml
  doc/src/sgml/ref/create_trigger.sgml
  doc/src/sgml/ref/ecpg-ref.sgml
  doc/src/sgml/ref/grant.sgml
  doc/src/sgml/ref/prepare.sgml
Labels: レビュー待ち

#1937 変更漏れがあった日本語側のURLを修正
  doc/src/sgml/acronyms.sgml
  doc/src/sgml/advanced.sgml
  doc/src/sgml/charset.sgml
  doc/src/sgml/docguide.sgml
  doc/src/sgml/info.sgml
  doc/src/sgml/plperl.sgml
  doc/src/sgml/textsearch.sgml
Labels: レビュー待ち

#1935 重複箇所の削除
  doc/src/sgml/postgres-fdw.sgml
Labels: レビュー待ち

#1938 タグの変更を追従
  doc/src/sgml/custom-scan.sgml
  doc/src/sgml/history.sgml
  doc/src/sgml/maintenance.sgml
  doc/src/sgml/storage.sgml
  doc/src/sgml/user-manag.sgml
  doc/src/sgml/xfunc.sgml
  doc/src/sgml/xml2.sgml
Labels: レビュー待ち

#1940 fix "superuser"
  doc/src/sgml/adminpack.sgml
  doc/src/sgml/config.sgml
  doc/src/sgml/config3.sgml
  doc/src/sgml/ddl.sgml
  doc/src/sgml/logical-replication.sgml
  doc/src/sgml/pltcl.sgml
Labels: レビュー待ち

#1939 原文の変更に追従とtypo修正
  doc/src/sgml/config.sgml
  doc/src/sgml/config0.sgml
  doc/src/sgml/config1.sgml
  doc/src/sgml/config2.sgml
  doc/src/sgml/config3.sgml
Labels: レビュー待ち

#1934 pgtrgm.sgmlの13.1対応のため12.4翻訳を適用したものです。
  doc/src/sgml/pgtrgm.sgml
Labels: マージ待ち（レビュー済み）

#1814 func.sgmlのPostgreSQL 13.1対応です。
  doc/src/sgml/func.sgml
  doc/src/sgml/func0.sgml
  doc/src/sgml/func1.sgml
  doc/src/sgml/func2.sgml
  doc/src/sgml/func3.sgml
  doc/src/sgml/func4.sgml
Labels: 再レビュー待ち

#1944 installation.sgmlのurlとpathの更新漏れを追従
  doc/src/sgml/installation.sgml
Labels: レビュー待ち

#1943 翻訳の更新が漏れていた箇所の修正
  doc/src/sgml/fdwhandler.sgml
  doc/src/sgml/indexam.sgml
  doc/src/sgml/regress.sgml
  doc/src/sgml/trigger.sgml
Labels: レビュー待ち

#1946 func.sgmlの以前のタグの変更漏れとtypo修正
  doc/src/sgml/func.sgml
  doc/src/sgml/func1.sgml
  doc/src/sgml/func2.sgml
  doc/src/sgml/func4.sgml
Labels: レビュー待ち

#1945 タグの変更の追従とtypo修正
  doc/src/sgml/ref/alter_procedure.sgml
  doc/src/sgml/ref/create_database.sgml
  doc/src/sgml/ref/create_function.sgml
  doc/src/sgml/ref/create_index.sgml
  doc/src/sgml/ref/create_type.sgml
  doc/src/sgml/ref/initdb.sgml
  doc/src/sgml/ref/pg_dump.sgml
  doc/src/sgml/ref/pg_restore.sgml
  doc/src/sgml/ref/pgarchivecleanup.sgml
  doc/src/sgml/ref/pgbench.sgml
  doc/src/sgml/ref/pgtesttiming.sgml
  doc/src/sgml/ref/postgres-ref.sgml
  doc/src/sgml/ref/select.sgml
  doc/src/sgml/ref/set.sgml
  doc/src/sgml/ref/set_constraints.sgml
  doc/src/sgml/ref/set_session_auth.sgml
  doc/src/sgml/ref/update.sgml
Labels: レビュー待ち

#1930 monitoring.sgmlの13.1対応として12.4の翻訳を自動組み込み
  doc/src/sgml/monitoring.sgml
Labels: レビュー待ち

#1948 たまたま見つけたfunc.sgmlの翻訳漏れの修正です。
  doc/src/sgml/func.sgml
  doc/src/sgml/func4.sgml
Labels: レビュー待ち

#1926 ddl.sgmlのPostgreSQL 13.1対応です。
  doc/src/sgml/ddl.sgml
Labels: マージ待ち（レビュー済み）

#1936 high-availability.sgmlのPostgreSQL 13.1対応です。
  doc/src/sgml/high-availability.sgml
Labels: マージ待ち（レビュー済み）

#1942 update pgtrgm for 13.1
  doc/src/sgml/pgtrgm.sgml
Labels: マージ待ち（レビュー済み）

#1928 catalogs.sgmlの前バージョンからの自動組み込み
  doc/src/sgml/catalogs.sgml
Labels: レビュー待ち

#1951 古い記述が残っていた箇所の削除と修正です。
  doc/src/sgml/mvcc.sgml
  doc/src/sgml/ref/create_table.sgml
  doc/src/sgml/ref/pg_basebackup.sgml
  doc/src/sgml/ref/pg_resetwal.sgml
  doc/src/sgml/ref/pgupgrade.sgml
  doc/src/sgml/ref/psql-ref.sgml
  doc/src/sgml/ref/set_transaction.sgml
Labels: 再レビュー待ち

#1950 func.sgmlで更に翻訳漏れを見つけました。
  doc/src/sgml/func.sgml
  doc/src/sgml/func4.sgml
Labels: 再レビュー待ち

#1955 fix writer
  doc/src/sgml/config.sgml
  doc/src/sgml/config0.sgml
  doc/src/sgml/logicaldecoding.sgml
Labels: レビュー待ち

#1929 information_schema.sgml の13.1対応として12.4の訳を適用
  doc/src/sgml/information_schema.sgml
Labels: レビュー待ち

#1941 functionタグの自動変換
  doc/src/sgml/libpq.sgml
Labels: レビュー待ち

#1954 翻訳漏れ、タグの修正漏れ、コメントのタグ修正等の修正です。
  doc/src/sgml/ddl.sgml
  doc/src/sgml/ecpg.sgml
  doc/src/sgml/hstore.sgml
  doc/src/sgml/ref/create_table.sgml
Labels: レビュー待ち

#1949 queries.sgml の13.1対応です。
  doc/src/sgml/queries.sgml
Labels: レビュー待ち

#1959 pgbuffercache.sgml の表を他にあわせて修正
  doc/src/sgml/pgbuffercache.sgml
Labels: レビュー待ち

#1913 13.1 バージョン btree.sgml の翻訳
  doc/src/sgml/btree.sgml
Labels: 再レビュー待ち

#1958 information_schema.sgml の13.1対応です。
  doc/src/sgml/information_schema.sgml
Labels: レビュー待ち

#1956 protocol.sgmlの13.1対応です
  doc/src/sgml/protocol.sgml
Labels: マージ待ち（レビュー済み）
