Repository pgsql-jp/jpug-doc, pull requests merged in 2021-09, with the labels that each got.

#1989 v13の貢献者を記載
  doc/src/sgml/jpug-doc.sgml
Labels: レビュー待ち

#1990 斉藤さんの指摘事項を反映しました。
  doc/src/sgml/glossary.sgml
Labels: レビュー待ち

#1991 glossary.sgmlの13.1対応(属性、列)
  doc/src/sgml/glossary.sgml
Labels: レビュー待ち

#1993 日本語側のタグが抜けている箇所をチェックして修正
  doc/src/sgml/backup.sgml
  doc/src/sgml/catalogs.sgml
  doc/src/sgml/catalogs0.sgml
  doc/src/sgml/catalogs1.sgml
  doc/src/sgml/catalogs2.sgml
  doc/src/sgml/catalogs3.sgml
  doc/src/sgml/catalogs4.sgml
Labels: レビュー待ち

#1994 日本語側のタグが抜けている箇所をチェックして修正２
  doc/src/sgml/ref/alter_role.sgml
  doc/src/sgml/ref/alter_table.sgml
  doc/src/sgml/ref/copy.sgml
  doc/src/sgml/ref/create_role.sgml
  doc/src/sgml/ref/create_sequence.sgml
  doc/src/sgml/ref/delete.sgml
  doc/src/sgml/ref/drop_aggregate.sgml
  doc/src/sgml/ref/drop_policy.sgml
  doc/src/sgml/ref/pg_rewind.sgml
  doc/src/sgml/ref/pgbench.sgml
  doc/src/sgml/ref/pgupgrade.sgml
  doc/src/sgml/ref/psql-ref.sgml
  doc/src/sgml/ref/reassign_owned.sgml
Labels: レビュー待ち

#1995 日本語側のタグが抜けている箇所をチェックして修正３
  doc/src/sgml/arch-dev.sgml
  doc/src/sgml/diskusage.sgml
  doc/src/sgml/ecpg.sgml
  doc/src/sgml/geqo.sgml
  doc/src/sgml/maintenance.sgml
  doc/src/sgml/monitoring.sgml
  doc/src/sgml/regress.sgml
  doc/src/sgml/spi.sgml
  doc/src/sgml/storage.sgml
  doc/src/sgml/xfunc.sgml
  doc/src/sgml/xindex.sgml
Labels: レビュー待ち

#1992 glossary.sgmlのPostgreSQL 13.1対応です。
  doc/src/sgml/glossary.sgml
Labels: 再レビュー待ち

#1996 glossary.sgmlのPostgreSQL 13.1対応です。
  doc/src/sgml/glossary.sgml
Labels: レビュー待ち

#1998 日本語側のタグが抜けている箇所をチェックして修正４
  doc/src/sgml/brin.sgml
  doc/src/sgml/pgtrgm.sgml
  doc/src/sgml/sepgsql.sgml
  doc/src/sgml/trigger.sgml
Labels: レビュー待ち

#1999 日本語側のタグが抜けている箇所をチェックして修正５
  doc/src/sgml/config.sgml
  doc/src/sgml/config0.sgml
  doc/src/sgml/config1.sgml
  doc/src/sgml/config2.sgml
  doc/src/sgml/dblink.sgml
  doc/src/sgml/func.sgml
  doc/src/sgml/func1.sgml
  doc/src/sgml/func2.sgml
  doc/src/sgml/func3.sgml
  doc/src/sgml/func4.sgml
  doc/src/sgml/installation.sgml
  doc/src/sgml/logicaldecoding.sgml
  doc/src/sgml/ref/psql-ref.sgml
  doc/src/sgml/textsearch.sgml
Labels: レビュー待ち

#1997 glossary.sgmlの13.1対応（リレーション関連）
  doc/src/sgml/glossary.sgml
Labels: 再レビュー待ち

#2001 glossary.sgmlの13.1対応（ビュー）
  doc/src/sgml/glossary.sgml
Labels: レビュー待ち

#2003 glossary.sgmlのPostgreSQL 13.1対応です。
  doc/src/sgml/glossary.sgml
Labels: レビュー待ち

#2002 glossary.sgmlの13.1対応（シーケンス）
  doc/src/sgml/glossary.sgml
Labels: レビュー待ち

#2004 glossary.sgmlのPostgreSQL 13.1対応です。
  doc/src/sgml/glossary.sgml
Labels: レビュー待ち

#2005 glossary.sgmlのPostgreSQL 13.1対応です（"d"の項目）
  doc/src/sgml/glossary.sgml
Labels: レビュー待ち

#2006 glossary.sgmlのPostgreSQL 13.1対応です("e"から"f"まで)
  doc/src/sgml/glossary.sgml
Labels: 再レビュー待ち

#2009 glossary.sgmlの13.1対応(walとwindow関数)
  doc/src/sgml/glossary.sgml
Labels: 再レビュー待ち

#2010 開放->解放 の方が正しいと気づいたので修正
  doc/src/sgml/backup.sgml
  doc/src/sgml/libpq.sgml
  doc/src/sgml/plpython.sgml
  doc/src/sgml/xfunc.sgml
Labels: レビュー待ち

#2011 fix typo in glossary
  doc/src/sgml/glossary.sgml
Labels: レビュー待ち

#2012 glossary.sgmlのPosgreSQL 13.1対応です("j"から"l"まで)
  doc/src/sgml/glossary.sgml
Labels: レビュー待ち

#2008 glossary.sgmlのPostgreSQL 13.1対応です。Constraint、"g"から"i"まで。
  doc/src/sgml/glossary.sgml
Labels: 再レビュー待ち

#2013 glossary.sgmlの13.1対応(v)
  doc/src/sgml/glossary.sgml
Labels: 再レビュー待ち

#2000 古い訳のままだった箇所の修正
  doc/src/sgml/contrib.sgml
  doc/src/sgml/datatype.sgml
  doc/src/sgml/high-availability.sgml
  doc/src/sgml/libpq.sgml
  doc/src/sgml/libpq0.sgml
  doc/src/sgml/libpq1.sgml
  doc/src/sgml/libpq2.sgml
  doc/src/sgml/libpq3.sgml
  doc/src/sgml/plpgsql.sgml
  doc/src/sgml/runtime.sgml
  doc/src/sgml/spgist.sgml
Labels: 他にも誰か見て（レビュー済み）

#2015 glossary.sgmlの13.1対応(User mapping)
  doc/src/sgml/glossary.sgml
Labels: レビュー待ち

#2016 glossary.sgmlの13.1対応(Unlogged)
  doc/src/sgml/glossary.sgml
Labels: レビュー待ち

#2014 glossary.sgmlのPostgreSQL 13.1対応です("m")
  doc/src/sgml/glossary.sgml
Labels: レビュー待ち

#2017 斉藤さんの指摘に対応しました。
  doc/src/sgml/glossary.sgml
Labels: レビュー待ち

#2019 glossary.sgmlの13.1対応(unique constraint)
  doc/src/sgml/glossary.sgml
Labels: レビュー待ち

#2018 glossary.sgmlのPosgreSQL 13.1対応です("n"から"p"まで)
  doc/src/sgml/glossary.sgml
Labels: 再レビュー待ち

#2020 glossary.sgmlのPostgreSQL 13.1対応です。("q"から"r"まで)
  doc/src/sgml/glossary.sgml
Labels: 再レビュー待ち

#2024 ＃2007で指摘された箇所の修正
  doc/src/sgml/config.sgml
  doc/src/sgml/config2.sgml
  doc/src/sgml/config3.sgml
Labels: レビュー待ち

#2022 glossary.sgmlの13.1対応(t)
  doc/src/sgml/glossary.sgml
Labels: 再レビュー待ち

#2023 glossary.sgmlのPostgreSQL 13.1対応です("s"の項)
  doc/src/sgml/glossary.sgml
Labels: 再レビュー待ち

#2025 タグが足りていない箇所を修正
  doc/src/sgml/glossary.sgml
Labels: レビュー待ち

#2028 Schemaの翻訳漏れを修正
  doc/src/sgml/glossary.sgml
Labels: レビュー待ち

#2027 glossaryの見出しの形式を英語【日本語】（補足）に変更
  doc/src/sgml/glossary.sgml
Labels: レビュー待ち

#2030 ACIDの文言の統一（調整）
  doc/src/sgml/glossary.sgml
Labels: レビュー待ち

#2038 titleが「〜 Columns」になってしまったのを「の列」に修正
  doc/src/sgml/catalogs.sgml
  doc/src/sgml/catalogs0.sgml
  doc/src/sgml/catalogs1.sgml
  doc/src/sgml/catalogs2.sgml
  doc/src/sgml/catalogs3.sgml
  doc/src/sgml/catalogs4.sgml
Labels: レビュー待ち
