Repository pgsql-jp/jpug-doc, pull requests merged in 2021-05, with the labels that each got.

#1907 update alter/create_table.sgml for 13.1
  doc/src/sgml/ref/alter_table.sgml
  doc/src/sgml/ref/create_table.sgml
Labels: マージ待ち（レビュー済み）

#1911 fix typo in pg_basebackup
  doc/src/sgml/ref/pg_basebackup.sgml
Labels: レビュー待ち

#1909 xfunc.sgmlの13.1対応です
  doc/src/sgml/xfunc.sgml
Labels: 再レビュー待ち

#1910 update pg_dump for 13.1
  doc/src/sgml/ref/pg_dump.sgml
Labels: マージ待ち（レビュー済み）

#1915 update plperl for 13.1
  doc/src/sgml/plperl.sgml
Labels: マージ待ち（レビュー済み）

#1908 update psql-ref for 13.1
  doc/src/sgml/ref/psql-ref.sgml
Labels: 再レビュー待ち

#1912 translate pg_verifybackup for 13.1
  doc/src/sgml/ref/pg_verifybackup.sgml
Labels: 他にも誰か見て（レビュー済み）

#1917 Update json.sgml
  doc/src/sgml/json.sgml
Labels: マージ待ち（レビュー済み）

#1916 Update datatype.sgml
  doc/src/sgml/datatype.sgml
Labels: レビュー待ち

#1918 postgres.sgml の13.1対応です。
  doc/src/sgml/postgres.sgml
Labels: レビュー待ち

#1920 Install Dependencies で失敗してしまうので直前にupdateを追加
  .github/workflows/test.yml
Labels: レビュー待ち

#1921 catalogs.sgmlを5分割するマーカーをコメントで入れました。
  doc/src/sgml/catalogs.sgml
  doc/src/sgml/split-catalogs.sh
Labels: レビュー待ち
