Repository pgsql-jp/jpug-doc, pull requests merged in 2021-07, with the labels that each got.

#1952 plpgsqlの13.1対応です。
  doc/src/sgml/plpgsql.sgml
Labels: 再レビュー待ち

#1933 13.x で追加された color.sgml を翻訳
  doc/src/sgml/color.sgml
Labels: 再レビュー待ち

#1924 13.x で追加された backup-manifest を翻訳。
  doc/src/sgml/backup-manifest.sgml
Labels: 再レビュー待ち

#1963 config.sgmlの未翻訳箇所を見つけました。
  doc/src/sgml/config.sgml
  doc/src/sgml/config1.sgml
  doc/src/sgml/config2.sgml
Labels: レビュー待ち

#1962 glossary.sgmlの定型句を置き換え
  doc/src/sgml/glossary.sgml
Labels: レビュー待ち

#1953 catalogs.sgmlのPostgreSQL 13.1対応です。
  doc/src/sgml/catalogs.sgml
Labels: 再レビュー待ち

#1957 fix translation of 'predicate'
  doc/src/sgml/catalogs.sgml
Labels: マージ待ち（レビュー済み）

#1961 update logical_replication for 13.1
  doc/src/sgml/logical-replication.sgml
Labels: レビュー待ち

#1968 タグ、URL、古い記述を修正した
  doc/src/sgml/catalogs.sgml
  doc/src/sgml/config.sgml
  doc/src/sgml/pgcrypto.sgml
  doc/src/sgml/plpython.sgml
  doc/src/sgml/ref/pg_ctl-ref.sgml
Labels: レビュー待ち

#1960 update monitoring for 13.1
  doc/src/sgml/monitoring.sgml
Labels: 再レビュー待ち
