Repository pgsql-jp/jpug-doc, pull requests merged in 2021-12, with the labels that each got.

#2071 update ref/pgupgrade for 14.0
  doc/src/sgml/ref/pgupgrade.sgml
Labels: 再レビュー待ち

#2096 high-availability.sgmlの翻訳文の修正
  doc/src/sgml/high-availability.sgml
Labels: レビュー待ち

#2077 update grant and revoke for 14.0
  doc/src/sgml/ref/grant.sgml
  doc/src/sgml/ref/revoke.sgml
Labels: レビュー待ち

#2078 update ref/explain for 14.0
  doc/src/sgml/ref/explain.sgml
Labels: レビュー待ち

#2087 split.shで分割されたfunc[0-4].sgmlを結合し、再びfunc.sgmlに戻すスクリプトです。
  doc/src/sgml/merge-func.sh
Labels: レビュー待ち

#2081 update pgtrgm and syntax for 14.0
  doc/src/sgml/pgtrgm.sgml
  doc/src/sgml/syntax.sgml
Labels: マージ待ち（レビュー済み）

#2082 update set_role for 14.0
  doc/src/sgml/ref/set_role.sgml
Labels: マージ待ち（レビュー済み）

#2084 update ref/reindexdb for 14.0
  doc/src/sgml/ref/reindexdb.sgml
Labels: レビュー待ち

#2085 update ref/*_operator for 14.0
  doc/src/sgml/ref/alter_operator.sgml
  doc/src/sgml/ref/create_operator.sgml
  doc/src/sgml/ref/drop_operator.sgml
Labels: レビュー待ち

#2086 update ref/create_conv etc. for 14.0
  doc/src/sgml/ref/create_aggregate.sgml
  doc/src/sgml/ref/create_conversion.sgml
Labels: レビュー待ち

#2089 update plhandler for 14.0
  doc/src/sgml/plhandler.sgml
Labels: レビュー待ち

#2076 update intarray for 14.0
  doc/src/sgml/intarray.sgml
Labels: 再レビュー待ち, レビュー待ち

#2106 high-availability.sgmlの翻訳文の修正（#2096の13へのバックポート）
  doc/src/sgml/high-availability.sgml
Labels: レビュー待ち, version 13

#2090 update ref/analyze and create_db for 14.0
  doc/src/sgml/ref/analyze.sgml
  doc/src/sgml/ref/create_database.sgml
Labels: レビュー待ち

#2093 update ref/create_trans and pg_rewind for 14.0
  doc/src/sgml/ref/create_transform.sgml
  doc/src/sgml/ref/pg_rewind.sgml
Labels: レビュー待ち

#2092 update docguide for 14.0
  doc/src/sgml/docguide.sgml
Labels: レビュー待ち

#2099 update query for 14.0
  doc/src/sgml/query.sgml
Labels: レビュー待ち

#2091 update installation for 14.0
  doc/src/sgml/installation.sgml
Labels: マージ待ち（レビュー済み）

#2107 update bki for 14.0
  doc/src/sgml/bki.sgml
Labels: 再レビュー待ち

#2080 update ref/create_view and declare for 14.0
  doc/src/sgml/ref/create_view.sgml
  doc/src/sgml/ref/declare.sgml
Labels: 再レビュー待ち

#2079 update maintenance and storage for 14.0
  doc/src/sgml/maintenance.sgml
  doc/src/sgml/storage.sgml
Labels: 再レビュー待ち

#2105 update drop_routine for 14.0
  doc/src/sgml/ref/drop_routine.sgml
Labels: マージ待ち（レビュー済み）

#2098 update ref/copy for 14.0
  doc/src/sgml/ref/copy.sgml
Labels: 再レビュー待ち

#2101 update ref/initdb for 14.0
  doc/src/sgml/ref/initdb.sgml
Labels: 再レビュー待ち

#2102 update backup for 14.0
  doc/src/sgml/backup.sgml
Labels: 再レビュー待ち

#2108 update ref/pg_resetwal for 14.0
  doc/src/sgml/ref/pg_resetwal.sgml
Labels: レビュー待ち

#2094 update ref/pg_basebackup.sgml for 14.0
  doc/src/sgml/ref/pg_basebackup.sgml
Labels: 再レビュー待ち

#2088 update ref/*_publication|subscription for 14.0
  doc/src/sgml/ref/alter_publication.sgml
  doc/src/sgml/ref/alter_subscription.sgml
  doc/src/sgml/ref/create_subscription.sgml
  doc/src/sgml/ref/drop_subscription.sgml
Labels: 他にも誰か見て（レビュー済み）

#2109 contrib.sgmlのPostgreSQL 14.0対応です。
  doc/src/sgml/contrib.sgml
Labels: 再レビュー待ち

#2100 update user-manag for 14.0
  doc/src/sgml/user-manag.sgml
Labels: マージ待ち（レビュー済み）

#2097 update ref/pg_dump etc. for 14.0
  doc/src/sgml/ref/pg_dump.sgml
  doc/src/sgml/ref/pg_dumpall.sgml
  doc/src/sgml/ref/pg_restore.sgml
Labels: 他にも誰か見て（レビュー済み）

#2113 start.sgmlの14.0対応です
  doc/src/sgml/start.sgml
Labels: レビュー待ち

#2114 drop_statistics.sgmlの翻訳です。
  doc/src/sgml/ref/drop_statistics.sgml
Labels: マージ待ち（レビュー済み）

#2104 appendix-obsolete*の14.0対応です。
  doc/src/sgml/appendix-obsolete-default-roles.sgml
  doc/src/sgml/appendix-obsolete-pgreceivexlog.sgml
  doc/src/sgml/appendix-obsolete-pgresetxlog.sgml
  doc/src/sgml/appendix-obsolete-pgxlogdump.sgml
  doc/src/sgml/appendix-obsolete-recovery-config.sgml
  doc/src/sgml/appendix-obsolete.sgml
Labels: マージ待ち（レビュー済み）

#2111 alter_type.sgml modified::
  doc/src/sgml/ref/alter_type.sgml
Labels: マージ待ち（レビュー済み）

#2115 glossary.sgmlの14.0対応です。
  doc/src/sgml/glossary.sgml
Labels: レビュー待ち
