Repository pgsql-jp/jpug-doc, pull requests merged in 2021-11, with the labels that each got.

#2050 update ref/rollback etc. for 14.0
  doc/src/sgml/ref/rollback.sgml
  doc/src/sgml/ref/rollback_to.sgml
  doc/src/sgml/ref/savepoint.sgml
Labels: レビュー待ち

#2047 update typeconv and xaggr
  doc/src/sgml/typeconv.sgml
  doc/src/sgml/xaggr.sgml
Labels: レビュー待ち

#2048 update ref/show etc. for 14.0
  doc/src/sgml/ref/show.sgml
  doc/src/sgml/ref/start_transaction.sgml
  doc/src/sgml/ref/truncate.sgml
Labels: レビュー待ち

#2051 update ref/prepare etc. for 14.0
  doc/src/sgml/ref/prepare.sgml
  doc/src/sgml/ref/prepare_transaction.sgml
  doc/src/sgml/ref/reassign_owned.sgml
  doc/src/sgml/ref/refresh_materialized_view.sgml
Labels: レビュー待ち

#2049 update ref/set etc. for 14.0
  doc/src/sgml/ref/security_label.sgml
  doc/src/sgml/ref/set.sgml
  doc/src/sgml/ref/set_session_auth.sgml
Labels: マージ待ち（レビュー済み）

#2045 pageinsepect.sgmlの14.0対応です
  doc/src/sgml/pageinspect.sgml
Labels: レビュー待ち

#2052 update ref/drop_group|owned for 14.0
  doc/src/sgml/ref/drop_group.sgml
  doc/src/sgml/ref/drop_owned.sgml
Labels: レビュー待ち

#2054 update ref/alter_extension,group for 14.0
  doc/src/sgml/ref/alter_extension.sgml
  doc/src/sgml/ref/alter_group.sgml
Labels: レビュー待ち

#2055 update ref/*user* for 14.0
  doc/src/sgml/ref/alter_user.sgml
  doc/src/sgml/ref/alter_user_mapping.sgml
  doc/src/sgml/ref/create_user.sgml
  doc/src/sgml/ref/create_user_mapping.sgml
  doc/src/sgml/ref/createuser.sgml
  doc/src/sgml/ref/drop_user.sgml
  doc/src/sgml/ref/drop_user_mapping.sgml
  doc/src/sgml/ref/dropuser.sgml
Labels: レビュー待ち

#2056 update ref/close etc. for 14.0
  doc/src/sgml/ref/close.sgml
  doc/src/sgml/ref/comment.sgml
  doc/src/sgml/ref/delete.sgml
  doc/src/sgml/ref/fetch.sgml
  doc/src/sgml/ref/lock.sgml
Labels: レビュー待ち

#2057 update dml for 14.0
  doc/src/sgml/dml.sgml
Labels: レビュー待ち

#2053 update sslinfo for 14.0
  doc/src/sgml/sslinfo.sgml
Labels: 再レビュー待ち

#2058 update *_role for 14.0
  doc/src/sgml/ref/alter_role.sgml
  doc/src/sgml/ref/create_role.sgml
  doc/src/sgml/ref/drop_role.sgml
Labels: マージ待ち（レビュー済み）

#2060 update ref/create|dropdb for 14.0
  doc/src/sgml/ref/createdb.sgml
  doc/src/sgml/ref/dropdb.sgml
Labels: レビュー待ち

#2061 update ref/alter_agg etc. for 14.0
  doc/src/sgml/ref/alter_aggregate.sgml
  doc/src/sgml/ref/create_aggregate.sgml
  doc/src/sgml/ref/create_cast.sgml
Labels: レビュー待ち

#2062 update sepgsql for 14.0
  doc/src/sgml/sepgsql.sgml
Labels: レビュー待ち

#2063 update ref/alter_domain etc. for 14.0
  doc/src/sgml/ref/alter_domain.sgml
  doc/src/sgml/ref/alter_materialized_view.sgml
  doc/src/sgml/ref/create_materialized_view.sgml
Labels: レビュー待ち

#2064 update ref/begin and end for 14.0
  doc/src/sgml/ref/begin.sgml
  doc/src/sgml/ref/end.sgml
Labels: レビュー待ち

#2065 update pl* for 14.0
  doc/src/sgml/plperl.sgml
  doc/src/sgml/plpython.sgml
  doc/src/sgml/pltcl.sgml
Labels: レビュー待ち

#2066 update nls etc. for 14.0
  doc/src/sgml/nls.sgml
  doc/src/sgml/pgrowlocks.sgml
  doc/src/sgml/tsm-system-rows.sgml
  doc/src/sgml/tsm-system-time.sgml
Labels: レビュー待ち

#2067 update ref/abort and create_opcls for 14.0
  doc/src/sgml/ref/abort.sgml
  doc/src/sgml/ref/create_opclass.sgml
Labels: レビュー待ち

#2068 update ref/alter_opf etc. for 14.0
  doc/src/sgml/ref/alter_opfamily.sgml
  doc/src/sgml/ref/create_foreign_table.sgml
Labels: レビュー待ち

#2069 update pgrcypto for 14.0
  doc/src/sgml/pgcrypto.sgml
Labels: レビュー待ち

#2070 update file-fwd for 14.0
  doc/src/sgml/file-fdw.sgml
Labels: レビュー待ち

#2072 update ref/postgres-ref for 14.0
  doc/src/sgml/ref/postgres-ref.sgml
Labels: レビュー待ち

#2059 update ref/*_lang|policy for 14.0
  doc/src/sgml/ref/create_language.sgml
  doc/src/sgml/ref/create_policy.sgml
  doc/src/sgml/ref/drop_language.sgml
Labels: 再レビュー待ち

#2074 update ref/alter_foreign_table for 14.0
  doc/src/sgml/ref/alter_foreign_table.sgml
Labels: レビュー待ち

#2075 update test-decoding and textsearch for 14.0
  doc/src/sgml/test-decoding.sgml
  doc/src/sgml/textsearch.sgml
Labels: レビュー待ち
