Repository pgsql-jp/jpug-doc, pull requests merged in 2021-08, with the labels that each got.

#1901 datatype.sgmlのv13対応
  doc/src/sgml/datatype.sgml
Labels: 再レビュー待ち

#1914 update alter type etc. for 13.1
  doc/src/sgml/ref/alter_opfamily.sgml
  doc/src/sgml/ref/alter_type.sgml
  doc/src/sgml/ref/create_opclass.sgml
Labels: 再レビュー待ち

#1965 func.sgmlの修正漏れの修正
  doc/src/sgml/func.sgml
  doc/src/sgml/func1.sgml
  doc/src/sgml/func2.sgml
  doc/src/sgml/func3.sgml
  doc/src/sgml/func4.sgml
Labels: 再レビュー待ち

#1969 Issues1967で指摘いただいたタグミスの修正
  doc/src/sgml/libpq.sgml
Labels: レビュー待ち

#1972 古い記述が残っていた箇所を更新
  doc/src/sgml/datatype.sgml
Labels: レビュー待ち

#1964 perform.sgmlの13.1対応です
  doc/src/sgml/perform.sgml
Labels: 再レビュー待ち

#1971 類似の箇所の翻訳と一部翻訳
  doc/src/sgml/glossary.sgml
Labels: レビュー待ち

#1973 2用語翻訳
  doc/src/sgml/glossary.sgml
Labels: レビュー待ち

#1966 extend.sgml の v13.1 の変更点を翻訳。
  doc/src/sgml/extend.sgml
Labels: マージ待ち（レビュー済み）

#1976 ltree.sgmlの翻訳漏れがあった箇所です
  doc/src/sgml/ltree.sgml
Labels: レビュー待ち

#1977 glossary.sgmlの「SQL standard」用語の訳。
  doc/src/sgml/glossary.sgml
Labels: レビュー待ち

#1970 runtime.sgmlの13.1対応です
  doc/src/sgml/runtime.sgml
Labels: 再レビュー待ち

#1978 translate Update and User in glossary
  doc/src/sgml/glossary.sgml
Labels: レビュー待ち

#1975 catalogs.sgmlの翻訳漏れがあった箇所です
  doc/src/sgml/catalogs.sgml
Labels: 他にも誰か見て（レビュー済み）

#1982 catalogs.sgmlを5分割しました。
  doc/src/sgml/catalogs0.sgml
  doc/src/sgml/catalogs1.sgml
  doc/src/sgml/catalogs2.sgml
  doc/src/sgml/catalogs3.sgml
  doc/src/sgml/catalogs4.sgml
Labels: レビュー待ち

#1981 plpgsql.sgmlのPostgreSQL 13.1対応における追加修正です。
  doc/src/sgml/plpgsql.sgml
Labels: レビュー待ち

#1974 pageinspect.sgmlの13.1対応です
  doc/src/sgml/pageinspect.sgml
Labels: 再レビュー待ち

#1983 glossary.sgmlのSQLコマンドを翻訳
  doc/src/sgml/glossary.sgml
Labels: レビュー待ち

#1979 libpq.sgml の V13 対応翻訳
  doc/src/sgml/libpq.sgml
Labels: 再レビュー待ち, マージ待ち（レビュー済み）

#1985 libpq.sgmlを4分割にします。
  doc/src/sgml/libpq.sgml
  doc/src/sgml/split-libpq.sh
Labels: レビュー待ち

#1984 charset.sgmlの13対応の翻訳
  doc/src/sgml/charset.sgml
Labels: マージ待ち（レビュー済み）

#1987 fix comments in split shells
  doc/src/sgml/split-catalogs.sh
  doc/src/sgml/split-libpq.sh
Labels: レビュー待ち

#1986 glossary.sgmlのPostgreSQL 13.1対応です。(Transaction ID)
  doc/src/sgml/glossary.sgml
Labels: レビュー待ち

#1988 translate grant in glossary
  doc/src/sgml/glossary.sgml
Labels: レビュー待ち
