Repository pgsql-jp/jpug-doc, pull requests merged in 2021-01, with the labels that each got.

#1830 update create_aggregate/conversion for 13.1
  doc/src/sgml/ref/create_aggregate.sgml
  doc/src/sgml/ref/create_conversion.sgml
Labels: レビュー待ち

#1831 update docguide etc. for 13.1
  doc/src/sgml/docguide.sgml
  doc/src/sgml/install-windows.sgml
  doc/src/sgml/oid2name.sgml
  doc/src/sgml/pgcrypto.sgml
Labels: レビュー待ち

#1833 update mvcc for 13.1
  doc/src/sgml/mvcc.sgml
Labels: レビュー待ち

#1835 fix translation of "single user"
  doc/src/sgml/parallel.sgml
Labels: レビュー待ち

#1832 bgworker/client-authの13.1対応です
  doc/src/sgml/bgworker.sgml
  doc/src/sgml/client-auth.sgml
Labels: 再レビュー待ち

#1838 update ref/vacuum.sgml for 13.1
  doc/src/sgml/ref/vacuum.sgml
Labels: 再レビュー待ち

#1837 update ref/vacuumdb.sgml for 13.1
  doc/src/sgml/ref/vacuumdb.sgml
Labels: 再レビュー待ち

#1840 update dropdb etc. for 13.1
  doc/src/sgml/ref/drop_database.sgml
  doc/src/sgml/ref/dropdb.sgml
Labels: マージ待ち（レビュー済み）

#1834 update contrib for 13.1
  doc/src/sgml/contrib.sgml
Labels: 再レビュー待ち

#1804 update alter_trigger etc. for 13.1
  doc/src/sgml/ref/alter_materialized_view.sgml
  doc/src/sgml/ref/alter_role.sgml
  doc/src/sgml/ref/alter_tablespace.sgml
  doc/src/sgml/ref/alter_trigger.sgml
Labels: 再レビュー待ち

#1839 update pg_rewind for 13.1
  doc/src/sgml/ref/pg_rewind.sgml
Labels: 再レビュー待ち

#1841 update datetime.sgml for 13.1
  doc/src/sgml/datetime.sgml
Labels: 再レビュー待ち

#1842 remove extra white spaces
  doc/src/sgml/contrib.sgml
  doc/src/sgml/ref/vacuum.sgml
Labels: レビュー待ち

#1843 update spi for 13.1
  doc/src/sgml/spi.sgml
Labels: レビュー待ち

#1846 update sepgsql for 13.1
  doc/src/sgml/sepgsql.sgml
Labels: レビュー待ち
