Repository pgsql-jp/jpug-doc, pull requests merged in 2022-12, with the labels that each got.

#2440 func.sgmlのPostgreSQL 15.0対応です。
  doc/src/sgml/func.sgml
  doc/src/sgml/func1.sgml
  doc/src/sgml/func2.sgml
  doc/src/sgml/func3.sgml
  doc/src/sgml/func4.sgml
Labels: 再レビュー待ち

#2470 update pg_recvlogical for 15.0
  doc/src/sgml/ref/pg_recvlogical.sgml
Labels: マージは待って（レビュー中）

#2482 catalogs.sgmlのPostgreSQL 15.0対応です(パート3)
  doc/src/sgml/catalogs.sgml
  doc/src/sgml/catalogs3.sgml
Labels: レビュー待ち

#2478 catalogs.sgmlのPostgreSQL 15.0対応です(catalogs1.sgml部分)
  doc/src/sgml/catalogs.sgml
  doc/src/sgml/catalogs1.sgml
Labels: レビュー待ち

#2488 update alter_system for 15.0
  doc/src/sgml/ref/alter_system.sgml
Labels: マージ待ち（レビュー済み）

#2481 client-auth.sgmlのPR2480にsearch+bindの変更を追加
  doc/src/sgml/client-auth.sgml
Labels: マージ待ち（レビュー済み）

#2479 prepare.sgmlにおそらく誤訳と思われる箇所があるので修正提案です。
  doc/src/sgml/ref/prepare.sgml
Labels: 他にも誰か見て（レビュー済み）

#2499 round関数の訳を修正
  doc/src/sgml/func.sgml
Labels: マージ待ち（レビュー済み）

#2492 xfunc.sgmlの15.0対応です
  doc/src/sgml/xfunc.sgml
Labels: レビュー待ち

#2496 lobj.sgmlのPostgreSQL 15.0対応です。
  doc/src/sgml/lobj.sgml
Labels: 再レビュー待ち

#2500 queries.sgmlの15.0対応です
  doc/src/sgml/queries.sgml
Labels: レビュー待ち

#2503 他バージョンの文書として公式サイトへのリンク
  doc/src/sgml/stylesheet-custom.xsl
  doc/src/sgml/stylesheet.css
Labels: 再レビュー待ち

#2506 pg_dumpall.sgmlの15.0対応です
  doc/src/sgml/ref/pg_dumpall.sgml
Labels: 再レビュー待ち

#2507 pg_dump.sgmlの15.0対応です
  doc/src/sgml/ref/pg_dump.sgml
Labels: 再レビュー待ち

#2511 sources.sgmlのPostgreSQL 15.0対応です。
  doc/src/sgml/sources.sgml
Labels: レビュー待ち

#2497 update indices for 15.0
  doc/src/sgml/indices.sgml
Labels: 再レビュー待ち

#2483 update json for 15.0
  doc/src/sgml/json.sgml
Labels: 再レビュー待ち

#2487 system-views.sgmlのPostgreSQL 15.0対応です。
  doc/src/sgml/system-views.sgml
Labels: 再レビュー待ち

#2494 add "ブーリアン" to NG list
  .ng.list
  doc/src/sgml/ref/create_foreign_table.sgml
  doc/src/sgml/ref/insert.sgml
  doc/src/sgml/syntax.sgml
Labels: マージ待ち（レビュー済み）

#2502 monitoring.sgmlの15.0対応です
  doc/src/sgml/monitoring.sgml
Labels: 再レビュー待ち
