Repository pgsql-jp/jpug-doc, pull requests merged in 2022-11, with the labels that each got.

#2427 installation.sgmlの15.0対応です
  doc/src/sgml/installation.sgml
Labels: レビュー待ち

#2429 update set_transaction for 15.0
  doc/src/sgml/ref/set_transaction.sgml
Labels: レビュー待ち

#2432 update sql_features for 15.0
  src/backend/catalog/sql_features.txt.ja
Labels: レビュー待ち

#2441 catalogs.sgmlをPostgreSQL 15.0対応するための準備です。
  doc/src/sgml/catalogs.sgml
  doc/src/sgml/catalogs3.sgml
  doc/src/sgml/catalogs4.sgml
  doc/src/sgml/merge-catalogs.sh
  doc/src/sgml/split-catalogs.sh
Labels: レビュー待ち

#2422 config.sgmlのPostgreSQL 15.0対応です。
  doc/src/sgml/config.sgml
  doc/src/sgml/config0.sgml
  doc/src/sgml/config1.sgml
  doc/src/sgml/config2.sgml
  doc/src/sgml/config3.sgml
Labels: 再レビュー待ち

#2431 glossary.sgmlの15.0対応です
  doc/src/sgml/glossary.sgml
Labels: 他にも誰か見て（レビュー済み）

#2433 update alter_collation for 15.0
  doc/src/sgml/ref/alter_collation.sgml
Labels: レビュー待ち

#2434 update set for 15.0
  doc/src/sgml/ref/set.sgml
Labels: レビュー待ち

#2435 update reindex for 15.0
  doc/src/sgml/ref/reindex.sgml
Labels: レビュー待ち

#2439 tableam.sgmlの15.0対応です
  doc/src/sgml/tableam.sgml
Labels: マージ待ち（レビュー済み）

#2446 update syntax for 15.0
  doc/src/sgml/syntax.sgml
Labels: レビュー待ち

#2447 catalogs.sgmlのPostgreSQL1 15.0対応です(パート1)
  doc/src/sgml/catalogs.sgml
  doc/src/sgml/catalogs0.sgml
  doc/src/sgml/catalogs1.sgml
  doc/src/sgml/catalogs2.sgml
  doc/src/sgml/catalogs3.sgml
  doc/src/sgml/merge-catalogs.sh
Labels: マージ待ち（レビュー済み）

#2443 update lock for 15.0
  doc/src/sgml/ref/lock.sgml
Labels: マージ待ち（レビュー済み）

#2430 monitoring.sgmの15.0対応の第1弾です
  doc/src/sgml/monitoring.sgml
Labels: 再レビュー待ち

#2444 update *_transform for 15.0
  doc/src/sgml/ref/create_transform.sgml
  doc/src/sgml/ref/drop_transform.sgml
Labels: 他にも誰か見て（レビュー済み）

#2451 update postgres-ref for 15.0
  doc/src/sgml/ref/postgres-ref.sgml
Labels: マージ待ち（レビュー済み）

#2448 fix 'free space map'
  doc/src/sgml/glossary.sgml
Labels: 他にも誰か見て（レビュー済み）

#2449 plpgsql.sgmlの15.0対応です
  doc/src/sgml/plpgsql.sgml
Labels: 他にも誰か見て（レビュー済み）

#2453 install-windows.sgmlの15.0対応です
  doc/src/sgml/install-windows.sgml
Labels: 他にも誰か見て（レビュー済み）

#2463 add "フリースペースマップ" to NG list
  .ng.list
Labels: レビュー待ち

#2459 update pl_* for 15.0
  doc/src/sgml/plperl.sgml
  doc/src/sgml/pltcl.sgml
Labels: マージ待ち（レビュー済み）

#2460 update pgrowlocks for 15.0
  doc/src/sgml/pgrowlocks.sgml
Labels: マージ待ち（レビュー済み）

#2452 update *_sequence for 15.0
  doc/src/sgml/ref/alter_sequence.sgml
  doc/src/sgml/ref/create_sequence.sgml
Labels: マージ待ち（レビュー済み）

#2461 update for 15.0 - part2
  doc/src/sgml/arch-dev.sgml
  doc/src/sgml/docguide.sgml
  doc/src/sgml/ecpg.sgml
Labels: マージ待ち（レビュー済み）

#2462 update analyze for 15.0
  doc/src/sgml/ref/analyze.sgml
Labels: マージ待ち（レビュー済み）

#2464 update for 15.0 - part3
  doc/src/sgml/ref/explain.sgml
  doc/src/sgml/ref/fetch.sgml
Labels: マージ待ち（レビュー済み）

#2465 update for 15.0 - part4
  doc/src/sgml/ref/checkpoint.sgml
  doc/src/sgml/ref/copy.sgml
  doc/src/sgml/ref/grant.sgml
Labels: 再レビュー待ち

#2466 update for 15.0 - part5
  doc/src/sgml/ref/move.sgml
  doc/src/sgml/ref/pg_checksums.sgml
Labels: マージ待ち（レビュー済み）

#2469 update pg_rewind for 15.0
  doc/src/sgml/ref/pg_rewind.sgml
Labels: マージ待ち（レビュー済み）

#2474 update hstore for 15.0
  doc/src/sgml/hstore.sgml
Labels: マージ待ち（レビュー済み）

#2489 ブーリアン値を論理値に変更
  doc/src/sgml/ddl.sgml
Labels: マージ待ち（レビュー済み）

#2477 bgworker.sgmlの15.0対応です
  doc/src/sgml/bgworker.sgml
Labels: 再レビュー待ち

#2485 acronyms.sgmlのPostgreSQL 15.0対応です。
  doc/src/sgml/acronyms.sgml
Labels: レビュー待ち

#2454 information_schema.sgmlの15.0対応です
  doc/src/sgml/information_schema.sgml
Labels: マージ待ち（レビュー済み）

#2493 Fix typo in pgstatstatements.sgml
  doc/src/sgml/pgstatstatements.sgml
Labels: マージ待ち（レビュー済み）

#2471 uuid-ossp.sgmlの15.0対応です
  doc/src/sgml/uuid-ossp.sgml
Labels: 再レビュー待ち
