Repository pgsql-jp/jpug-doc, pull requests merged in 2022-03, with the labels that each got.

#2166 誤字修正
  doc/src/sgml/amcheck.sgml
  doc/src/sgml/catalogs.sgml
  doc/src/sgml/catalogs2.sgml
  doc/src/sgml/high-availability.sgml
  doc/src/sgml/ref/cluster.sgml
  doc/src/sgml/ref/create_collation.sgml
  doc/src/sgml/ref/psql-ref.sgml
Labels: レビュー待ち

#2167 誤字修正 #2166の13へのバックポート
  doc/src/sgml/catalogs.sgml
  doc/src/sgml/catalogs2.sgml
  doc/src/sgml/high-availability.sgml
  doc/src/sgml/ref/create_collation.sgml
  doc/src/sgml/ref/psql-ref.sgml
Labels: レビュー待ち, version 13

#2171 histogram の訳語を「度数分布」から「ヒストグラム」に変更した。
  doc/src/sgml/catalogs.sgml
  doc/src/sgml/catalogs0.sgml
  doc/src/sgml/catalogs2.sgml
  doc/src/sgml/catalogs4.sgml
  doc/src/sgml/maintenance.sgml
  doc/src/sgml/planstats.sgml
  doc/src/sgml/ref/analyze.sgml
Labels: レビュー待ち

#2172 fix mistranslations
  doc/src/sgml/sources.sgml
Labels: レビュー待ち

#2147 update ref/select for 14.0
  doc/src/sgml/ref/select.sgml
Labels: 再レビュー待ち

#2152 protocol.sgmlのPostgreSQL 14.0対応です。
  doc/src/sgml/protocol.sgml
Labels: 再レビュー待ち

#2159 update json for 14.0
  doc/src/sgml/json.sgml
Labels: マージ待ち（レビュー済み）

#2170 update create/drop_table for 14.0
  doc/src/sgml/ref/create_table.sgml
  doc/src/sgml/ref/drop_table.sgml
Labels: レビュー待ち

#2169 update psql-ref for 14.0
  doc/src/sgml/ref/psql-ref.sgml
Labels: 再レビュー待ち

#2157 runtime.sgmlのPostgreSQL 14.0対応です。
  doc/src/sgml/runtime.sgml
Labels: 再レビュー待ち

#2161 keywords.sgmlのPostgreSQL 14.0対応です。
  doc/src/sgml/keywords.sgml
Labels: 再レビュー待ち
