Repository pgsql-jp/jpug-doc, pull requests merged in 2022-01, with the labels that each got.

#2118 parallel.sgmlのPostgreSQL14.0対応です。
  doc/src/sgml/parallel.sgml
Labels: レビュー待ち

#2119 mvcc.sgmlのPostgreSQL 14.0対応です。
  doc/src/sgml/mvcc.sgml
Labels: レビュー待ち

#2120 xindex.sgmlの14.0対応です
  doc/src/sgml/xindex.sgml
Labels: レビュー待ち

#2123 alter_trigger.sgmlのPostgreSQL14.0対応です。
  doc/src/sgml/ref/alter_trigger.sgml
Labels: レビュー待ち

#2124 マージミスによる重複の削除
  doc/src/sgml/mvcc.sgml
Labels: レビュー待ち

#2125 マージミスによる重複の削除
  doc/src/sgml/ref/pg_basebackup.sgml
Labels: レビュー待ち

#2046 config.sgmlのPostgreSQL 14.0対応です。
  doc/src/sgml/config.sgml
  doc/src/sgml/config0.sgml
  doc/src/sgml/config1.sgml
  doc/src/sgml/config2.sgml
  doc/src/sgml/config3.sgml
  doc/src/sgml/merge-config.sh
Labels: マージ待ち（レビュー済み）

#2073 func.sgmlのPostgreSQL 14.0対応です。
  doc/src/sgml/func.sgml
  doc/src/sgml/func1.sgml
  doc/src/sgml/func2.sgml
  doc/src/sgml/func3.sgml
  doc/src/sgml/func4.sgml
Labels: 再レビュー待ち

#2103 catalogs.sgmlのPostgreSQL 14.0対応です。
  doc/src/sgml/catalogs.sgml
  doc/src/sgml/catalogs0.sgml
  doc/src/sgml/catalogs1.sgml
  doc/src/sgml/catalogs2.sgml
  doc/src/sgml/catalogs3.sgml
  doc/src/sgml/catalogs4.sgml
  doc/src/sgml/merge-catalogs.sh
Labels: マージ待ち（レビュー済み）

#2110 triger.sgmlのPostgreSQL14.0対応です。
  doc/src/sgml/trigger.sgml
Labels: マージ待ち（レビュー済み）

#2116 update ref/reindex for 14.0
  doc/src/sgml/ref/reindex.sgml
Labels: 再レビュー待ち

#2039 「references」を「〜を参照」に変更
  doc/src/sgml/catalogs.sgml
  doc/src/sgml/catalogs0.sgml
  doc/src/sgml/catalogs1.sgml
  doc/src/sgml/catalogs2.sgml
  doc/src/sgml/catalogs3.sgml
  doc/src/sgml/catalogs4.sgml
  doc/src/sgml/pgbuffercache.sgml
  doc/src/sgml/pgstatstatements.sgml
Labels: レビュー待ち, version 13

#2128 references を参照先にする
  doc/src/sgml/catalogs.sgml
  doc/src/sgml/catalogs0.sgml
  doc/src/sgml/catalogs1.sgml
  doc/src/sgml/catalogs2.sgml
  doc/src/sgml/catalogs3.sgml
  doc/src/sgml/catalogs4.sgml
  doc/src/sgml/pgbuffercache.sgml
  doc/src/sgml/pgstatstatements.sgml
Labels: レビュー待ち

#2112 update ref/*_index.sgml for 14.0
  doc/src/sgml/ref/alter_index.sgml
  doc/src/sgml/ref/create_index.sgml
  doc/src/sgml/ref/drop_index.sgml
Labels: 再レビュー待ち

#2121 修正漏れ対応(主に13までの修正漏れ)
  doc/src/sgml/acronyms.sgml
  doc/src/sgml/contrib.sgml
  doc/src/sgml/docguide.sgml
  doc/src/sgml/ecpg.sgml
  doc/src/sgml/event-trigger.sgml
  doc/src/sgml/gist.sgml
  doc/src/sgml/history.sgml
  doc/src/sgml/install-windows.sgml
  doc/src/sgml/installation.sgml
  doc/src/sgml/ref/alter_table.sgml
  doc/src/sgml/ref/copy.sgml
  doc/src/sgml/ref/truncate.sgml
  doc/src/sgml/runtime.sgml
  doc/src/sgml/xfunc.sgml
Labels: レビュー待ち

#2132 修正漏れ
  doc/src/sgml/config.sgml
  doc/src/sgml/func.sgml
  doc/src/sgml/ref/psql-ref.sgml
  doc/src/sgml/ref/select.sgml
Labels: マージ待ち（レビュー済み）

#2130 fix translation of subscriber
  doc/src/sgml/config.sgml
  doc/src/sgml/config1.sgml
  doc/src/sgml/logical-replication.sgml
  doc/src/sgml/ref/create_publication.sgml
  doc/src/sgml/ref/create_subscription.sgml
Labels: レビュー待ち

#2127 update ref/set_transaction for 14.0
  doc/src/sgml/ref/set_transaction.sgml
Labels: 再レビュー待ち

#2131 datetime.sgmlの14.0対応です。
  doc/src/sgml/datetime.sgml
Labels: レビュー待ち

#2137 acronyms.sgmlのPostgreSQL 14.0対応です。
  doc/src/sgml/acronyms.sgml
Labels: 再レビュー待ち

#2129 update vacuumdb for 14.0
  doc/src/sgml/ref/vacuumdb.sgml
Labels: マージ待ち（レビュー済み）

#2134 install-binaries.sgmlのPostgreSQL 14.0対応です。
  doc/src/sgml/install-binaries.sgml
Labels: 再レビュー待ち

#2126 マージミスによる重複その他の修正
  doc/src/sgml/btree.sgml
  doc/src/sgml/gin.sgml
  doc/src/sgml/ref/create_trigger.sgml
  doc/src/sgml/runtime.sgml
Labels: レビュー待ち

#2138 lobj.sgmlのPostgreSQL 14.0対応です。
  doc/src/sgml/lobj.sgml
Labels: マージ待ち（レビュー済み）

#2141 update install-windows for 14.0
  doc/src/sgml/install-windows.sgml
Labels: 再レビュー待ち

#2117 high-availability.sgmlのPostgreSQL 14.0対応です。
  doc/src/sgml/high-availability.sgml
Labels: 再レビュー待ち
