Repository pgsql-jp/jpug-doc, pull requests merged in 2022-05, with the labels that each got.

#2190 Update ddl.sgml
  doc/src/sgml/ddl.sgml
Labels: レビュー待ち

#2189 oldsnapshot.sgmlのPostgreSQL 14.0対応です。
  doc/src/sgml/oldsnapshot.sgml
Labels: レビュー待ち

#2192 Update manage-ag.sgml
  doc/src/sgml/manage-ag.sgml
Labels: レビュー待ち

#2191 Update syntax.sgml
  doc/src/sgml/syntax.sgml
Labels: レビュー待ち

#2194 fix typo in create_trigger of v13
  doc/src/sgml/ref/create_trigger.sgml
Labels: レビュー待ち

#2178 release-14.sgml を翻訳。
  doc/src/sgml/release-14.sgml
Labels: 指摘事項あり

#2179 update create_trigger for 14.0
  doc/src/sgml/ref/create_trigger.sgml
Labels: レビュー待ち

#2181 update wal.sgml for 14.0
  doc/src/sgml/wal.sgml
Labels: 再レビュー待ち

#2180 postgres-fdw.sgmlのPostgreSQL 14.0対応です。
  doc/src/sgml/postgres-fdw.sgml
Labels: 再レビュー待ち

#2199 update gist for 14.0
  doc/src/sgml/gist.sgml
Labels: 再レビュー待ち

#2198 update create_type for 14.0
  doc/src/sgml/ref/create_type.sgml
Labels: 他にも誰か見て（レビュー済み）

#2204 remove extra ws
  doc/src/sgml/wal.sgml
Labels: レビュー待ち

#2205 xfunc.sgmlのPostgreSQL 14.0対応です。
  doc/src/sgml/xfunc.sgml
Labels: 他にも誰か見て（レビュー済み）
