Repository pgsql-jp/jpug-doc, pull requests merged in 2022-06, with the labels that each got.

#2206 update spgist for 14.0
  doc/src/sgml/spgist.sgml
Labels: レビュー待ち

#2214 fix translation of "lossy"
  doc/src/sgml/indexam.sgml
Labels: レビュー待ち

#2209 hash.sgmlのPostgreSQL 14.0対応です。
  doc/src/sgml/hash.sgml
Labels: 他にも誰か見て（レビュー済み）

#2211 update ref/pgbench.sgml for 14.0
  doc/src/sgml/ref/pgbench.sgml
Labels: 他にも誰か見て（レビュー済み）

#2215 identifiesの修正
  doc/src/sgml/information_schema.sgml
Labels: レビュー待ち

#2220 remove extra white spaces
  doc/src/sgml/ref/pgbench.sgml
Labels: レビュー待ち

#2219 indexam.sgmlのPostgreSQL 14.0対応です。
  doc/src/sgml/indexam.sgml
Labels: 再レビュー待ち

#2208 gin.sgmlのPostgreSQL 14.0対応です。
  doc/src/sgml/gin.sgml
Labels: マージ待ち（レビュー済み）

#2217 queries.sgmlの14.0対応です
  doc/src/sgml/queries.sgml
Labels: マージ待ち（レビュー済み）

#2221 ddl.sgmlのPostgreSQL 14.0対応です。
  doc/src/sgml/ddl.sgml
Labels: 再レビュー待ち
