Repository pgsql-jp/jpug-doc, pull requests merged in 2022-08, with the labels that each got.

#2242 libpq.sgml(libpq0パート)のPostgreSQL 14.0対応です。
  doc/src/sgml/libpq.sgml
Labels: 他にも誰か見て（レビュー済み）

#2259 NULは意図的にNULLと区別されている
  doc/src/sgml/datatype.sgml
Labels: レビュー待ち

#2260 定型句を揃えた
  doc/src/sgml/information_schema.sgml
Labels: レビュー待ち

#2249 libpq1の14.0対応です
  doc/src/sgml/libpq.sgml
  doc/src/sgml/libpq1.sgml
Labels: マージ待ち（レビュー済み）

#2263 multirangeを多重範囲に統一
  doc/src/sgml/datatype.sgml
  doc/src/sgml/ref/create_type.sgml
  doc/src/sgml/release-14.sgml
Labels: レビュー待ち

#2261 最新の記述に訳も合わせた
  doc/src/sgml/installation.sgml
Labels: レビュー待ち

#2251 libpq2,3の14.0対応です
  doc/src/sgml/libpq.sgml
  doc/src/sgml/libpq2.sgml
  doc/src/sgml/libpq3.sgml
Labels: 他にも誰か見て（レビュー済み）

#2265 fix typos in config of 14.0
  doc/src/sgml/config.sgml
  doc/src/sgml/config1.sgml
Labels: レビュー待ち

#2266 忘れていた処理（翻訳の変更はありません）
  doc/src/sgml/libpq0.sgml
  doc/src/sgml/libpq2.sgml
  doc/src/sgml/release-13.sgml
Labels: レビュー待ち

#2267 remove extra ws
  doc/src/sgml/ref/alter_table.sgml
Labels: レビュー待ち

#2269 titleも訳した
  doc/src/sgml/release.sgml
Labels: レビュー待ち

#2270 logical-replication.sgmlの修正(ISSUES2173の対応)
  doc/src/sgml/logical-replication.sgml
Labels: レビュー待ち

#2252 fdwhandler.sgmlの14.0対応です。
  doc/src/sgml/fdwhandler.sgml
Labels: 指摘事項あり

#2264 v14の貢献者初版
  doc/src/sgml/jpug-doc.sgml
Labels: レビュー待ち

#2271 fdwhandlerの残りの指摘箇所を対応
  doc/src/sgml/fdwhandler.sgml
Labels: 再レビュー待ち

#2272 fix typos in fdwhandler of 14.0
  doc/src/sgml/fdwhandler.sgml
Labels: レビュー待ち

#2273 タグが翻訳で原文と揃っていない箇所の修正
  doc/src/sgml/datatype.sgml
  doc/src/sgml/ecpg.sgml
  doc/src/sgml/external-projects.sgml
  doc/src/sgml/indexam.sgml
  doc/src/sgml/information_schema.sgml
  doc/src/sgml/queries.sgml
  doc/src/sgml/ref/copy.sgml
  doc/src/sgml/ref/create_database.sgml
  doc/src/sgml/ref/create_materialized_view.sgml
  doc/src/sgml/ref/pg_dump.sgml
  doc/src/sgml/ref/set.sgml
  doc/src/sgml/user-manag.sgml
  doc/src/sgml/xfunc.sgml
  doc/src/sgml/xml2.sgml
  doc/src/sgml/xoper.sgml
Labels: レビュー待ち

#2274 タグ数チェックにより判明した箇所の修正
  doc/src/sgml/array.sgml
  doc/src/sgml/catalogs.sgml
  doc/src/sgml/catalogs1.sgml
  doc/src/sgml/catalogs2.sgml
  doc/src/sgml/citext.sgml
  doc/src/sgml/fuzzystrmatch.sgml
  doc/src/sgml/high-availability.sgml
  doc/src/sgml/history.sgml
  doc/src/sgml/ltree.sgml
  doc/src/sgml/manage-ag.sgml
  doc/src/sgml/monitoring.sgml
  doc/src/sgml/postgres-fdw.sgml
  doc/src/sgml/runtime.sgml
Labels: レビュー待ち

#2282 fix sra oss company name typo.
  doc/src/sgml/jpug-doc.sgml
Labels: レビュー待ち

#2281 typo修正
  doc/src/sgml/xfunc.sgml
Labels: レビュー待ち

#2275 タグ数チェックにより判明した箇所の修正２
  doc/src/sgml/charset.sgml
  doc/src/sgml/config.sgml
  doc/src/sgml/config2.sgml
  doc/src/sgml/config3.sgml
  doc/src/sgml/ddl.sgml
  doc/src/sgml/installation.sgml
  doc/src/sgml/plpgsql.sgml
Labels: レビュー待ち

#2279 タグが翻訳で原文と揃っていない箇所の修正５
  doc/src/sgml/syntax.sgml
  doc/src/sgml/trigger.sgml
Labels: マージ待ち（レビュー済み）

#2284 cosmetics!
  doc/src/sgml/syntax.sgml
Labels: レビュー待ち

#2285 URL修正
  doc/src/sgml/installation.sgml
Labels: レビュー待ち

#2278 タグが翻訳で原文と揃っていない箇所の修正４
  doc/src/sgml/pgprewarm.sgml
  doc/src/sgml/ref/lock.sgml
  doc/src/sgml/ref/psql-ref.sgml
  doc/src/sgml/ref/set_constraints.sgml
  doc/src/sgml/ref/set_role.sgml
  doc/src/sgml/ref/update.sgml
  doc/src/sgml/ref/vacuum.sgml
  doc/src/sgml/textsearch.sgml
Labels: 再レビュー待ち

#2286 は、はの箇所を修正
  doc/src/sgml/charset.sgml
Labels: レビュー待ち

#2288 タグ数チェック関連で発見箇所の修正
  doc/src/sgml/high-availability.sgml
Labels: レビュー待ち

#2287 「パーティション」「パーティショニング」の混在解消(# 2227 の対応)
  doc/src/sgml/ddl.sgml
  doc/src/sgml/postgres-fdw.sgml
  doc/src/sgml/trigger.sgml
Labels: 他にも誰か見て（レビュー済み）

#2276 タグが翻訳で原文と揃っていない箇所の修正３
  doc/src/sgml/func.sgml
  doc/src/sgml/func1.sgml
  doc/src/sgml/func2.sgml
  doc/src/sgml/func3.sgml
  doc/src/sgml/func4.sgml
  doc/src/sgml/json.sgml
  doc/src/sgml/libpq.sgml
  doc/src/sgml/libpq0.sgml
  doc/src/sgml/protocol.sgml
Labels: 再レビュー待ち

#2289 タグ数チェックで発見した箇所の翻訳改善
  doc/src/sgml/gin.sgml
Labels: 他にも誰か見て（レビュー済み）

#2290 fix typos in index for 14.0
  doc/src/sgml/config.sgml
  doc/src/sgml/pgtrgm.sgml
Labels: レビュー待ち

#2294 fix indexterm in btree
  doc/src/sgml/btree.sgml
Labels: レビュー待ち

#2292 fix translation of 'read-only'
  doc/src/sgml/ref/set_transaction.sgml
Labels: マージ待ち（レビュー済み）

#2296 config.sgmlのインデント修正
  doc/src/sgml/config.sgml
  doc/src/sgml/config0.sgml
  doc/src/sgml/config1.sgml
  doc/src/sgml/config2.sgml
  doc/src/sgml/config3.sgml
Labels: 再レビュー待ち

#2295 indextermのミス修正
  doc/src/sgml/array.sgml
  doc/src/sgml/datatype.sgml
  doc/src/sgml/gin.sgml
  doc/src/sgml/gist.sgml
  doc/src/sgml/indices.sgml
  doc/src/sgml/plperl.sgml
  doc/src/sgml/queries.sgml
  doc/src/sgml/ref/declare.sgml
  doc/src/sgml/ref/fetch.sgml
  doc/src/sgml/ref/move.sgml
  doc/src/sgml/rules.sgml
  doc/src/sgml/xfunc.sgml
Labels: マージ待ち（レビュー済み）

#2301 fix missing comment tags
  doc/src/sgml/legal.sgml
  doc/src/sgml/xindex.sgml
Labels: レビュー待ち
