Repository pgsql-jp/jpug-doc, pull requests merged in 2022-04, with the labels that each got.

#2174 extend.sgmlの14.0対応です
  doc/src/sgml/extend.sgml
Labels: 再レビュー待ち

#2175 update create_procedure for 14.0
  doc/src/sgml/ref/create_procedure.sgml
Labels: 他にも誰か見て（レビュー済み）

#2176 update create_function for 14.0
  doc/src/sgml/ref/create_function.sgml
Labels: 他にも誰か見て（レビュー済み）

#2177 Pgstatstatements140
  doc/src/sgml/pgstatstatements.sgml
Labels: 再レビュー待ち

#2182 update perform.sgml for 14.0
  doc/src/sgml/perform.sgml
Labels: レビュー待ち

#2183 logical-replication.sgml の PG14 対応翻訳
  doc/src/sgml/logical-replication.sgml
Labels: レビュー待ち

#2186 remove extra ws
  doc/src/sgml/pgstatstatements.sgml
Labels: レビュー待ち

#2187 Issue #2184 の対応
  doc/src/sgml/textsearch.sgml
Labels: レビュー待ち

#2188 fix translation about extension
  doc/src/sgml/extend.sgml
Labels: レビュー待ち
