Repository pgsql-jp/jpug-doc, pull requests merged in 2022-07, with the labels that each got.

#2216 update ecpg for 14.0
  doc/src/sgml/ecpg.sgml
Labels: 再レビュー待ち

#2222 update plpgsql for 14.0
  doc/src/sgml/plpgsql.sgml
Labels: 再レビュー待ち

#2223 update for monitoring for 14.0
  doc/src/sgml/monitoring.sgml
Labels: 再レビュー待ち

#2231 libpq.sgmlの14.0対応（下訳）です。
  doc/src/sgml/libpq.sgml
  doc/src/sgml/libpq0.sgml
  doc/src/sgml/libpq1.sgml
  doc/src/sgml/libpq2.sgml
  doc/src/sgml/libpq3.sgml
Labels: wontfix

#2235 fix typo in datatype for v13
  doc/src/sgml/datatype.sgml
Labels: レビュー待ち, version 13

#2236 fix typo in datatype for v12
  doc/src/sgml/datatype.sgml
Labels: レビュー待ち

#2239 fix typo in datatype for v10
  doc/src/sgml/datatype.sgml
Labels: レビュー待ち

#2238 fix typo in datatype for v11
  doc/src/sgml/datatype.sgml
Labels: レビュー待ち

#2233 remove extra ws in monitoring
  doc/src/sgml/monitoring.sgml
Labels: レビュー待ち

#2224 update spi for 14.0
  doc/src/sgml/spi.sgml
Labels: 他にも誰か見て（レビュー済み）

#2225 brin.sgmlのPostgreSQL 14.0対応です。
  doc/src/sgml/brin.sgml
Labels: 指摘事項あり

#2240 brin.sgmlの追加修正です。
  doc/src/sgml/brin.sgml
Labels: レビュー待ち

#2201 update btree and charset for v14
  doc/src/sgml/btree.sgml
  doc/src/sgml/charset.sgml
Labels: 再レビュー待ち

#2241 translate table contents in brin - part1
  doc/src/sgml/brin.sgml
Labels: レビュー待ち

#2200 datatype.sgmlのv14対応
  doc/src/sgml/datatype.sgml
Labels: マージは待って（レビュー中）

#2243 以前のバージョン修正漏れを修正
  doc/src/sgml/high-availability.sgml
  doc/src/sgml/runtime.sgml
Labels: レビュー待ち

#2244 remove extra ws in btree of 14.0
  doc/src/sgml/btree.sgml
Labels: レビュー待ち

#2226 rangetypes.sgmlの14.0対応です
  doc/src/sgml/rangetypes.sgml
Labels: 他にも誰か見て（レビュー済み）

#2247 fix typo in query of 14.0
  doc/src/sgml/query.sgml
Labels: レビュー待ち

#2248 fix typo in ddl of 14.0
  doc/src/sgml/ddl.sgml
Labels: レビュー待ち

#2250 fix typo in config of 14.0
  doc/src/sgml/config.sgml
  doc/src/sgml/config1.sgml
Labels: レビュー待ち

#2246 変更修正漏れ
  doc/src/sgml/fdwhandler.sgml
Labels: レビュー待ち

#2245 タグが原文と合ってなかった箇所の修正
  doc/src/sgml/arch-dev.sgml
  doc/src/sgml/backup.sgml
  doc/src/sgml/catalogs.sgml
  doc/src/sgml/catalogs0.sgml
  doc/src/sgml/catalogs2.sgml
  doc/src/sgml/catalogs3.sgml
  doc/src/sgml/config0.sgml
  doc/src/sgml/config1.sgml
  doc/src/sgml/func1.sgml
  doc/src/sgml/func2.sgml
  doc/src/sgml/func4.sgml
  doc/src/sgml/indexam.sgml
  doc/src/sgml/ref/initdb.sgml
Labels: 他にも誰か見て（レビュー済み）

#2253 fix typos in term index for 14.0
  doc/src/sgml/datatype.sgml
  doc/src/sgml/func.sgml
  doc/src/sgml/func4.sgml
  doc/src/sgml/high-availability.sgml
  doc/src/sgml/xfunc.sgml
Labels: レビュー待ち

#2254 14のマージ時に適用されてなかった修正
  doc/src/sgml/gin.sgml
Labels: レビュー待ち

#2255 原文を書き換えていた箇所を修正
  doc/src/sgml/config.sgml
  doc/src/sgml/config1.sgml
Labels: レビュー待ち

#2232 update ref/alter_table for 14.0
  doc/src/sgml/ref/alter_table.sgml
Labels: 再レビュー待ち, 他にも誰か見て（レビュー済み）

#2230 logicaldecoding.sgml の14.0対応です
  doc/src/sgml/logicaldecoding.sgml
Labels: 再レビュー待ち

#2256 マージミスで入れる位置が間違っていた
  doc/src/sgml/monitoring.sgml
Labels: 再レビュー待ち

#2229 pg_amcheck.sgmlのPostgreSQL 14.0対応です。
  doc/src/sgml/ref/pg_amcheck.sgml
Labels: マージ待ち（レビュー済み）

#2257 isolation levelを分離レベルに統一
  doc/src/sgml/config.sgml
  doc/src/sgml/config2.sgml
  doc/src/sgml/config3.sgml
  doc/src/sgml/extend.sgml
  doc/src/sgml/func.sgml
  doc/src/sgml/func4.sgml
  doc/src/sgml/high-availability.sgml
  doc/src/sgml/mvcc.sgml
  doc/src/sgml/plpgsql.sgml
  doc/src/sgml/postgres-fdw.sgml
  doc/src/sgml/ref/begin.sgml
  doc/src/sgml/ref/lock.sgml
  doc/src/sgml/ref/pg_dump.sgml
  doc/src/sgml/ref/select.sgml
  doc/src/sgml/ref/set_transaction.sgml
  doc/src/sgml/ref/start_transaction.sgml
  doc/src/sgml/spi.sgml
Labels: レビュー待ち

#2258 マージ時の重複修正
  doc/src/sgml/extend.sgml
  doc/src/sgml/logical-replication.sgml
  doc/src/sgml/standalone-install.xml
Labels: レビュー待ち
