Repository pgsql-jp/jpug-doc, pull requests merged in 2023-05, with the labels that each got.

#2560 update *_database for 15.0
  doc/src/sgml/ref/alter_database.sgml
  doc/src/sgml/ref/create_database.sgml
  doc/src/sgml/ref/createdb.sgml
Labels: 再レビュー待ち

#2603 update psql-ref for 15.0
  doc/src/sgml/ref/psql-ref.sgml
Labels: マージ待ち（レビュー済み）

#2592 merge.sgmlの15.0対応です
  doc/src/sgml/ref/merge.sgml
Labels: 再レビュー待ち

#2591 pgbench.sgmlの15.0対応です
  doc/src/sgml/ref/pgbench.sgml
Labels: 再レビュー待ち

#2605 オーバ -> オーバー の一括変換
  .ng.list
  doc/src/sgml/brin.sgml
  doc/src/sgml/charset.sgml
  doc/src/sgml/config.sgml
  doc/src/sgml/config0.sgml
  doc/src/sgml/config1.sgml
  doc/src/sgml/config2.sgml
  doc/src/sgml/config3.sgml
  doc/src/sgml/datatype.sgml
  doc/src/sgml/func.sgml
  doc/src/sgml/func4.sgml
  doc/src/sgml/hash.sgml
  doc/src/sgml/high-availability.sgml
  doc/src/sgml/libpq.sgml
  doc/src/sgml/libpq2.sgml
  doc/src/sgml/libpq3.sgml
  doc/src/sgml/monitoring.sgml
  doc/src/sgml/pgstatstatements.sgml
  doc/src/sgml/pgstattuple.sgml
  doc/src/sgml/postgres-fdw.sgml
  doc/src/sgml/replication-origins.sgml
  doc/src/sgml/xtypes.sgml
Labels: レビュー待ち

#2607 トランザクション隔離を見逃していました。
  .ng.list
  doc/src/sgml/ref/pgbench.sgml
Labels: レビュー待ち

#2610 不要な機械翻訳が入っていました
  doc/src/sgml/ref/create_cast.sgml
Labels: レビュー待ち

#2606 ヘッダーファイル -> ヘッダファイルの変更
  .ng.list
  doc/src/sgml/bki.sgml
Labels: レビュー待ち

#2611 xreflabelの翻訳追加
  doc/src/sgml/jit.sgml
  doc/src/sgml/ref/alter_collation.sgml
  doc/src/sgml/ref/alter_table.sgml
  doc/src/sgml/ref/create_aggregate.sgml
  doc/src/sgml/ref/create_index.sgml
  doc/src/sgml/ref/create_subscription.sgml
  doc/src/sgml/ref/create_table.sgml
  doc/src/sgml/ref/create_type.sgml
  doc/src/sgml/ref/declare.sgml
  doc/src/sgml/ref/insert.sgml
  doc/src/sgml/ref/pg_dump.sgml
  doc/src/sgml/ref/postgres-ref.sgml
  doc/src/sgml/ref/psql-ref.sgml
  doc/src/sgml/ref/select.sgml
Labels: 再レビュー待ち

#2612 文章表現を改善しました
  doc/src/sgml/query.sgml
Labels: レビュー待ち

#2614 fix typo in advanced
  doc/src/sgml/advanced.sgml
Labels: レビュー待ち

#2615 田中さんのご指摘修正
  doc/src/sgml/ref/merge.sgml
Labels: レビュー待ち

#2613 第3章の文章表現を見直しました。
  doc/src/sgml/advanced.sgml
Labels: 再レビュー待ち

#2618 typo修正（田中さんのご指摘修正）
  doc/src/sgml/ref/pgbench.sgml
Labels: レビュー待ち

#2619 第4章の文章表現を見直しました。
  doc/src/sgml/syntax.sgml
Labels: レビュー待ち

#2604 PostgreSQL15の貢献者
  doc/src/sgml/jpug-doc.sgml
Labels: レビュー待ち

#2621 貢献者の記載でタグの誤りを修正
  doc/src/sgml/jpug-doc.sgml
Labels: レビュー待ち

#2623 config.sgmlのPostgreSQL 15.3対応です。
  doc/src/sgml/config.sgml
  doc/src/sgml/config0.sgml
  doc/src/sgml/config1.sgml
Labels: レビュー待ち

#2624 plpgsql.sgmlの15.3対応です
  doc/src/sgml/plpgsql.sgml
Labels: レビュー待ち
