Repository pgsql-jp/jpug-doc, pull requests merged in 2023-04, with the labels that each got.

#2581 color.sgmlの15.0対応です
  doc/src/sgml/color.sgml
Labels: レビュー待ち

#2582 regress.sgmlの15.0対応です
  doc/src/sgml/regress.sgml
Labels: レビュー待ち

#2578 update pg_basebackup for 15.0
  doc/src/sgml/ref/pg_basebackup.sgml
Labels: マージ待ち（レビュー済み）

#2579 update *_subscription for 15.0
  doc/src/sgml/ref/alter_subscription.sgml
  doc/src/sgml/ref/create_subscription.sgml
Labels: 再レビュー待ち

#2585 pgwalinspect.sgmlのPostgreSQL 15.0対応です。
  doc/src/sgml/pgwalinspect.sgml
Labels: 他にも誰か見て（レビュー済み）

#2586 logicaldecoding.sgmlの15.0対応です
  doc/src/sgml/logicaldecoding.sgml
Labels: レビュー待ち

#2593 flushをフラッシュにする修正
  doc/src/sgml/wal.sgml
Labels: レビュー待ち

#2595 スーパ→スーパーへ変更
  .ng.list
  doc/src/sgml/amcheck.sgml
  doc/src/sgml/config.sgml
  doc/src/sgml/config0.sgml
  doc/src/sgml/func.sgml
  doc/src/sgml/func1.sgml
  doc/src/sgml/func4.sgml
  doc/src/sgml/runtime.sgml
  doc/src/sgml/system-views.sgml
Labels: 指摘事項あり

#2597 JIT説明の誤記を修正した
  doc/src/sgml/jit.sgml
Labels: マージ待ち（レビュー済み）

#2587 libpq.sgmlの15.0対応です
  doc/src/sgml/libpq.sgml
  doc/src/sgml/libpq0.sgml
  doc/src/sgml/libpq1.sgml
  doc/src/sgml/libpq2.sgml
  doc/src/sgml/libpq3.sgml
Labels: 再レビュー待ち

#2588 Update for release-15
  doc/src/sgml/release-15.sgml
Labels: 再レビュー待ち

#2577 update pgupgrade for 15.0
  doc/src/sgml/ref/pgupgrade.sgml
Labels: 再レビュー待ち

#2589 custom-rmgr.sgmlの15.0対応です
  doc/src/sgml/custom-rmgr.sgml
Labels: 再レビュー待ち

#2590 logical-replication.sgmlの15.0対応です
  doc/src/sgml/logical-replication.sgml
Labels: 再レビュー待ち

#2600 ワーカ→ワーカーの修正
  .ng.list
  doc/src/sgml/archive-modules.sgml
  doc/src/sgml/bgworker.sgml
  doc/src/sgml/btree.sgml
  doc/src/sgml/catalogs.sgml
  doc/src/sgml/catalogs2.sgml
  doc/src/sgml/config.sgml
  doc/src/sgml/config0.sgml
  doc/src/sgml/config2.sgml
  doc/src/sgml/config3.sgml
  doc/src/sgml/func.sgml
  doc/src/sgml/func4.sgml
  doc/src/sgml/glossary.sgml
  doc/src/sgml/indexam.sgml
  doc/src/sgml/maintenance.sgml
  doc/src/sgml/monitoring.sgml
  doc/src/sgml/ref/alter_subscription.sgml
  doc/src/sgml/ref/create_database.sgml
  doc/src/sgml/ref/create_index.sgml
  doc/src/sgml/ref/create_role.sgml
  doc/src/sgml/ref/create_subscription.sgml
  doc/src/sgml/ref/create_table.sgml
  doc/src/sgml/ref/pg_dump.sgml
  doc/src/sgml/ref/pgbench.sgml
  doc/src/sgml/runtime.sgml
  doc/src/sgml/system-views.sgml
  doc/src/sgml/xaggr.sgml
Labels: レビュー待ち

#2594 update select for 15.0
  doc/src/sgml/ref/select.sgml
Labels: マージ待ち（レビュー済み）

#2562 update pg_receivewal for 15.0
  doc/src/sgml/ref/pg_receivewal.sgml
Labels: 指摘事項あり

#2601 以下の観点で文章を見直しました。
  doc/src/sgml/history.sgml
  doc/src/sgml/intro.sgml
  doc/src/sgml/problems.sgml
  doc/src/sgml/start.sgml
Labels: マージ待ち（レビュー済み）
