Repository pgsql-jp/jpug-doc, pull requests merged in 2023-08, with the labels that each got.

#2682 #2681 の対応です。
  doc/src/sgml/release-15.sgml
Labels: レビュー待ち

#2671 monitoring.sgmlの15.3対応です
  doc/src/sgml/monitoring.sgml
Labels: 再レビュー待ち

#2675 func.sgmlの15.3対応です
  doc/src/sgml/func.sgml
  doc/src/sgml/func2.sgml
  doc/src/sgml/func3.sgml
  doc/src/sgml/func4.sgml
Labels: レビュー待ち

#2679 第24章の文章表現を見直しました。
  doc/src/sgml/charset.sgml
Labels: レビュー待ち

#2670 update logical-replication for 15.3
  doc/src/sgml/logical-replication.sgml
Labels: マージ待ち（レビュー済み）

#2684 オプション(--wal-segsize)間違い修正
  doc/src/sgml/wal.sgml
Labels: レビュー待ち

#2688 Issues #2678 の対応をしました
  .ng.list
  doc/src/sgml/backup.sgml
  doc/src/sgml/config.sgml
  doc/src/sgml/config0.sgml
  doc/src/sgml/config1.sgml
  doc/src/sgml/config3.sgml
  doc/src/sgml/func.sgml
  doc/src/sgml/func4.sgml
  doc/src/sgml/high-availability.sgml
  doc/src/sgml/install-windows.sgml
  doc/src/sgml/installation.sgml
  doc/src/sgml/libpq.sgml
  doc/src/sgml/libpq0.sgml
  doc/src/sgml/manage-ag.sgml
  doc/src/sgml/plpgsql.sgml
  doc/src/sgml/pltcl.sgml
  doc/src/sgml/queries.sgml
  doc/src/sgml/ref/pg_basebackup.sgml
  doc/src/sgml/ref/pg_resetwal.sgml
  doc/src/sgml/ref/pgupgrade.sgml
  doc/src/sgml/release-15.sgml
  doc/src/sgml/runtime.sgml
Labels: レビュー待ち

#2686 pg_replication_slots viewの説明修正
  doc/src/sgml/system-views.sgml
Labels: レビュー待ち

#2687 ラッパ->ラッパーの変更
  .ng.list
  doc/src/sgml/catalogs.sgml
  doc/src/sgml/catalogs0.sgml
  doc/src/sgml/catalogs1.sgml
  doc/src/sgml/custom-scan.sgml
  doc/src/sgml/datatype.sgml
  doc/src/sgml/ddl.sgml
  doc/src/sgml/fdwhandler.sgml
  doc/src/sgml/file-fdw.sgml
  doc/src/sgml/func.sgml
  doc/src/sgml/func4.sgml
  doc/src/sgml/glossary.sgml
  doc/src/sgml/information_schema.sgml
  doc/src/sgml/intagg.sgml
  doc/src/sgml/manage-ag.sgml
  doc/src/sgml/parallel.sgml
  doc/src/sgml/postgres-fdw.sgml
  doc/src/sgml/ref/alter_foreign_data_wrapper.sgml
  doc/src/sgml/ref/alter_foreign_table.sgml
  doc/src/sgml/ref/alter_server.sgml
  doc/src/sgml/ref/alter_user_mapping.sgml
  doc/src/sgml/ref/analyze.sgml
  doc/src/sgml/ref/clusterdb.sgml
  doc/src/sgml/ref/create_database.sgml
  doc/src/sgml/ref/create_foreign_data_wrapper.sgml
  doc/src/sgml/ref/create_foreign_table.sgml
  doc/src/sgml/ref/create_server.sgml
  doc/src/sgml/ref/create_user_mapping.sgml
  doc/src/sgml/ref/createdb.sgml
  doc/src/sgml/ref/createuser.sgml
  doc/src/sgml/ref/drop_database.sgml
  doc/src/sgml/ref/drop_foreign_data_wrapper.sgml
  doc/src/sgml/ref/dropdb.sgml
  doc/src/sgml/ref/dropuser.sgml
  doc/src/sgml/ref/grant.sgml
  doc/src/sgml/ref/import_foreign_schema.sgml
  doc/src/sgml/ref/psql-ref.sgml
  doc/src/sgml/ref/reindexdb.sgml
  doc/src/sgml/ref/truncate.sgml
  doc/src/sgml/ref/update.sgml
  doc/src/sgml/ref/vacuumdb.sgml
  doc/src/sgml/release-15.sgml
  doc/src/sgml/rules.sgml
  doc/src/sgml/runtime.sgml
  doc/src/sgml/tablefunc.sgml
  doc/src/sgml/unaccent.sgml
  doc/src/sgml/user-manag.sgml
  doc/src/sgml/xindex.sgml
  doc/src/sgml/xml2.sgml
Labels: レビュー待ち

#2692 queries.sgmlの15.4対応です
  doc/src/sgml/queries.sgml
Labels: レビュー待ち

#2694 func.sgmlのPostgreSQL 15.4対応です。
  doc/src/sgml/func.sgml
  doc/src/sgml/func4.sgml
Labels: レビュー待ち

#2695 update hstory and storage for 15.4
  doc/src/sgml/history.sgml
  doc/src/sgml/storage.sgml
Labels: レビュー待ち

#2697 mvcc.sgmlの15.4対応です
  doc/src/sgml/mvcc.sgml
Labels: レビュー待ち

#2698 pgstatstatements.sgmlでの括弧の修正です。
  doc/src/sgml/pgstatstatements.sgml
Labels: レビュー待ち

#2699 logical-replication.sgmlの15.4対応です
  doc/src/sgml/logical-replication.sgml
Labels: レビュー待ち

#2701 config.sgmlのPostgreSQL 15.4対応です。
  doc/src/sgml/config.sgml
  doc/src/sgml/config0.sgml
  doc/src/sgml/config2.sgml
Labels: レビュー待ち

#2702 update custom_scan for 15.4
  doc/src/sgml/custom-scan.sgml
Labels: レビュー待ち

#2703 update create_stat and drop_subsc for 15.4
  doc/src/sgml/ref/create_statistics.sgml
  doc/src/sgml/ref/drop_subscription.sgml
Labels: レビュー待ち

#2704 update psql-ref for 15.4
  doc/src/sgml/ref/psql-ref.sgml
Labels: レビュー待ち

#2706 update catalogs for 15.4
  doc/src/sgml/catalogs.sgml
  doc/src/sgml/catalogs1.sgml
Labels: レビュー待ち

#2708 regression testの訳を「リグレッションテスト」に統一しました。
  .ng.list
  doc/src/sgml/amcheck.sgml
  doc/src/sgml/config.sgml
  doc/src/sgml/config2.sgml
Labels: 他にも誰か見て（レビュー済み）

#2712 並び替え→並べ替え
  .ng.list
  doc/src/sgml/charset.sgml
  doc/src/sgml/config.sgml
  doc/src/sgml/config0.sgml
  doc/src/sgml/config1.sgml
  doc/src/sgml/config3.sgml
  doc/src/sgml/cube.sgml
  doc/src/sgml/ddl.sgml
  doc/src/sgml/features.sgml
  doc/src/sgml/func.sgml
  doc/src/sgml/func3.sgml
  doc/src/sgml/func4.sgml
  doc/src/sgml/ref/pg_dump.sgml
  doc/src/sgml/ref/pg_restore.sgml
  doc/src/sgml/ref/select.sgml
  doc/src/sgml/syntax.sgml
  doc/src/sgml/textsearch.sgml
Labels: レビュー待ち

#2707 ddl.sgmlの15.4対応です
  doc/src/sgml/ddl.sgml
Labels: 他にも誰か見て（レビュー済み）

#2710 メーカ → メーカー
  .ng.list
  doc/src/sgml/ref/select.sgml
Labels: レビュー待ち

#2714 catalogs.sgmlとsystem-views.sgmlの翻訳漏れとカッコ修正
  doc/src/sgml/catalogs.sgml
  doc/src/sgml/catalogs0.sgml
  doc/src/sgml/system-views.sgml
Labels: レビュー待ち

#2715 訳漏れ対応
  doc/src/sgml/ref/create_function.sgml
Labels: レビュー待ち

#2717 catalogs.sgmlとsystem-views.sgmlの修正
  doc/src/sgml/catalogs.sgml
  doc/src/sgml/system-views.sgml
Labels: レビュー待ち

#2713 Update release-15 for 15.4
  doc/src/sgml/release-15.sgml
Labels: 再レビュー待ち
