Repository pgsql-jp/jpug-doc, pull requests merged in 2023-07, with the labels that each got.

#2655 update createuser for 15.3
  doc/src/sgml/ref/createuser.sgml
Labels: レビュー待ち

#2656 update plperl for 15.3
  doc/src/sgml/plperl.sgml
Labels: レビュー待ち

#2657 第17章の文章表現を見直しました。
  doc/src/sgml/installation.sgml
Labels: レビュー待ち

#2660 第18章の文章表現を見直しました。
  doc/src/sgml/install-windows.sgml
Labels: レビュー待ち

#2654 update create_table for 15.3
  doc/src/sgml/ref/create_table.sgml
Labels: 再レビュー待ち

#2658 arch-dev.sgmlの15.3対応です
  doc/src/sgml/arch-dev.sgml
Labels: 再レビュー待ち

#2627 Update for release-15 (15.3)
  doc/src/sgml/release-15.sgml
Labels: 再レビュー待ち

#2661 libpq.sgmlの15.3対応です
  doc/src/sgml/datatype.sgml
  doc/src/sgml/libpq.sgml
  doc/src/sgml/libpq1.sgml
  doc/src/sgml/libpq3.sgml
Labels: レビュー待ち

#2653 update set_transaction for 15.3
  doc/src/sgml/ref/set_transaction.sgml
Labels: 他にも誰か見て（レビュー済み）

#2662 update security_label for 15.3
  doc/src/sgml/ref/security_label.sgml
Labels: マージ待ち（レビュー済み）

#2666 update merge for 15.3
  doc/src/sgml/ref/merge.sgml
Labels: レビュー待ち

#2668 第23章の文章表現を見直しました。
  doc/src/sgml/manage-ag.sgml
Labels: レビュー待ち

#2665 update alter_table for 15.3
  doc/src/sgml/ref/alter_table.sgml
Labels: レビュー待ち

#2674 原文とのタグ違いを修正
  doc/src/sgml/plperl.sgml
  doc/src/sgml/plpython.sgml
  doc/src/sgml/ref/create_table.sgml
  doc/src/sgml/ref/set_transaction.sgml
Labels: レビュー待ち

#2663 update parallel for 15.3
  doc/src/sgml/parallel.sgml
Labels: 再レビュー待ち

#2664 第21章の文章表現を見直しました。
  doc/src/sgml/client-auth.sgml
Labels: 再レビュー待ち

#2667 update user-manag for 15.3
  doc/src/sgml/user-manag.sgml
Labels: 再レビュー待ち

#2673 ddl.sgmlの15.3対応です
  doc/src/sgml/ddl.sgml
Labels: 他にも誰か見て（レビュー済み）

#2677 越える→超える
  doc/src/sgml/config.sgml
  doc/src/sgml/config0.sgml
  doc/src/sgml/config1.sgml
  doc/src/sgml/datatype.sgml
  doc/src/sgml/rangetypes.sgml
Labels: レビュー待ち
