Repository pgsql-jp/jpug-doc, pull requests merged in 2023-06, with the labels that each got.

#2628 update for 15.3 - part 1
  doc/src/sgml/ref/move.sgml
  doc/src/sgml/ref/pg_amcheck.sgml
  doc/src/sgml/ref/prepare.sgml
Labels: レビュー待ち

#2629 update for 15.3 - part 2
  doc/src/sgml/ref/alter_role.sgml
  doc/src/sgml/ref/create_subscription.sgml
  doc/src/sgml/ref/fetch.sgml
Labels: レビュー待ち

#2630 queries.sgmlの15.3対応です
  doc/src/sgml/queries.sgml
Labels: レビュー待ち

#2632 第6章の文章表現を見直しました。
  doc/src/sgml/dml.sgml
Labels: レビュー待ち

#2633 第10章の文章表現を見直しました。
  doc/src/sgml/typeconv.sgml
Labels: レビュー待ち

#2634 update explain for 15.3
  doc/src/sgml/ref/explain.sgml
Labels: レビュー待ち

#2635 update pltcl for 15.3
  doc/src/sgml/pltcl.sgml
Labels: レビュー待ち

#2636 update ltree for 15.3
  doc/src/sgml/ltree.sgml
Labels: レビュー待ち

#2638 update for 15.3 - part 3
  doc/src/sgml/spi.sgml
  doc/src/sgml/textsearch.sgml
Labels: レビュー待ち

#2639 update plpython for 15.3
  doc/src/sgml/plpython.sgml
Labels: レビュー待ち

#2640 backup.sgmlの15.3対応です
  doc/src/sgml/backup.sgml
Labels: レビュー待ち

#2641 protocol.sgmlの15.3対応です
  doc/src/sgml/protocol.sgml
Labels: レビュー待ち

#2642 system-views.sgmlの15.3対応です
  doc/src/sgml/system-views.sgml
Labels: レビュー待ち

#2643 perform.sgmlの15.3対応です
  doc/src/sgml/perform.sgml
Labels: レビュー待ち

#2644 indices.sgmlの15.3対応です
  doc/src/sgml/indices.sgml
Labels: レビュー待ち

#2645 brin.sgmlの15.3対応です
  doc/src/sgml/brin.sgml
Labels: レビュー待ち

#2637 update create_publication for 15.3
  doc/src/sgml/ref/create_publication.sgml
Labels: 再レビュー待ち

#2646 docguide.sgmlの15.3対応です
  doc/src/sgml/docguide.sgml
Labels: レビュー待ち

#2648 Updated github-script
  .github/workflows/pr-label.yml
Labels: レビュー待ち

#2647 update create_role for 15.3
  doc/src/sgml/ref/create_role.sgml
Labels: 再レビュー待ち

#2649 sources.sgmlの15.3対応です
  doc/src/sgml/sources.sgml
Labels: レビュー待ち

#2651 第13章の文章表現を見直しました。
  doc/src/sgml/mvcc.sgml
Labels: レビュー待ち

#2652 update comment for 15.3
  doc/src/sgml/ref/comment.sgml
Labels: レビュー待ち

#2626 xfunc.sgmlの15.3対応です
  doc/src/sgml/xfunc.sgml
Labels: 指摘事項あり
