Repository pgsql-jp/jpug-doc, pull requests merged in 2023-02, with the labels that each got.

#2538 15.0からのバックポート
  doc/src/sgml/amcheck.sgml
  doc/src/sgml/arch-dev.sgml
  doc/src/sgml/brin.sgml
  doc/src/sgml/charset.sgml
  doc/src/sgml/client-auth.sgml
  doc/src/sgml/config.sgml
  doc/src/sgml/config0.sgml
  doc/src/sgml/config1.sgml
  doc/src/sgml/config2.sgml
  doc/src/sgml/ddl.sgml
  doc/src/sgml/fdwhandler.sgml
  doc/src/sgml/func.sgml
  doc/src/sgml/func1.sgml
  doc/src/sgml/func4.sgml
  doc/src/sgml/gist.sgml
  doc/src/sgml/glossary.sgml
  doc/src/sgml/history.sgml
  doc/src/sgml/installation.sgml
  doc/src/sgml/json.sgml
  doc/src/sgml/legal.sgml
  doc/src/sgml/maintenance.sgml
  doc/src/sgml/monitoring.sgml
  doc/src/sgml/parallel.sgml
  doc/src/sgml/perform.sgml
  doc/src/sgml/pgstatstatements.sgml
  doc/src/sgml/plpgsql.sgml
  doc/src/sgml/ref/alter_tablespace.sgml
  doc/src/sgml/ref/create_foreign_table.sgml
  doc/src/sgml/ref/create_tablespace.sgml
  doc/src/sgml/ref/explain.sgml
  doc/src/sgml/ref/fetch.sgml
  doc/src/sgml/ref/insert.sgml
  doc/src/sgml/ref/pg_ctl-ref.sgml
  doc/src/sgml/ref/pg_waldump.sgml
  doc/src/sgml/ref/pgtesttiming.sgml
  doc/src/sgml/ref/prepare.sgml
  doc/src/sgml/ref/set.sgml
  doc/src/sgml/ref/update.sgml
  doc/src/sgml/rules.sgml
  doc/src/sgml/sources.sgml
  doc/src/sgml/spgist.sgml
  doc/src/sgml/spi.sgml
  doc/src/sgml/storage.sgml
  doc/src/sgml/syntax.sgml
  doc/src/sgml/tablesample-method.sgml
  doc/src/sgml/trigger.sgml
  doc/src/sgml/typeconv.sgml
  doc/src/sgml/xfunc.sgml
Labels: レビュー待ち, version 14

#2541 bki.sgmlのPostgreSQL 15.0対応です。
  doc/src/sgml/bki.sgml
Labels: マージ待ち（レビュー済み）

#2544 update *_trigger for 15.0
  doc/src/sgml/ref/alter_trigger.sgml
  doc/src/sgml/ref/create_trigger.sgml
Labels: マージ待ち（レビュー済み）

#2546 update for 15.0 - part 7
  doc/src/sgml/ref/pg_ctl-ref.sgml
  doc/src/sgml/ref/pg_restore.sgml
Labels: レビュー待ち

#2547 update trigger for 15.0
  doc/src/sgml/trigger.sgml
Labels: レビュー待ち

#2548 update user-manag for 15.0
  doc/src/sgml/user-manag.sgml
Labels: レビュー待ち

#2537 イベントトリガ関数のSub-object IDを翻訳
  doc/src/sgml/func.sgml
Labels: レビュー待ち

#2549 pgstatstatements.sgmlの15.0対応です
  doc/src/sgml/pgstatstatements.sgml
Labels: レビュー待ち

#2557 「メークファイル」を"makefile"に変更します。
  doc/src/sgml/extend.sgml
Labels: レビュー待ち

#2543 charset.sgmlのPostgreSQL 15.0対応です。
  doc/src/sgml/charset.sgml
Labels: 再レビュー待ち

#2550 update for 15.0 - part 8
  doc/src/sgml/pgbuffercache.sgml
  doc/src/sgml/pgfreespacemap.sgml
  doc/src/sgml/pgvisibility.sgml
Labels: レビュー待ち

#2551 update pg_amcheck for 15.0
  doc/src/sgml/ref/pg_amcheck.sgml
Labels: レビュー待ち

#2552 update for 15.0 - part 9
  doc/src/sgml/ltree.sgml
  doc/src/sgml/manage-ag.sgml
Labels: レビュー待ち

#2545 rules.sgmlの15.0対応です
  doc/src/sgml/rules.sgml
Labels: マージ待ち（レビュー済み）

#2558 generic-wal.sgmlの15.0対応です
  doc/src/sgml/generic-wal.sgml
Labels: マージ待ち（レビュー済み）

#2559 update lo for 15.0
  doc/src/sgml/lo.sgml
Labels: レビュー待ち

#2561 update pgcrypto for 15.0
  doc/src/sgml/pgcrypto.sgml
Labels: レビュー待ち

#2554 update custom-scan for 15.0
  doc/src/sgml/custom-scan.sgml
Labels: マージ待ち（レビュー済み）

#2563 pageinspect.sgmlの15.0対応です。
  doc/src/sgml/pageinspect.sgml
Labels: レビュー待ち

#2564 typo修正
  doc/src/sgml/ref/alter_trigger.sgml
Labels: レビュー待ち
