Repository pgsql-jp/jpug-doc, pull requests merged in 2023-03, with the labels that each got.

#2555 update earthdistance for 15.0
  doc/src/sgml/earthdistance.sgml
Labels: 再レビュー待ち

#2570 catalogs.sgmlの修正
  doc/src/sgml/catalogs.sgml
  doc/src/sgml/catalogs1.sgml
  doc/src/sgml/catalogs2.sgml
Labels: レビュー待ち

#2566 update *_table* for 15.0
  doc/src/sgml/ref/alter_table.sgml
  doc/src/sgml/ref/create_table.sgml
  doc/src/sgml/ref/create_table_as.sgml
Labels: マージ待ち（レビュー済み）

#2565 postgres-fdw.sgmlのPostgreSQL 15.0対応です。
  doc/src/sgml/postgres-fdw.sgml
Labels: 再レビュー待ち

#2567 update *_view for 15.0
  doc/src/sgml/ref/alter_view.sgml
  doc/src/sgml/ref/create_view.sgml
Labels: レビュー待ち

#2568 fix oversight in rule.sgml
  doc/src/sgml/rules.sgml
Labels: レビュー待ち

#2571 update cluster for 15.0
  doc/src/sgml/ref/cluster.sgml
Labels: マージ待ち（レビュー済み）

#2572 update plpython for 15.0
  doc/src/sgml/plpython.sgml
Labels: レビュー待ち

#2584 セクションへのリンクが日本語表示になるよう修正
  doc/src/sgml/ref/reindex.sgml
Labels: レビュー待ち

#2569 protocol.sgmlの15.0対応です
  doc/src/sgml/protocol.sgml
Labels: 再レビュー待ち

#2573 ddl.sgmlのPostgreSQL 15.0対応です。
  doc/src/sgml/ddl.sgml
Labels: 再レビュー待ち

#2575 update initdb for 15.0
  doc/src/sgml/ref/initdb.sgml
Labels: マージ待ち（レビュー済み）

#2583 flushの訳をフラッシュに修正
  doc/src/sgml/config.sgml
  doc/src/sgml/config0.sgml
  doc/src/sgml/config1.sgml
  doc/src/sgml/config3.sgml
  doc/src/sgml/glossary.sgml
  doc/src/sgml/high-availability.sgml
  doc/src/sgml/monitoring.sgml
  doc/src/sgml/perform.sgml
  doc/src/sgml/plperl.sgml
  doc/src/sgml/protocol.sgml
  doc/src/sgml/runtime.sgml
  doc/src/sgml/wal.sgml
Labels: 再レビュー待ち

#2576 update *_publication for 15.0
  doc/src/sgml/ref/alter_publication.sgml
  doc/src/sgml/ref/create_publication.sgml
Labels: マージ待ち（レビュー済み）
