Repository pgsql-jp/jpug-doc, pull requests merged in 2024-05, with the labels that each got.

#2884 doc_ja_16_0 の内容をdoc_ja_16_2に反映
  .ng.list
  doc/src/sgml/Makefile
  doc/src/sgml/catalogs2.sgml
  doc/src/sgml/client-auth.sgml
  doc/src/sgml/datatype.sgml
  doc/src/sgml/func.sgml
  doc/src/sgml/func1.sgml
  doc/src/sgml/func2.sgml
  doc/src/sgml/func3.sgml
  doc/src/sgml/func4.sgml
  doc/src/sgml/pgbuffercache.sgml
  doc/src/sgml/pgwalinspect.sgml
  doc/src/sgml/plpgsql.sgml
  doc/src/sgml/pltcl.sgml
  doc/src/sgml/postgres-fdw.sgml
  doc/src/sgml/ref/create_index.sgml
  doc/src/sgml/ref/create_procedure.sgml
  doc/src/sgml/ref/create_subscription.sgml
  doc/src/sgml/ref/create_table.sgml
  doc/src/sgml/ref/create_transform.sgml
  doc/src/sgml/ref/declare.sgml
  doc/src/sgml/ref/pgbench.sgml
  doc/src/sgml/ref/postgres-ref.sgml
  doc/src/sgml/ref/psql-ref.sgml
  doc/src/sgml/ref/select.sgml
  doc/src/sgml/regress.sgml
  doc/src/sgml/spgist.sgml
  doc/src/sgml/storage.sgml
  doc/src/sgml/system-views.sgml
  doc/src/sgml/user-manag.sgml
  doc/src/sgml/xact.sgml
Labels: レビュー待ち, version 16.2

#2885 以前のマージの問題を修正
  doc/src/sgml/config.sgml
  doc/src/sgml/config1.sgml
  doc/src/sgml/datatype.sgml
  doc/src/sgml/fdwhandler.sgml
  doc/src/sgml/limits.sgml
Labels: レビュー待ち, version 16.2

#2868 installation.sgmlの16.0対応です
  doc/src/sgml/installation.sgml
Labels: 再レビュー待ち

#2883 localization: ローカライゼーションに統一
  doc/src/sgml/charset.sgml
  doc/src/sgml/errcodes.sgml
  doc/src/sgml/func.sgml
  doc/src/sgml/func2.sgml
  doc/src/sgml/installation.sgml
  doc/src/sgml/libpq.sgml
  doc/src/sgml/libpq1.sgml
  doc/src/sgml/libpq2.sgml
  doc/src/sgml/nls.sgml
  doc/src/sgml/protocol.sgml
  doc/src/sgml/release-16.sgml
  doc/src/sgml/sources.sgml
Labels: 他にも誰か見て（レビュー済み）

#2872 charset.sgmlの16.0対応です
  doc/src/sgml/charset.sgml
Labels: 他にも誰か見て（レビュー済み）

#2886 漢字違いもNG語に追加
  .ng.list
Labels: レビュー待ち

#2870 update libpq for 16.0
  doc/src/sgml/libpq.sgml
  doc/src/sgml/libpq0.sgml
  doc/src/sgml/libpq1.sgml
  doc/src/sgml/libpq2.sgml
  doc/src/sgml/protocol.sgml
Labels: 再レビュー待ち

#2888 titleのインデントを修正
  doc/src/sgml/datetime.sgml
  doc/src/sgml/ddl.sgml
  doc/src/sgml/diskusage.sgml
  doc/src/sgml/errcodes.sgml
  doc/src/sgml/func.sgml
  doc/src/sgml/func4.sgml
  doc/src/sgml/install-windows.sgml
  doc/src/sgml/installation.sgml
  doc/src/sgml/libpq.sgml
  doc/src/sgml/libpq1.sgml
  doc/src/sgml/libpq2.sgml
  doc/src/sgml/lobj.sgml
  doc/src/sgml/logical-replication.sgml
  doc/src/sgml/maintenance.sgml
  doc/src/sgml/perform.sgml
  doc/src/sgml/planstats.sgml
  doc/src/sgml/plperl.sgml
  doc/src/sgml/protocol.sgml
  doc/src/sgml/ref/alter_user.sgml
  doc/src/sgml/ref/clusterdb.sgml
  doc/src/sgml/ref/copy.sgml
  doc/src/sgml/ref/create_cast.sgml
  doc/src/sgml/ref/create_conversion.sgml
  doc/src/sgml/ref/create_database.sgml
  doc/src/sgml/ref/create_domain.sgml
  doc/src/sgml/ref/create_language.sgml
  doc/src/sgml/ref/create_schema.sgml
  doc/src/sgml/ref/create_table_as.sgml
  doc/src/sgml/ref/create_type.sgml
  doc/src/sgml/ref/createdb.sgml
  doc/src/sgml/ref/createuser.sgml
  doc/src/sgml/ref/do.sgml
  doc/src/sgml/ref/drop_cast.sgml
  doc/src/sgml/ref/drop_conversion.sgml
  doc/src/sgml/ref/drop_trigger.sgml
  doc/src/sgml/ref/drop_type.sgml
  doc/src/sgml/ref/drop_user.sgml
  doc/src/sgml/ref/dropdb.sgml
  doc/src/sgml/ref/dropuser.sgml
  doc/src/sgml/ref/ecpg-ref.sgml
  doc/src/sgml/ref/grant.sgml
  doc/src/sgml/ref/initdb.sgml
  doc/src/sgml/ref/pg_config-ref.sgml
  doc/src/sgml/ref/pg_controldata.sgml
  doc/src/sgml/ref/pg_dumpall.sgml
  doc/src/sgml/ref/pg_resetwal.sgml
  doc/src/sgml/ref/pg_restore.sgml
  doc/src/sgml/ref/postgres-ref.sgml
  doc/src/sgml/ref/set.sgml
  doc/src/sgml/ref/set_constraints.sgml
  doc/src/sgml/sources.sgml
  doc/src/sgml/trigger.sgml
  doc/src/sgml/user-manag.sgml
  doc/src/sgml/wal.sgml
  doc/src/sgml/xfunc.sgml
  doc/src/sgml/xplang.sgml
Labels: レビュー待ち

#2889 commaの訳語を「カンマ」に統一
  doc/src/sgml/acronyms.sgml
  doc/src/sgml/client-auth.sgml
  doc/src/sgml/config.sgml
  doc/src/sgml/config0.sgml
  doc/src/sgml/config2.sgml
  doc/src/sgml/func.sgml
  doc/src/sgml/func2.sgml
  doc/src/sgml/ref/psql-ref.sgml
Labels: レビュー待ち

#2887 titleとCDATAのコメント化の修正
  doc/src/sgml/docguide.sgml
  doc/src/sgml/extend.sgml
  doc/src/sgml/glossary.sgml
  doc/src/sgml/plpgsql.sgml
  doc/src/sgml/ref/create_table.sgml
  doc/src/sgml/ref/declare.sgml
  doc/src/sgml/ref/pg_dump.sgml
  doc/src/sgml/release-16.sgml
  doc/src/sgml/xindex.sgml
Labels: レビュー待ち

#2891 カンマに統一の修正で最修正
  src/backend/catalog/sql_features.txt.ja
Labels: レビュー待ち

#2892 copartitionの訳見直し
  src/backend/catalog/sql_features.txt.ja
  src/backend/utils/errcodes.txt.ja
Labels: レビュー待ち

#2895 fix typo in installation
  doc/src/sgml/installation.sgml
Labels: レビュー待ち

#2896 fix typo in ecpg
  doc/src/sgml/ecpg.sgml
Labels: レビュー待ち

#2894 fix "firewall"
  doc/src/sgml/runtime.sgml
Labels: レビュー待ち

#2897 typo修正&スキップへの変更&全角カッコに変更
  doc/src/sgml/ref/reindex.sgml
Labels: レビュー待ち

#2871 update logical-replication for 16.0
  doc/src/sgml/logical-replication.sgml
Labels: 再レビュー待ち

#2879 monitoring.sgmlのPostgreSQL 16.0対応です。
  doc/src/sgml/monitoring.sgml
Labels: 指摘事項あり

#2904 Doc ja 16 3
  doc/src/sgml/ecpg.sgml
  doc/src/sgml/installation.sgml
  doc/src/sgml/logical-replication.sgml
  doc/src/sgml/logicaldecoding.sgml
  doc/src/sgml/monitoring.sgml
  doc/src/sgml/plpgsql.sgml
  doc/src/sgml/ref/reindex.sgml
  doc/src/sgml/runtime.sgml
Labels: version 16.3

#2903 high-availability.sgmlで訳抜けの文を修正
  doc/src/sgml/high-availability.sgml
Labels: レビュー待ち

#2902 This parameter can only be set at server〜の訳統一
  doc/src/sgml/config.sgml
  doc/src/sgml/config0.sgml
  doc/src/sgml/config1.sgml
  doc/src/sgml/config2.sgml
  doc/src/sgml/config3.sgml
Labels: レビュー待ち

#2905 v16の貢献者を更新
  doc/src/sgml/jpug-doc.sgml
Labels: レビュー待ち

#2906 翻訳対象漏れと原文に戻す修正
  doc/src/sgml/monitoring.sgml
Labels: レビュー待ち, version 16.0リリース

#2911 update for 16.3 - part 2
  doc/src/sgml/ref/analyze.sgml
  doc/src/sgml/ref/copy.sgml
  doc/src/sgml/ref/create_collation.sgml
  doc/src/sgml/ref/ecpg-ref.sgml
  doc/src/sgml/ref/initdb.sgml
Labels: レビュー待ち

#2915 update pg_basebackup for 16.3
  doc/src/sgml/ref/pg_basebackup.sgml
Labels: レビュー待ち

#2916 Doc ja master
  contrib/postgres_fdw/expected/postgres_fdw.out
  contrib/postgres_fdw/sql/postgres_fdw.sql
  doc/src/sgml/config0.sgml
  doc/src/sgml/libpq0.sgml
  doc/src/sgml/perform.sgml
  doc/src/sgml/ref/drop_database.sgml
  doc/src/sgml/release-17.sgml
  doc/src/sgml/sources.sgml
  src/backend/optimizer/path/allpaths.c
  src/backend/optimizer/path/equivclass.c
  src/backend/optimizer/path/pathkeys.c
  src/backend/optimizer/plan/planner.c
  src/backend/optimizer/plan/subselect.c
  src/backend/optimizer/prep/prepunion.c
  src/backend/parser/analyze.c
  src/backend/po/de.po
  src/backend/po/ka.po
  src/bin/initdb/po/ka.po
  src/bin/pg_basebackup/po/de.po
  src/bin/pg_basebackup/po/ka.po
  src/bin/pg_combinebackup/po/LINGUAS
  src/bin/pg_combinebackup/po/de.po
  src/bin/pg_combinebackup/po/ka.po
  src/bin/pg_controldata/po/de.po
  src/bin/pg_controldata/po/ka.po
  src/bin/pg_dump/po/ka.po
  src/bin/pg_rewind/po/ka.po
  src/bin/pg_test_fsync/po/ka.po
  src/bin/pg_upgrade/po/ka.po
  src/bin/pg_verifybackup/po/de.po
  src/bin/pg_verifybackup/po/ka.po
  src/bin/pg_walsummary/po/de.po
  src/bin/psql/po/de.po
  src/bin/psql/po/ka.po
  src/include/nodes/pathnodes.h
  src/include/optimizer/paths.h
  src/include/optimizer/planner.h
  src/include/optimizer/prep.h
  src/interfaces/libpq/po/ka.po
  src/test/regress/expected/collate.icu.utf8.out
  src/test/regress/expected/incremental_sort.out
  src/test/regress/expected/union.out
  src/test/regress/sql/collate.icu.utf8.sql
  src/test/regress/sql/union.sql
Labels: doc_ja_master

#2923 Doc ja master
  configure
  configure.ac
  contrib/postgres_fdw/expected/postgres_fdw.out
  contrib/postgres_fdw/sql/postgres_fdw.sql
  doc/src/sgml/config.sgml
  doc/src/sgml/config0.sgml
  doc/src/sgml/config1.sgml
  doc/src/sgml/gist.sgml
  doc/src/sgml/logical-replication.sgml
  doc/src/sgml/plpgsql.sgml
  doc/src/sgml/ref/alter_table.sgml
  doc/src/sgml/ref/analyze.sgml
  doc/src/sgml/ref/create_collation.sgml
  doc/src/sgml/ref/create_table.sgml
  doc/src/sgml/ref/ecpg-ref.sgml
  doc/src/sgml/ref/initdb.sgml
  doc/src/sgml/ref/pg_basebackup.sgml
  doc/src/sgml/ref/pg_receivewal.sgml
  doc/src/sgml/ref/psql-ref.sgml
  doc/src/sgml/release-17.sgml
  doc/src/sgml/xindex.sgml
  meson.build
  src/backend/optimizer/path/allpaths.c
  src/backend/optimizer/path/equivclass.c
  src/backend/optimizer/path/pathkeys.c
  src/backend/optimizer/plan/planner.c
  src/backend/optimizer/plan/subselect.c
  src/backend/optimizer/prep/prepunion.c
  src/backend/parser/analyze.c
  src/include/nodes/pathnodes.h
  src/include/optimizer/paths.h
  src/include/optimizer/planner.h
  src/include/optimizer/prep.h
  src/test/regress/expected/collate.icu.utf8.out
  src/test/regress/expected/incremental_sort.out
  src/test/regress/expected/union.out
  src/test/regress/sql/collate.icu.utf8.sql
  src/test/regress/sql/union.sql
Labels: doc_ja_master

#2909 update for 16.3 - part 1
  doc/src/sgml/ref/create_domain.sgml
  doc/src/sgml/ref/pg_rewind.sgml
  doc/src/sgml/ref/psql-ref.sgml
  doc/src/sgml/ref/select.sgml
  doc/src/sgml/ref/set_role.sgml
  doc/src/sgml/ref/vacuum.sgml
Labels: 再レビュー待ち

#2914 update for 16.3 - part 3
  doc/src/sgml/logical-replication.sgml
  doc/src/sgml/nls.sgml
  doc/src/sgml/postgres-fdw.sgml
  doc/src/sgml/uuid-ossp.sgml
  doc/src/sgml/wal.sgml
Labels: 再レビュー待ち

#2917 update pgupgrade for 16.3
  doc/src/sgml/ref/pgupgrade.sgml
Labels: レビュー待ち

#2919 update syntax for 16.3
  doc/src/sgml/syntax.sgml
Labels: レビュー待ち

#2920 update fdwhandler for 16.3
  doc/src/sgml/fdwhandler.sgml
Labels: レビュー待ち

#2918 update for 16.3 - part 4
  doc/src/sgml/ref/pg_dump.sgml
  doc/src/sgml/ref/pg_dumpall.sgml
Labels: 指摘事項あり

#2921 plpgsql.sgmlの16.3対応です
  doc/src/sgml/plpgsql.sgml
Labels: レビュー待ち
