Repository pgsql-jp/jpug-doc, pull requests merged in 2024-01, with the labels that each got.

#2790 update *_collation for 16.0
  doc/src/sgml/ref/alter_collation.sgml
  doc/src/sgml/ref/create_collation.sgml
Labels: 再レビュー待ち, レビュー待ち

#2801 docguide.sgmlの16.0対応です
  doc/src/sgml/docguide.sgml
Labels: 再レビュー待ち, レビュー待ち

#2797 update wal for 16.0
  doc/src/sgml/wal.sgml
Labels: レビュー待ち

#2798 update for 16.0 - new part14
  doc/src/sgml/ref/alter_role.sgml
  doc/src/sgml/ref/create_role.sgml
  doc/src/sgml/ref/createuser.sgml
  doc/src/sgml/ref/drop_role.sgml
  doc/src/sgml/ref/dropuser.sgml
Labels: レビュー待ち

#2799 update set_role for 16.0
  doc/src/sgml/ref/set_role.sgml
Labels: レビュー待ち

#2803 update runtime for 16.0
  doc/src/sgml/runtime.sgml
Labels: レビュー待ち

#2804 update pageinspect for 16.0
  doc/src/sgml/pageinspect.sgml
Labels: レビュー待ち

#2795 update nls for 16.0
  doc/src/sgml/nls.sgml
Labels: 再レビュー待ち, レビュー待ち

#2800 update syntax for 16.0
  doc/src/sgml/syntax.sgml
Labels: 指摘事項あり

#2806 update copy for 16.0
  doc/src/sgml/ref/copy.sgml
Labels: レビュー待ち

#2807 protocol.sgmlの16.0対応です
  doc/src/sgml/protocol.sgml
Labels: レビュー待ち

#2808 update explain for 16.0
  doc/src/sgml/ref/explain.sgml
Labels: レビュー待ち

#2809 fuzzystrmatch.sgmlの16.0対応です
  doc/src/sgml/fuzzystrmatch.sgml
Labels: レビュー待ち

#2812 issues 2802の対応
  doc/src/sgml/config.sgml
  doc/src/sgml/config2.sgml
Labels: レビュー待ち
