Repository pgsql-jp/jpug-doc, pull requests merged in 2024-10, with the labels that each got.

#3091 update for 17.0 - part 1
  doc/src/sgml/ref/lock.sgml
  doc/src/sgml/ref/pg_recvlogical.sgml
  doc/src/sgml/ref/set_session_auth.sgml
Labels: マージ待ち（レビュー済み）

#3094 intro.sgmlの17.0対応です。
  doc/src/sgml/intro.sgml
Labels: レビュー待ち

#3096 Translate drop_subscription.sgml for PG17
  doc/src/sgml/ref/drop_subscription.sgml
Labels: レビュー待ち

#3097 Translate alter_subscription.sgml for PG17
  doc/src/sgml/ref/alter_subscription.sgml
Labels: 他にも誰か見て（レビュー済み）

#3106 サブスクライバーに統一
  .ng.list
  doc/src/sgml/logical-replication.sgml
  doc/src/sgml/monitoring.sgml
  doc/src/sgml/ref/alter_subscription.sgml
  doc/src/sgml/release-16.sgml
Labels: レビュー待ち, version 16

#3098 Translate alter_publication for PG17
  doc/src/sgml/ref/alter_publication.sgml
Labels: 他にも誰か見て（レビュー済み）

#3099 update for 17.0 - part 2
  src/backend/catalog/sql_features.txt.ja
  src/backend/utils/errcodes.txt.ja
Labels: マージ待ち（レビュー済み）

#3101 Translate ecpg.sgml for PG17
  doc/src/sgml/ecpg.sgml
Labels: 他にも誰か見て（レビュー済み）

#3102 Translate bgworker.sgml
  doc/src/sgml/bgworker.sgml
Labels: 再レビュー待ち

#3108 index関連の17.0対応です
  doc/src/sgml/brin.sgml
  doc/src/sgml/btree.sgml
  doc/src/sgml/indextypes.sgml
Labels: レビュー待ち

#3111 update for 17.0 - part 3
  doc/src/sgml/tableam.sgml
  doc/src/sgml/xact.sgml
Labels: マージ待ち（レビュー済み）

#3121 長音を省く統一（４）
  .ng.list
  doc/src/sgml/ref/initdb.sgml
Labels: レビュー待ち, version 16

#3103 Translate logicaldecoding.sgml
  doc/src/sgml/logicaldecoding.sgml
Labels: 再レビュー待ち

#3112 update for 17.0 - part 4
  doc/src/sgml/ref/pg_verifybackup.sgml
  doc/src/sgml/ref/pg_waldump.sgml
Labels: マージ待ち（レビュー済み）

#3122 checkpoint,checkpointerの訳を修正
  doc/src/sgml/high-availability.sgml
  doc/src/sgml/monitoring.sgml
Labels: レビュー待ち, version 16

#3124 sql_features.txt.jaもチェック対象に追加
  doc/src/sgml/Makefile
  src/backend/catalog/sql_features.txt.ja
Labels: レビュー待ち, version 16

#3125 段落の文の共通化（４）
  doc/src/sgml/config.sgml
  doc/src/sgml/config0.sgml
  doc/src/sgml/config1.sgml
  doc/src/sgml/config2.sgml
  doc/src/sgml/config3.sgml
  doc/src/sgml/pgstatstatements.sgml
  doc/src/sgml/plperl.sgml
  doc/src/sgml/sepgsql.sgml
Labels: レビュー待ち, version 16

#3095 Translate create_subscription.sgml for PG17
  doc/src/sgml/ref/create_subscription.sgml
Labels: 再レビュー待ち

#3126 update datetime for 17.0
  doc/src/sgml/datetime.sgml
Labels: レビュー待ち

#3114 update for 17.0 - part 6
  doc/src/sgml/oid2name.sgml
  doc/src/sgml/pgrowlocks.sgml
  doc/src/sgml/rowtypes.sgml
Labels: マージ待ち（レビュー済み）

#3105 config.sgmlのPostgreSQL 17.0対応です。
  doc/src/sgml/config.sgml
  doc/src/sgml/config0.sgml
  doc/src/sgml/config1.sgml
  doc/src/sgml/config2.sgml
  doc/src/sgml/config3.sgml
Labels: 再レビュー待ち

#3127 update create_event_trigger for 17.0
  doc/src/sgml/ref/create_event_trigger.sgml
Labels: レビュー待ち

#3110 pg_createsubscriber.sgmlのPostgreSQL 17.0対応です。
  doc/src/sgml/ref/pg_createsubscriber.sgml
Labels: 再レビュー待ち

#3115 update sepgsql for 17.0
  doc/src/sgml/sepgsql.sgml
Labels: 再レビュー待ち

#3142 「。」の漏れを修正
  doc/src/sgml/ecpg.sgml
  doc/src/sgml/indexam.sgml
  doc/src/sgml/information_schema.sgml
  doc/src/sgml/planstats.sgml
  doc/src/sgml/plpgsql.sgml
  doc/src/sgml/plpython.sgml
  doc/src/sgml/query.sgml
  doc/src/sgml/ref/alter_extension.sgml
  doc/src/sgml/ref/alter_table.sgml
  doc/src/sgml/ref/create_cast.sgml
  doc/src/sgml/ref/create_trigger.sgml
  doc/src/sgml/ref/initdb.sgml
  doc/src/sgml/ref/psql-ref.sgml
  doc/src/sgml/ref/reindex.sgml
  doc/src/sgml/spi.sgml
  doc/src/sgml/storage.sgml
  doc/src/sgml/typeconv.sgml
Labels: 再レビュー待ち, version 16

#3129 update for 17.0 - part 9
  doc/src/sgml/ref/alter_role.sgml
  doc/src/sgml/ref/create_role.sgml
  doc/src/sgml/ref/set_role.sgml
Labels: レビュー待ち

#3113 update for 17.0 - part 5
  doc/src/sgml/indices.sgml
  doc/src/sgml/json.sgml
  doc/src/sgml/manage-ag.sgml
  doc/src/sgml/pageinspect.sgml
  doc/src/sgml/parallel.sgml
Labels: 再レビュー待ち

#3120 Translate installation.sgml
  doc/src/sgml/installation.sgml
Labels: 再レビュー待ち

#3128 catalogs.sgmlの17.0対応です
  doc/src/sgml/catalogs.sgml
  doc/src/sgml/catalogs0.sgml
  doc/src/sgml/catalogs1.sgml
  doc/src/sgml/catalogs2.sgml
Labels: 指摘事項あり

#3147 wal_writer_delay と wal_writer_flush_after の説明を修正
  doc/src/sgml/config.sgml
  doc/src/sgml/config1.sgml
Labels: レビュー待ち

#3138 標準SQLに統一（１）
  doc/src/sgml/btree.sgml
  doc/src/sgml/catalogs.sgml
  doc/src/sgml/catalogs2.sgml
  doc/src/sgml/charset.sgml
  doc/src/sgml/config.sgml
  doc/src/sgml/config3.sgml
  doc/src/sgml/dblink.sgml
  doc/src/sgml/ddl.sgml
  doc/src/sgml/ecpg.sgml
  doc/src/sgml/features.sgml
  doc/src/sgml/func.sgml
  doc/src/sgml/func1.sgml
  doc/src/sgml/func2.sgml
  doc/src/sgml/func3.sgml
  doc/src/sgml/func4.sgml
  doc/src/sgml/glossary.sgml
  doc/src/sgml/mvcc.sgml
  doc/src/sgml/queries.sgml
  doc/src/sgml/ref/alter_procedure.sgml
  doc/src/sgml/ref/alter_routine.sgml
  doc/src/sgml/ref/psql-ref.sgml
  doc/src/sgml/ref/select.sgml
  doc/src/sgml/release-16.sgml
  doc/src/sgml/syntax.sgml
  doc/src/sgml/system-views.sgml
  doc/src/sgml/tablesample-method.sgml
  doc/src/sgml/xfunc.sgml
Labels: レビュー待ち, version 16

#3148 関数名の誤り修正
  doc/src/sgml/protocol.sgml
Labels: レビュー待ち, version 16

#3141 訳抜けの文があるファイルを修正
  doc/src/sgml/btree.sgml
  doc/src/sgml/config.sgml
  doc/src/sgml/config0.sgml
  doc/src/sgml/config1.sgml
  doc/src/sgml/config3.sgml
  doc/src/sgml/cube.sgml
  doc/src/sgml/func.sgml
  doc/src/sgml/func2.sgml
  doc/src/sgml/func3.sgml
  doc/src/sgml/func4.sgml
  doc/src/sgml/hash.sgml
  doc/src/sgml/high-availability.sgml
  doc/src/sgml/installation.sgml
  doc/src/sgml/intarray.sgml
  doc/src/sgml/jit.sgml
  doc/src/sgml/logicaldecoding.sgml
  doc/src/sgml/pltcl.sgml
  doc/src/sgml/postgres-fdw.sgml
  doc/src/sgml/protocol.sgml
  doc/src/sgml/textsearch.sgml
Labels: レビュー待ち, version 16

#3149 #3147のバックポート
  doc/src/sgml/config.sgml
  doc/src/sgml/config1.sgml
Labels: レビュー待ち, version 16
