Repository pgsql-jp/jpug-doc, pull requests merged in 2024-09, with the labels that each got.

#3040 update datatype for 16.4
  doc/src/sgml/datatype.sgml
Labels: マージ待ち（レビュー済み）

#3050 「デフォルト」が抜けている箇所の修正
  doc/src/sgml/config.sgml
  doc/src/sgml/config1.sgml
  doc/src/sgml/docguide.sgml
  doc/src/sgml/ecpg.sgml
  doc/src/sgml/func.sgml
  doc/src/sgml/func1.sgml
  doc/src/sgml/func2.sgml
  doc/src/sgml/func4.sgml
  doc/src/sgml/install-windows.sgml
  doc/src/sgml/ref/createuser.sgml
  doc/src/sgml/ref/pgbench.sgml
  doc/src/sgml/sepgsql.sgml
Labels: 他にも誰か見て（レビュー済み）

#3053 fix translation of 'question mark'
  doc/src/sgml/func.sgml
  doc/src/sgml/func3.sgml
  doc/src/sgml/ref/ecpg-ref.sgml
Labels: レビュー待ち

#3054 loadableを「読み込み可能な」から「ロード可能な」に変更
  doc/src/sgml/high-availability.sgml
  doc/src/sgml/plpgsql.sgml
  doc/src/sgml/ref/pg_config-ref.sgml
  doc/src/sgml/sepgsql.sgml
Labels: レビュー待ち, version 16

#3056 PDF用の設定マージ漏れ
  doc/src/sgml/stylesheet-fo.xsl
Labels: レビュー待ち, doc_ja_17

#3060 RC1のマージミスを修正
  contrib/amcheck/verify_nbtree.c
  doc/src/sgml/config.sgml
  doc/src/sgml/installation.sgml
  doc/src/sgml/limits.sgml
  doc/src/sgml/logical-replication.sgml
  doc/src/sgml/release-17.sgml
  doc/src/sgml/wal.sgml
Labels: レビュー待ち

#3058 更新されてなかった訳の修正
  doc/src/sgml/func.sgml
  doc/src/sgml/func1.sgml
  doc/src/sgml/func3.sgml
  doc/src/sgml/func4.sgml
Labels: レビュー待ち, version 16

#3063 userの訳をユーザに統一
  .ng.list
  doc/src/sgml/adminpack.sgml
  doc/src/sgml/basebackup-to-shell.sgml
  doc/src/sgml/bki.sgml
  doc/src/sgml/client-auth.sgml
  doc/src/sgml/config.sgml
  doc/src/sgml/config2.sgml
  doc/src/sgml/config3.sgml
  doc/src/sgml/fdwhandler.sgml
  doc/src/sgml/file-fdw.sgml
  doc/src/sgml/func.sgml
  doc/src/sgml/func4.sgml
  doc/src/sgml/glossary.sgml
  doc/src/sgml/logical-replication.sgml
  doc/src/sgml/maintenance.sgml
  doc/src/sgml/monitoring.sgml
  doc/src/sgml/mvcc.sgml
  doc/src/sgml/postgres-fdw.sgml
  doc/src/sgml/ref/alter_database.sgml
  doc/src/sgml/ref/alter_publication.sgml
  doc/src/sgml/ref/alter_subscription.sgml
  doc/src/sgml/ref/alter_system.sgml
  doc/src/sgml/ref/create_publication.sgml
  doc/src/sgml/ref/create_view.sgml
  doc/src/sgml/ref/initdb.sgml
  doc/src/sgml/ref/lock.sgml
  doc/src/sgml/ref/pg_dump.sgml
  doc/src/sgml/release-16.sgml
  doc/src/sgml/rules.sgml
  doc/src/sgml/runtime.sgml
  doc/src/sgml/system-views.sgml
  doc/src/sgml/xaggr.sgml
Labels: レビュー待ち, version 16

#3057 マッチ度文と機械翻訳文の追加
  doc/src/sgml/bgworker.sgml
  doc/src/sgml/docguide.sgml
  doc/src/sgml/monitoring.sgml
Labels: レビュー待ち, doc_ja_17

#3068 マージのミスとマッチ度、機械翻訳の改善
  doc/src/sgml/catalogs.sgml
  doc/src/sgml/catalogs0.sgml
  doc/src/sgml/catalogs1.sgml
  doc/src/sgml/catalogs2.sgml
  doc/src/sgml/catalogs3.sgml
  doc/src/sgml/config.sgml
  doc/src/sgml/config2.sgml
  doc/src/sgml/config3.sgml
  doc/src/sgml/custom-scan.sgml
  doc/src/sgml/ddl.sgml
  doc/src/sgml/func.sgml
  doc/src/sgml/func1.sgml
  doc/src/sgml/func2.sgml
  doc/src/sgml/func3.sgml
  doc/src/sgml/func4.sgml
  doc/src/sgml/glossary.sgml
  doc/src/sgml/libpq.sgml
  doc/src/sgml/libpq0.sgml
  doc/src/sgml/libpq2.sgml
  doc/src/sgml/logical-replication.sgml
  doc/src/sgml/pgrowlocks.sgml
  doc/src/sgml/pgstatstatements.sgml
  doc/src/sgml/ref/alter_table.sgml
  doc/src/sgml/ref/copy.sgml
  doc/src/sgml/ref/create_operator.sgml
  doc/src/sgml/ref/create_table.sgml
  doc/src/sgml/ref/initdb.sgml
  doc/src/sgml/ref/merge.sgml
  doc/src/sgml/ref/pg_basebackup.sgml
  doc/src/sgml/ref/pg_checksums.sgml
  doc/src/sgml/ref/pg_combinebackup.sgml
  doc/src/sgml/ref/pg_createsubscriber.sgml
  doc/src/sgml/ref/pg_dump.sgml
  doc/src/sgml/ref/pg_restore.sgml
  doc/src/sgml/ref/pg_rewind.sgml
  doc/src/sgml/ref/pgbench.sgml
  doc/src/sgml/ref/pgupgrade.sgml
  doc/src/sgml/release-17.sgml
  doc/src/sgml/runtime.sgml
  doc/src/sgml/spi.sgml
  doc/src/sgml/syntax.sgml
  doc/src/sgml/system-views.sgml
  doc/src/sgml/user-manag.sgml
Labels: レビュー待ち

#3069 split-*の入る位置が間違っていたのを修正
  doc/src/sgml/catalogs.sgml
  doc/src/sgml/catalogs0.sgml
  doc/src/sgml/catalogs2.sgml
  doc/src/sgml/catalogs3.sgml
Labels: レビュー待ち

#3065 serverの訳をサーバに統一
  .ng.list
  doc/src/sgml/backup.sgml
  doc/src/sgml/basic-archive.sgml
  doc/src/sgml/client-auth.sgml
  doc/src/sgml/config.sgml
  doc/src/sgml/config0.sgml
  doc/src/sgml/config1.sgml
  doc/src/sgml/config3.sgml
  doc/src/sgml/contrib.sgml
  doc/src/sgml/fdwhandler.sgml
  doc/src/sgml/func.sgml
  doc/src/sgml/func1.sgml
  doc/src/sgml/libpq.sgml
  doc/src/sgml/libpq0.sgml
  doc/src/sgml/logical-replication.sgml
  doc/src/sgml/mvcc.sgml
  doc/src/sgml/perform.sgml
  doc/src/sgml/pgprewarm.sgml
  doc/src/sgml/protocol.sgml
  doc/src/sgml/ref/create_subscription.sgml
  doc/src/sgml/ref/pg_dump.sgml
  doc/src/sgml/ref/pg_dumpall.sgml
  doc/src/sgml/ref/pgbench.sgml
  doc/src/sgml/release-16.sgml
  doc/src/sgml/runtime.sgml
Labels: レビュー待ち, version 16

#3066 clauseを句に統一
  doc/src/sgml/ddl.sgml
  doc/src/sgml/func.sgml
  doc/src/sgml/func1.sgml
  doc/src/sgml/func3.sgml
  doc/src/sgml/ref/alter_table.sgml
  doc/src/sgml/ref/create_table.sgml
  doc/src/sgml/ref/insert.sgml
  doc/src/sgml/ref/select.sgml
  doc/src/sgml/tablefunc.sgml
  doc/src/sgml/xindex.sgml
Labels: レビュー待ち, version 16

#3067 The optional clauseの表現と統一しました
  doc/src/sgml/ref/alter_sequence.sgml
  doc/src/sgml/ref/create_sequence.sgml
Labels: レビュー待ち, version 16

#3070 機械翻訳の改善
  doc/src/sgml/amcheck.sgml
  doc/src/sgml/archive-modules.sgml
  doc/src/sgml/backup-manifest.sgml
  doc/src/sgml/bgworker.sgml
  doc/src/sgml/brin.sgml
  doc/src/sgml/catalogs.sgml
  doc/src/sgml/catalogs0.sgml
  doc/src/sgml/catalogs1.sgml
  doc/src/sgml/catalogs2.sgml
  doc/src/sgml/charset.sgml
  doc/src/sgml/config.sgml
  doc/src/sgml/config0.sgml
  doc/src/sgml/config1.sgml
  doc/src/sgml/config2.sgml
  doc/src/sgml/config3.sgml
  doc/src/sgml/custom-rmgr.sgml
  doc/src/sgml/ddl.sgml
  doc/src/sgml/dml.sgml
  doc/src/sgml/docguide.sgml
  doc/src/sgml/ecpg.sgml
  doc/src/sgml/event-trigger.sgml
  doc/src/sgml/features.sgml
  doc/src/sgml/file-fdw.sgml
  doc/src/sgml/func.sgml
  doc/src/sgml/func3.sgml
  doc/src/sgml/func4.sgml
  doc/src/sgml/glossary.sgml
  doc/src/sgml/high-availability.sgml
  doc/src/sgml/indexam.sgml
  doc/src/sgml/information_schema.sgml
  doc/src/sgml/installation.sgml
  doc/src/sgml/logical-replication.sgml
  doc/src/sgml/logicaldecoding.sgml
  doc/src/sgml/maintenance.sgml
  doc/src/sgml/mvcc.sgml
  doc/src/sgml/perform.sgml
  doc/src/sgml/pgrowlocks.sgml
  doc/src/sgml/pgstatstatements.sgml
  doc/src/sgml/plpgsql.sgml
  doc/src/sgml/queries.sgml
  doc/src/sgml/ref/alter_subscription.sgml
  doc/src/sgml/ref/merge.sgml
  doc/src/sgml/ref/pg_createsubscriber.sgml
  doc/src/sgml/ref/pg_dump.sgml
  doc/src/sgml/release-17.sgml
  doc/src/sgml/rules.sgml
  doc/src/sgml/storage.sgml
  doc/src/sgml/syntax.sgml
  doc/src/sgml/trigger.sgml
  doc/src/sgml/wal.sgml
  doc/src/sgml/xindex.sgml
Labels: レビュー待ち, doc_ja_17

#3071 段落の文の共通化（１）
  doc/src/sgml/oid2name.sgml
  doc/src/sgml/ref/clusterdb.sgml
  doc/src/sgml/ref/createdb.sgml
  doc/src/sgml/ref/createuser.sgml
  doc/src/sgml/ref/dropdb.sgml
  doc/src/sgml/ref/dropuser.sgml
  doc/src/sgml/ref/initdb.sgml
  doc/src/sgml/ref/pg_basebackup.sgml
  doc/src/sgml/ref/pg_checksums.sgml
  doc/src/sgml/ref/pg_controldata.sgml
  doc/src/sgml/ref/pg_dump.sgml
  doc/src/sgml/ref/pg_dumpall.sgml
  doc/src/sgml/ref/pg_isready.sgml
  doc/src/sgml/ref/pg_receivewal.sgml
  doc/src/sgml/ref/pg_recvlogical.sgml
  doc/src/sgml/ref/pg_resetwal.sgml
  doc/src/sgml/ref/pg_restore.sgml
  doc/src/sgml/ref/pg_rewind.sgml
  doc/src/sgml/ref/pg_waldump.sgml
  doc/src/sgml/ref/pgarchivecleanup.sgml
  doc/src/sgml/ref/pgbench.sgml
  doc/src/sgml/ref/pgtestfsync.sgml
  doc/src/sgml/ref/psql-ref.sgml
  doc/src/sgml/ref/reindexdb.sgml
  doc/src/sgml/ref/vacuumdb.sgml
  doc/src/sgml/vacuumlo.sgml
Labels: 再レビュー待ち, version 16

#3073 段落の文の共通化（３）
  doc/src/sgml/gist.sgml
  doc/src/sgml/spgist.sgml
Labels: レビュー待ち, version 16

#3074 familyの訳の見直し
  doc/src/sgml/config.sgml
  doc/src/sgml/config0.sgml
  doc/src/sgml/installation.sgml
  doc/src/sgml/textsearch.sgml
Labels: レビュー待ち, version 16

#3075 familの見直し２
  doc/src/sgml/btree.sgml
Labels: レビュー待ち, version 16

#3072 段落の文の共通化（２）
  doc/src/sgml/ref/pg_amcheck.sgml
  doc/src/sgml/ref/pg_receivewal.sgml
  doc/src/sgml/ref/pg_recvlogical.sgml
  doc/src/sgml/vacuumlo.sgml
Labels: 指摘事項あり, version 16

#3078 走査->スキャンの変換
  doc/src/sgml/amcheck.sgml
  doc/src/sgml/gist.sgml
  doc/src/sgml/hash.sgml
  doc/src/sgml/hstore.sgml
  doc/src/sgml/intarray.sgml
  doc/src/sgml/ltree.sgml
  doc/src/sgml/perform.sgml
  doc/src/sgml/pgstattuple.sgml
  doc/src/sgml/pgtrgm.sgml
  doc/src/sgml/postgres-fdw.sgml
  doc/src/sgml/ref/alter_table.sgml
  doc/src/sgml/ref/create_aggregate.sgml
  doc/src/sgml/ref/create_table.sgml
  doc/src/sgml/ref/fetch.sgml
  doc/src/sgml/ref/pg_receivewal.sgml
  doc/src/sgml/ref/reindex.sgml
  doc/src/sgml/ref/select.sgml
  doc/src/sgml/ref/truncate.sgml
  doc/src/sgml/textsearch.sgml
  doc/src/sgml/xfunc.sgml
Labels: レビュー待ち, version 16

#3080 フィルターをフィルタに変換
  .ng.list
  doc/src/sgml/advanced.sgml
  doc/src/sgml/bloom.sgml
  doc/src/sgml/client-auth.sgml
  doc/src/sgml/config.sgml
  doc/src/sgml/config0.sgml
  doc/src/sgml/func.sgml
  doc/src/sgml/func2.sgml
  doc/src/sgml/func3.sgml
  doc/src/sgml/json.sgml
  doc/src/sgml/ref/alter_subscription.sgml
  doc/src/sgml/ref/create_policy.sgml
  doc/src/sgml/replication-origins.sgml
Labels: レビュー待ち, version 16

#3081 consumerの訳を消費者に統一
  doc/src/sgml/config.sgml
  doc/src/sgml/config1.sgml
  doc/src/sgml/logicaldecoding.sgml
Labels: レビュー待ち, version 16

#3079 走査→スキャンの変換とシーケンシャルスキャン、インデックススキャンの統一
  doc/src/sgml/brin.sgml
  doc/src/sgml/config.sgml
  doc/src/sgml/config0.sgml
  doc/src/sgml/config1.sgml
  doc/src/sgml/config3.sgml
  doc/src/sgml/ddl.sgml
  doc/src/sgml/maintenance.sgml
  doc/src/sgml/monitoring.sgml
  doc/src/sgml/parallel.sgml
  doc/src/sgml/system-views.sgml
  doc/src/sgml/tablesample-method.sgml
Labels: 再レビュー待ち, version 16

#3082 vectorの訳でベクタとベクターがありましたが、ベクトルに統一しました
  doc/src/sgml/client-auth.sgml
  doc/src/sgml/gin.sgml
  doc/src/sgml/gist.sgml
Labels: レビュー待ち, version 16

#3083 長音を省く統一（１）
  doc/src/sgml/bloom.sgml
  doc/src/sgml/config.sgml
  doc/src/sgml/config3.sgml
  doc/src/sgml/datatype.sgml
  doc/src/sgml/monitoring.sgml
Labels: レビュー待ち, version 16

#3084 長音を省く統一（２）
  doc/src/sgml/glossary.sgml
  doc/src/sgml/monitoring.sgml
  doc/src/sgml/ref/pgtesttiming.sgml
  doc/src/sgml/runtime.sgml
Labels: レビュー待ち, version 16

#3085 翻訳漏れ修正
  doc/src/sgml/config.sgml
  doc/src/sgml/config1.sgml
  doc/src/sgml/libpq.sgml
  doc/src/sgml/libpq1.sgml
Labels: レビュー待ち, version 16

#3086 atomicallyの訳修正
  doc/src/sgml/func.sgml
  doc/src/sgml/func3.sgml
Labels: レビュー待ち, version 16

#3087 chapter,sectionの統一
  doc/src/sgml/appendix-obsolete.sgml
  doc/src/sgml/backup-manifest.sgml
  doc/src/sgml/client-auth.sgml
  doc/src/sgml/config.sgml
  doc/src/sgml/config1.sgml
  doc/src/sgml/contrib.sgml
  doc/src/sgml/datatype.sgml
  doc/src/sgml/ddl.sgml
  doc/src/sgml/diskusage.sgml
  doc/src/sgml/ecpg.sgml
  doc/src/sgml/features.sgml
  doc/src/sgml/indices.sgml
  doc/src/sgml/maintenance.sgml
  doc/src/sgml/queries.sgml
  doc/src/sgml/query.sgml
  doc/src/sgml/start.sgml
  doc/src/sgml/tablefunc.sgml
  doc/src/sgml/textsearch.sgml
Labels: レビュー待ち, version 16

#3092 長音を省く統一（３）
  .ng.list
  doc/src/sgml/btree.sgml
  doc/src/sgml/config.sgml
  doc/src/sgml/config1.sgml
  doc/src/sgml/config3.sgml
  doc/src/sgml/ddl.sgml
  doc/src/sgml/dml.sgml
  doc/src/sgml/ecpg.sgml
  doc/src/sgml/fdwhandler.sgml
  doc/src/sgml/func.sgml
  doc/src/sgml/func2.sgml
  doc/src/sgml/func3.sgml
  doc/src/sgml/func4.sgml
  doc/src/sgml/information_schema.sgml
  doc/src/sgml/logical-replication.sgml
  doc/src/sgml/mvcc.sgml
  doc/src/sgml/pltcl.sgml
  doc/src/sgml/postgres-fdw.sgml
  doc/src/sgml/rangetypes.sgml
  doc/src/sgml/ref/comment.sgml
  doc/src/sgml/ref/create_domain.sgml
  doc/src/sgml/ref/create_policy.sgml
  doc/src/sgml/ref/create_view.sgml
  doc/src/sgml/ref/insert.sgml
  doc/src/sgml/ref/notify.sgml
  doc/src/sgml/ref/pg_basebackup.sgml
  doc/src/sgml/ref/select.sgml
  doc/src/sgml/release-16.sgml
  doc/src/sgml/rules.sgml
  doc/src/sgml/spi.sgml
Labels: レビュー待ち, version 16

#3093 17.0対応（doc_ja_16の更新適用ミスの修正）
  doc/src/sgml/gist.sgml
  doc/src/sgml/spgist.sgml
Labels: レビュー待ち

#3104 本家でREADME.mdが追加されたため移動
  .github/README.md
Labels: レビュー待ち
