Repository pgsql-jp/jpug-doc, pull requests merged in 2024-02, with the labels that each got.

#2816 タグのチェックに引っかかったファイルを修正
  doc/src/sgml/ref/create_role.sgml
  doc/src/sgml/ref/createuser.sgml
  doc/src/sgml/ref/explain.sgml
Labels: レビュー待ち

#2817 英語の単語チェックによる修正
  doc/src/sgml/config.sgml
  doc/src/sgml/config3.sgml
Labels: レビュー待ち

#2815 レビュー待ちラベルが再度ついてしまうのを修正
  .github/workflows/pr-label.yml
Labels: レビュー待ち

#2810 glossary.sgmlの16.0対応です
  doc/src/sgml/glossary.sgml
Labels: 再レビュー待ち, レビュー待ち

#2818 翻訳形式を統一するための修正
  doc/src/sgml/config.sgml
  doc/src/sgml/config0.sgml
  doc/src/sgml/config2.sgml
  doc/src/sgml/plpython.sgml
  doc/src/sgml/ref/pg_waldump.sgml
  doc/src/sgml/ref/release_savepoint.sgml
  doc/src/sgml/xfunc.sgml
Labels: レビュー待ち

#2819 features.sgmlの修正漏れを修正
  doc/src/sgml/features.sgml
Labels: レビュー待ち

#2822 update pgbench for 16.0
  doc/src/sgml/ref/pgbench.sgml
Labels: マージ待ち（レビュー済み）

#2796 func.sgmlのPostgreSQL 16.0対応です。
  doc/src/sgml/func.sgml
  doc/src/sgml/func1.sgml
  doc/src/sgml/func2.sgml
  doc/src/sgml/func3.sgml
  doc/src/sgml/func4.sgml
Labels: レビュー待ち, 他にも誰か見て（レビュー済み）

#2825 func.sgmlのチェックで見つけた問題の修正です
  doc/src/sgml/func.sgml
  doc/src/sgml/func1.sgml
  doc/src/sgml/func2.sgml
  doc/src/sgml/func3.sgml
  doc/src/sgml/func4.sgml
Labels: 再レビュー待ち

#2826 Add machine translation
  doc/src/sgml/release-16.sgml
Labels: version 16.2

#2805 update for 16.0 - new part 15
  doc/src/sgml/ref/grant.sgml
  doc/src/sgml/ref/revoke.sgml
Labels: 他にも誰か見て（レビュー済み）

#2834 <title>が同じ英文の場合は同じ日本語にする
  doc/src/sgml/bloom.sgml
  doc/src/sgml/citext.sgml
  doc/src/sgml/config.sgml
  doc/src/sgml/ddl.sgml
  doc/src/sgml/extend.sgml
  doc/src/sgml/gin.sgml
  doc/src/sgml/indices.sgml
  doc/src/sgml/installation.sgml
  doc/src/sgml/lo.sgml
  doc/src/sgml/mvcc.sgml
  doc/src/sgml/nls.sgml
  doc/src/sgml/pgcrypto.sgml
  doc/src/sgml/postgres-fdw.sgml
  doc/src/sgml/query.sgml
  doc/src/sgml/ref/alter_procedure.sgml
  doc/src/sgml/ref/alter_type.sgml
  doc/src/sgml/ref/create_collation.sgml
  doc/src/sgml/ref/create_opclass.sgml
  doc/src/sgml/ref/create_table.sgml
  doc/src/sgml/ref/execute.sgml
  doc/src/sgml/ref/insert.sgml
  doc/src/sgml/ref/load.sgml
  doc/src/sgml/ref/pg_basebackup.sgml
  doc/src/sgml/ref/pg_recvlogical.sgml
  doc/src/sgml/ref/psql-ref.sgml
  doc/src/sgml/ref/set_session_auth.sgml
  doc/src/sgml/regress.sgml
  doc/src/sgml/release-16.sgml
  doc/src/sgml/spi.sgml
  doc/src/sgml/textsearch.sgml
  doc/src/sgml/vacuumlo.sgml
Labels: レビュー待ち

#2835 doc_ja_16_2の更新
  doc/src/sgml/bloom.sgml
  doc/src/sgml/citext.sgml
  doc/src/sgml/config.sgml
  doc/src/sgml/ddl.sgml
  doc/src/sgml/docguide.sgml
  doc/src/sgml/extend.sgml
  doc/src/sgml/func.sgml
  doc/src/sgml/gin.sgml
  doc/src/sgml/indices.sgml
  doc/src/sgml/installation.sgml
  doc/src/sgml/lo.sgml
  doc/src/sgml/mvcc.sgml
  doc/src/sgml/nls.sgml
  doc/src/sgml/pgcrypto.sgml
  doc/src/sgml/postgres-fdw.sgml
  doc/src/sgml/query.sgml
  doc/src/sgml/ref/alter_default_privileges.sgml
  doc/src/sgml/ref/alter_procedure.sgml
  doc/src/sgml/ref/alter_system.sgml
  doc/src/sgml/ref/analyze.sgml
  doc/src/sgml/ref/copy.sgml
  doc/src/sgml/ref/create_operator.sgml
  doc/src/sgml/ref/create_role.sgml
  doc/src/sgml/ref/create_rule.sgml
  doc/src/sgml/ref/create_server.sgml
  doc/src/sgml/ref/create_subscription.sgml
  doc/src/sgml/ref/create_table.sgml
  doc/src/sgml/ref/grant.sgml
  doc/src/sgml/ref/initdb.sgml
  doc/src/sgml/ref/merge.sgml
  doc/src/sgml/ref/pg_dump.sgml
  doc/src/sgml/ref/pg_dumpall.sgml
  doc/src/sgml/ref/pg_recvlogical.sgml
  doc/src/sgml/ref/pg_restore.sgml
  doc/src/sgml/ref/pgupgrade.sgml
  doc/src/sgml/ref/psql-ref.sgml
  doc/src/sgml/ref/revoke.sgml
  doc/src/sgml/ref/select.sgml
  doc/src/sgml/regress.sgml
  doc/src/sgml/release-16.sgml
  doc/src/sgml/sources.sgml
  doc/src/sgml/spi.sgml
  doc/src/sgml/storage.sgml
  doc/src/sgml/system-views.sgml
  doc/src/sgml/textsearch.sgml
  doc/src/sgml/user-manag.sgml
  doc/src/sgml/wal.sgml
Labels: レビュー待ち, version 16.2
