Repository pgsql-jp/jpug-doc, pull requests merged in 2024-03, with the labels that each got.

#2814 datatype.sgmlのv16対応
  doc/src/sgml/datatype.sgml
Labels: 再レビュー待ち

#2743 acronyms.sgmlの16.0対応です
  doc/src/sgml/acronyms.sgml
Labels: 再レビュー待ち

#2827 update for 16.0 - new part 16
  doc/src/sgml/ref/alter_subscription.sgml
  doc/src/sgml/ref/create_subscription.sgml
  doc/src/sgml/ref/drop_subscription.sgml
Labels: マージ待ち（レビュー済み）

#2811 ddl.sgmlの16.0対応です
  doc/src/sgml/ddl.sgml
Labels: 他にも誰か見て（レビュー済み）

#2831 update sql_features for 16.0
  src/backend/catalog/sql_feature_packages.txt.ja
  src/backend/catalog/sql_features.txt.ja
Labels: 再レビュー待ち

#2821 update vacuumdb for 16.0
  doc/src/sgml/ref/vacuumdb.sgml
Labels: 他にも誰か見て（レビュー済み）

#2794 update for 16.0 - new part 13
  doc/src/sgml/ref/alter_database.sgml
  doc/src/sgml/ref/create_database.sgml
  doc/src/sgml/ref/createdb.sgml
  doc/src/sgml/ref/initdb.sgml
Labels: 再レビュー待ち, レビュー待ち

#2823 system-views.sgmlの16.0対応です
  doc/src/sgml/system-views.sgml
Labels: 他にも誰か見て（レビュー済み）

#2842 commandは訳さないように修正
  doc/src/sgml/config.sgml
  doc/src/sgml/config1.sgml
  doc/src/sgml/config3.sgml
  doc/src/sgml/release-16.sgml
Labels: レビュー待ち

#2837 indexam.sgmlの16.0対応です
  doc/src/sgml/indexam.sgml
Labels: レビュー待ち

#2849 doc_ja_16の内容をフォワードポート
  doc/src/sgml/config.sgml
  doc/src/sgml/config1.sgml
  doc/src/sgml/config3.sgml
  doc/src/sgml/indexam.sgml
  doc/src/sgml/protocol.sgml
  doc/src/sgml/ref/create_operator.sgml
  doc/src/sgml/ref/initdb.sgml
  doc/src/sgml/regress.sgml
  doc/src/sgml/release-16.sgml
Labels: レビュー待ち, version 16.2

#2847 翻訳漏れ対応
  doc/src/sgml/ref/create_procedure.sgml
  doc/src/sgml/ref/create_transform.sgml
Labels: レビュー待ち

#2848 functions.sgmlの翻訳漏れの翻訳を追加
  doc/src/sgml/func.sgml
  doc/src/sgml/func1.sgml
  doc/src/sgml/func2.sgml
  doc/src/sgml/func4.sgml
Labels: レビュー待ち

#2846 翻訳の分割単位を厳格化
  doc/src/sgml/config.sgml
  doc/src/sgml/config0.sgml
  doc/src/sgml/config1.sgml
  doc/src/sgml/datatype.sgml
  doc/src/sgml/jit.sgml
  doc/src/sgml/pltcl.sgml
  doc/src/sgml/ref/alter_collation.sgml
  doc/src/sgml/ref/alter_database.sgml
  doc/src/sgml/ref/alter_default_privileges.sgml
  doc/src/sgml/ref/alter_table.sgml
  doc/src/sgml/ref/create_aggregate.sgml
  doc/src/sgml/ref/create_index.sgml
  doc/src/sgml/ref/create_subscription.sgml
  doc/src/sgml/ref/postgres-ref.sgml
  doc/src/sgml/ref/psql-ref.sgml
  doc/src/sgml/ref/select.sgml
  doc/src/sgml/ref/vacuumdb.sgml
  doc/src/sgml/regress.sgml
  doc/src/sgml/runtime.sgml
  doc/src/sgml/spgist.sgml
  doc/src/sgml/storage.sgml
Labels: 他にも誰か見て（レビュー済み）

#2836 high-availability.sgmlのPostgreSQL 16.0対応です。
  doc/src/sgml/high-availability.sgml
Labels: マージ待ち（レビュー済み）

#2853 logicaldecoding.sgmlの誤字修正
  doc/src/sgml/logicaldecoding.sgml
Labels: レビュー待ち

#2855 fix typos
  doc/src/sgml/release-16.sgml
Labels: レビュー待ち

#2856 fix typo in pg_dumpall
  doc/src/sgml/ref/pg_dumpall.sgml
Labels: レビュー待ち

#2839 update *_table for 16.0
  doc/src/sgml/ref/alter_table.sgml
  doc/src/sgml/ref/create_table.sgml
Labels: マージ待ち（レビュー済み）

#2844 ecpgv16の対応
  doc/src/sgml/ecpg.sgml
Labels: 他にも誰か見て（レビュー済み）

#2859 fix typo in create_table
  doc/src/sgml/ref/create_table.sgml
Labels: レビュー待ち
