Repository pgsql-jp/jpug-doc, pull requests merged in 2024-07, with the labels that each got.

#2948 fix typos
  doc/src/sgml/protocol.sgml
  doc/src/sgml/ref/pg_verifybackup.sgml
  doc/src/sgml/system-views.sgml
Labels: マージ待ち（レビュー済み）

#2949 update for 16.3 - part 8
  doc/src/sgml/manage-ag.sgml
  doc/src/sgml/plpython.sgml
  doc/src/sgml/spi.sgml
Labels: マージ待ち（レビュー済み）

#2954 indexam.sgmlの16.3対応です
  doc/src/sgml/indexam.sgml
Labels: レビュー待ち

#2955 high-availability.sgmlの16.3対応です
  doc/src/sgml/high-availability.sgml
Labels: レビュー待ち

#2959 update limits for 16.3
  doc/src/sgml/limits.sgml
Labels: マージ待ち（レビュー済み）

#2950 acronyms.sgmlの16.3対応です
  doc/src/sgml/acronyms.sgml
Labels: 指摘事項あり

#2952 update alter_system for 16.3
  doc/src/sgml/ref/alter_system.sgml
Labels: 再レビュー待ち

#2958 update create_rule for 16.3
  doc/src/sgml/ref/create_rule.sgml
Labels: 再レビュー待ち

#2960 update alter_default_privileges for 16.3
  doc/src/sgml/ref/alter_default_privileges.sgml
Labels: マージ待ち（レビュー済み）

#2961 Fix a mistranslation on FILTER clause
  doc/src/sgml/syntax.sgml
Labels: マージ待ち（レビュー済み）

#2964 installation.sgmlの16.3対応です
  doc/src/sgml/installation.sgml
Labels: マージ待ち（レビュー済み）

#2965 system-views.sgmlの16.3対応です
  doc/src/sgml/system-views.sgml
Labels: マージ待ち（レビュー済み）

#2966 protocol.sgmlの16.3対応です
  doc/src/sgml/protocol.sgml
Labels: 再レビュー待ち

#2947 update maintenance for 16.3
  doc/src/sgml/maintenance.sgml
Labels: 再レビュー待ち

#2968 update information_schema for 16.3
  doc/src/sgml/information_schema.sgml
Labels: レビュー待ち

#2975 Add .gitignore entry
  doc/src/sgml/.gitignore
Labels: レビュー待ち

#2977 貢献者情報を更新
  doc/src/sgml/jpug-doc.sgml
Labels: レビュー待ち

#2963 ddl.sgmlの16.3対応です
  doc/src/sgml/ddl.sgml
Labels: 再レビュー待ち

#2970 update monitoring for 16.3
  doc/src/sgml/monitoring.sgml
Labels: マージ待ち（レビュー済み）

#2967 ecpg.sgmlの16.3対応です
  doc/src/sgml/ecpg.sgml
Labels: 他にも誰か見て（レビュー済み）

#2981 remove extra ","
  doc/src/sgml/ref/create_table.sgml
Labels: レビュー待ち

#2982 doc_ja_16のフォワードポート
  doc/src/sgml/acronyms.sgml
  doc/src/sgml/config.sgml
  doc/src/sgml/ddl.sgml
  doc/src/sgml/ecpg.sgml
  doc/src/sgml/high-availability.sgml
  doc/src/sgml/indexam.sgml
  doc/src/sgml/information_schema.sgml
  doc/src/sgml/installation.sgml
  doc/src/sgml/limits.sgml
  doc/src/sgml/maintenance.sgml
  doc/src/sgml/manage-ag.sgml
  doc/src/sgml/plpython.sgml
  doc/src/sgml/protocol.sgml
  doc/src/sgml/ref/alter_default_privileges.sgml
  doc/src/sgml/ref/alter_system.sgml
  doc/src/sgml/ref/create_rule.sgml
  doc/src/sgml/ref/create_table.sgml
  doc/src/sgml/ref/pg_dump.sgml
  doc/src/sgml/ref/pg_verifybackup.sgml
  doc/src/sgml/ref/psql-ref.sgml
  doc/src/sgml/spi.sgml
  doc/src/sgml/storage.sgml
  doc/src/sgml/syntax.sgml
  doc/src/sgml/system-views.sgml
Labels: レビュー待ち, doc_ja_master

#2953 update pg_restore for 16.3
  doc/src/sgml/ref/pg_dump.sgml
  doc/src/sgml/ref/pg_restore.sgml
Labels: マージ待ち（レビュー済み）

#2971 update user-manag for 16.3
  doc/src/sgml/user-manag.sgml
Labels: 他にも誰か見て（レビュー済み）

#2978 xaggr.sgmlで日本語と不自然な箇所があったのでより自然な言い回しにしてみました。
  doc/src/sgml/xaggr.sgml
Labels: 再レビュー待ち

#2969 update merge for 16.3
  doc/src/sgml/ref/merge.sgml
Labels: 指摘事項あり
