Repository pgsql-jp/jpug-doc, pull requests merged in 2024-04, with the labels that each got.

#2829 update pg_dump for 16.0
  doc/src/sgml/ref/pg_dump.sgml
Labels: 他にも誰か見て（レビュー済み）

#2864 make check-ngのパス変更対応の修正
  doc/src/sgml/Makefile
Labels: レビュー待ち

#2861 user-manag.sgmlのPostgreSQL 16.0対応です。
  doc/src/sgml/user-manag.sgml
Labels: 再レビュー待ち

#2869 fix typos
  doc/src/sgml/datatype.sgml
  doc/src/sgml/ref/pgbench.sgml
Labels: レビュー待ち

#2862 pgwalinspect.sgmlのPostgreSQL 16.0対応です。
  doc/src/sgml/pgwalinspect.sgml
Labels: 再レビュー待ち

#2851 update postgres-fdw for 16.0
  doc/src/sgml/postgres-fdw.sgml
Labels: 他にも誰か見て（レビュー済み）

#2863 update backup for 16.0
  doc/src/sgml/backup.sgml
Labels: 再レビュー待ち

#2857 indextermのインデントを変更
  doc/src/sgml/func.sgml
  doc/src/sgml/func3.sgml
Labels: レビュー待ち

#2873 並べ替えの漢字違いがあったので修正
  doc/src/sgml/catalogs.sgml
  doc/src/sgml/catalogs2.sgml
  doc/src/sgml/ref/pg_dump.sgml
  doc/src/sgml/ref/pg_restore.sgml
  doc/src/sgml/ref/pgbench.sgml
Labels: レビュー待ち

#2875 スィート→スイート
  .ng.list
  doc/src/sgml/regress.sgml
Labels: レビュー待ち

#2854 update psql-ref for 16.0
  doc/src/sgml/ref/psql-ref.sgml
Labels: 再レビュー待ち, 他にも誰か見て（レビュー済み）

#2858 update client-auth for 16.0
  doc/src/sgml/client-auth.sgml
Labels: マージ待ち（レビュー済み）

#2867 update plpgsql for 16.0
  doc/src/sgml/plpgsql.sgml
Labels: マージ待ち（レビュー済み）

#2860 xact.sgmlのPostgreSQL 16.0対応です。
  doc/src/sgml/xact.sgml
Labels: 再レビュー待ち

#2876 fix typos in wal
  doc/src/sgml/wal.sgml
Labels: レビュー待ち

#2882 doc_ja_16の更新をフォワードポート
  doc/src/sgml/backup.sgml
  doc/src/sgml/catalogs.sgml
  doc/src/sgml/client-auth.sgml
  doc/src/sgml/datatype.sgml
  doc/src/sgml/ecpg.sgml
  doc/src/sgml/extend.sgml
  doc/src/sgml/glossary.sgml
  doc/src/sgml/high-availability.sgml
  doc/src/sgml/logicaldecoding.sgml
  doc/src/sgml/pgbuffercache.sgml
  doc/src/sgml/pgwalinspect.sgml
  doc/src/sgml/plpgsql.sgml
  doc/src/sgml/postgres-fdw.sgml
  doc/src/sgml/ref/alter_table.sgml
  doc/src/sgml/ref/create_table.sgml
  doc/src/sgml/ref/pg_dump.sgml
  doc/src/sgml/ref/pg_dumpall.sgml
  doc/src/sgml/ref/pg_restore.sgml
  doc/src/sgml/ref/pgbench.sgml
  doc/src/sgml/ref/psql-ref.sgml
  doc/src/sgml/regress.sgml
  doc/src/sgml/release-16.sgml
  doc/src/sgml/runtime.sgml
  doc/src/sgml/user-manag.sgml
  doc/src/sgml/wal.sgml
  doc/src/sgml/xact.sgml
Labels: レビュー待ち, version 16.2
