Repository pgsql-jp/jpug-doc, pull requests merged in 2024-12, with the labels that each got.

#3171 update pg_amcheck for 17.0
  doc/src/sgml/ref/pg_amcheck.sgml
Labels: 他にも誰か見て（レビュー済み）

#3116 update for 17.0 - part 7
  doc/src/sgml/ref/pgarchivecleanup.sgml
  doc/src/sgml/ref/psql-ref.sgml
Labels: マージ待ち（レビュー済み）

#3161 セキュリティラベルのセキュリティを省略しない
  doc/src/sgml/sepgsql.sgml
Labels: レビュー待ち, version 16

#3165 update alter_system for 17.0
  doc/src/sgml/ref/alter_system.sgml
Labels: マージ待ち（レビュー済み）

#3166 update create_collation for 17.0
  doc/src/sgml/ref/create_collation.sgml
Labels: マージ待ち（レビュー済み）

#3168 update vacuum for 17.0
  doc/src/sgml/ref/vacuum.sgml
Labels: 他にも誰か見て（レビュー済み）

#3169 update delete for 17.0
  doc/src/sgml/ref/delete.sgml
Labels: マージ待ち（レビュー済み）

#3172 update analyze for 17.0
  doc/src/sgml/ref/analyze.sgml
Labels: レビュー待ち

#3163 docguide.sgmlの17.0対応です
  doc/src/sgml/docguide.sgml
Labels: 再レビュー待ち

#3162 backup.sgmlのPostgreSQL 17.0対応です。
  doc/src/sgml/backup.sgml
Labels: 他にも誰か見て（レビュー済み）

#3177 フェイルオーバー後の復旧における「former primary system」に関する日本語訳修正
  doc/src/sgml/high-availability.sgml
Labels: レビュー待ち

#3140 fix typos in AT TIME ZONE
  doc/src/sgml/func.sgml
  doc/src/sgml/func2.sgml
Labels: レビュー待ち, version 16

#3183 16からのフォワードポート（２）
  doc/src/sgml/backup.sgml
  doc/src/sgml/brin.sgml
  doc/src/sgml/btree.sgml
  doc/src/sgml/catalogs.sgml
  doc/src/sgml/catalogs1.sgml
  doc/src/sgml/catalogs2.sgml
  doc/src/sgml/client-auth.sgml
  doc/src/sgml/config.sgml
  doc/src/sgml/config0.sgml
  doc/src/sgml/config1.sgml
  doc/src/sgml/config2.sgml
  doc/src/sgml/config3.sgml
  doc/src/sgml/dfunc.sgml
  doc/src/sgml/docguide.sgml
  doc/src/sgml/ecpg.sgml
  doc/src/sgml/func.sgml
  doc/src/sgml/func1.sgml
  doc/src/sgml/func2.sgml
  doc/src/sgml/func3.sgml
  doc/src/sgml/func4.sgml
  doc/src/sgml/gist.sgml
  doc/src/sgml/glossary.sgml
  doc/src/sgml/indices.sgml
  doc/src/sgml/installation.sgml
  doc/src/sgml/json.sgml
  doc/src/sgml/logical-replication.sgml
  doc/src/sgml/logicaldecoding.sgml
  doc/src/sgml/maintenance.sgml
  doc/src/sgml/parallel.sgml
  doc/src/sgml/ref/create_domain.sgml
  doc/src/sgml/ref/lock.sgml
  doc/src/sgml/ref/psql-ref.sgml
  doc/src/sgml/ref/select.sgml
  doc/src/sgml/rowtypes.sgml
  doc/src/sgml/runtime.sgml
  doc/src/sgml/sepgsql.sgml
  doc/src/sgml/spi.sgml
Labels: レビュー待ち

#3184 bgworker.sgmlの17から16へのバックポート
  doc/src/sgml/bgworker.sgml
Labels: レビュー待ち, version 16

#3186 update for 17.0 - part 12
  doc/src/sgml/sources.sgml
  doc/src/sgml/storage.sgml
Labels: マージ待ち（レビュー済み）

#3188 訳抜けの修正
  doc/src/sgml/plpgsql.sgml
  doc/src/sgml/pltcl.sgml
  doc/src/sgml/queries.sgml
  doc/src/sgml/ref/psql-ref.sgml
Labels: レビュー待ち, version 16

#3187 high-availability.sgmlのPostgreSQL 17.0対応
  doc/src/sgml/high-availability.sgml
Labels: 再レビュー待ち

#3133 fileの訳にファイルが抜けている箇所の修正
  doc/src/sgml/backup.sgml
  doc/src/sgml/dfunc.sgml
  doc/src/sgml/extend.sgml
  doc/src/sgml/high-availability.sgml
  doc/src/sgml/nls.sgml
  doc/src/sgml/ref/create_tablespace.sgml
  doc/src/sgml/regress.sgml
  doc/src/sgml/runtime.sgml
  doc/src/sgml/textsearch.sgml
Labels: 再レビュー待ち, version 16

#3180 datatype.sgml の17.0対応
  doc/src/sgml/datatype.sgml
Labels: マージ待ち（レビュー済み）

#3190 amcheck.sgml の日本語訳の PG17 対応
  doc/src/sgml/amcheck.sgml
Labels: レビュー待ち

#3191 archive-modules.sgml の日本語訳 の PG17対応
  doc/src/sgml/archive-modules.sgml
Labels: レビュー待ち

#3192 backup-manifest.sgml の日本語訳の PG17 対応
  doc/src/sgml/backup-manifest.sgml
Labels: レビュー待ち
