Repository pgsql-jp/jpug-doc, pull requests merged in 2024-08, with the labels that each got.

#2973 config.sgmlのPostgreSQL 16.3対応です。
  doc/src/sgml/config.sgml
  doc/src/sgml/config0.sgml
  doc/src/sgml/config1.sgml
  doc/src/sgml/config2.sgml
Labels: 指摘事項あり

#2974 catalogs.sgmlの16.3対応です
  doc/src/sgml/catalogs.sgml
  doc/src/sgml/catalogs0.sgml
  doc/src/sgml/catalogs2.sgml
Labels: 再レビュー待ち

#2980 Update for release-16 (16.3)
  doc/src/sgml/release-16.sgml
Labels: 指摘事項あり

#2985 glossary.sgmlでlinkendに漏れがありました
  doc/src/sgml/glossary.sgml
Labels: レビュー待ち

#2987 メンバーをメンバに統一
  .ng.list
  doc/src/sgml/array.sgml
  doc/src/sgml/bloom.sgml
  doc/src/sgml/brin.sgml
  doc/src/sgml/client-auth.sgml
  doc/src/sgml/custom-scan.sgml
  doc/src/sgml/ddl.sgml
  doc/src/sgml/ecpg.sgml
  doc/src/sgml/extend.sgml
  doc/src/sgml/fdwhandler.sgml
  doc/src/sgml/func.sgml
  doc/src/sgml/func3.sgml
  doc/src/sgml/func4.sgml
  doc/src/sgml/indexam.sgml
  doc/src/sgml/installation.sgml
  doc/src/sgml/logical-replication.sgml
  doc/src/sgml/queries.sgml
  doc/src/sgml/ref/create_opclass.sgml
  doc/src/sgml/ref/psql-ref.sgml
  doc/src/sgml/release-16.sgml
  doc/src/sgml/runtime.sgml
  doc/src/sgml/spgist.sgml
  doc/src/sgml/syntax.sgml
  doc/src/sgml/user-manag.sgml
Labels: レビュー待ち

#2993 SQL descriptorをSQL記述子に統一
  doc/src/sgml/ecpg.sgml
Labels: レビュー待ち

#2994 長音を省く方に統一（１）
  .ng.list
  doc/src/sgml/bki.sgml
  doc/src/sgml/catalogs.sgml
  doc/src/sgml/catalogs2.sgml
  doc/src/sgml/client-auth.sgml
  doc/src/sgml/config.sgml
  doc/src/sgml/config1.sgml
  doc/src/sgml/ddl.sgml
  doc/src/sgml/ecpg.sgml
  doc/src/sgml/func.sgml
  doc/src/sgml/func3.sgml
  doc/src/sgml/func4.sgml
  doc/src/sgml/high-availability.sgml
  doc/src/sgml/json.sgml
  doc/src/sgml/monitoring.sgml
  doc/src/sgml/pgstattuple.sgml
  doc/src/sgml/ref/create_sequence.sgml
  doc/src/sgml/ref/pg_dumpall.sgml
  doc/src/sgml/ref/pgbench.sgml
  doc/src/sgml/runtime.sgml
  doc/src/sgml/sepgsql.sgml
Labels: レビュー待ち

#2999 discussedの訳語を「説明」に変更
  doc/src/sgml/config.sgml
  doc/src/sgml/config3.sgml
  doc/src/sgml/ddl.sgml
  doc/src/sgml/event-trigger.sgml
  doc/src/sgml/func.sgml
  doc/src/sgml/func2.sgml
  doc/src/sgml/mvcc.sgml
  doc/src/sgml/parallel.sgml
  doc/src/sgml/protocol.sgml
  doc/src/sgml/ref/alter_table.sgml
  doc/src/sgml/ref/create_table.sgml
  doc/src/sgml/spgist.sgml
Labels: レビュー待ち

#3000 discussedの訳語を「説明」に変更して重複を解消
  doc/src/sgml/pgtrgm.sgml
Labels: レビュー待ち

#2997 sub-SELECTを副SELECTにする
  doc/src/sgml/advanced.sgml
  doc/src/sgml/datatype.sgml
  doc/src/sgml/ref/create_domain.sgml
  doc/src/sgml/ref/delete.sgml
  doc/src/sgml/ref/update.sgml
Labels: 他にも誰か見て（レビュー済み）

#3005 fix typo in nls
  doc/src/sgml/nls.sgml
Labels: レビュー待ち

#3009 doc_ja_16のフォワードポート20240807
  doc/src/sgml/advanced.sgml
  doc/src/sgml/array.sgml
  doc/src/sgml/bki.sgml
  doc/src/sgml/bloom.sgml
  doc/src/sgml/brin.sgml
  doc/src/sgml/catalogs.sgml
  doc/src/sgml/client-auth.sgml
  doc/src/sgml/config.sgml
  doc/src/sgml/custom-scan.sgml
  doc/src/sgml/datatype.sgml
  doc/src/sgml/ddl.sgml
  doc/src/sgml/ecpg.sgml
  doc/src/sgml/event-trigger.sgml
  doc/src/sgml/extend.sgml
  doc/src/sgml/fdwhandler.sgml
  doc/src/sgml/func.sgml
  doc/src/sgml/glossary.sgml
  doc/src/sgml/high-availability.sgml
  doc/src/sgml/indexam.sgml
  doc/src/sgml/json.sgml
  doc/src/sgml/logical-replication.sgml
  doc/src/sgml/monitoring.sgml
  doc/src/sgml/mvcc.sgml
  doc/src/sgml/nls.sgml
  doc/src/sgml/parallel.sgml
  doc/src/sgml/pgstattuple.sgml
  doc/src/sgml/pgtrgm.sgml
  doc/src/sgml/protocol.sgml
  doc/src/sgml/queries.sgml
  doc/src/sgml/ref/alter_table.sgml
  doc/src/sgml/ref/create_domain.sgml
  doc/src/sgml/ref/create_opclass.sgml
  doc/src/sgml/ref/create_sequence.sgml
  doc/src/sgml/ref/create_table.sgml
  doc/src/sgml/ref/delete.sgml
  doc/src/sgml/ref/merge.sgml
  doc/src/sgml/ref/pg_dump.sgml
  doc/src/sgml/ref/pg_dumpall.sgml
  doc/src/sgml/ref/pg_restore.sgml
  doc/src/sgml/ref/pgbench.sgml
  doc/src/sgml/ref/psql-ref.sgml
  doc/src/sgml/ref/update.sgml
  doc/src/sgml/runtime.sgml
  doc/src/sgml/sepgsql.sgml
  doc/src/sgml/spgist.sgml
  doc/src/sgml/syntax.sgml
  doc/src/sgml/user-manag.sgml
  doc/src/sgml/xaggr.sgml
Labels: doc_ja_master

#2976 match translation of 'boolean option' with one in protocol
  doc/src/sgml/file-fdw.sgml
Labels: マージ待ち（レビュー済み）

#2998 長音を省く方に統一（２）
  .ng.list
  doc/src/sgml/amcheck.sgml
  doc/src/sgml/bgworker.sgml
  doc/src/sgml/bki.sgml
  doc/src/sgml/bloom.sgml
  doc/src/sgml/brin.sgml
  doc/src/sgml/catalogs.sgml
  doc/src/sgml/catalogs0.sgml
  doc/src/sgml/config.sgml
  doc/src/sgml/config0.sgml
  doc/src/sgml/config3.sgml
  doc/src/sgml/fdwhandler.sgml
  doc/src/sgml/func.sgml
  doc/src/sgml/func2.sgml
  doc/src/sgml/glossary.sgml
  doc/src/sgml/libpq.sgml
  doc/src/sgml/libpq0.sgml
  doc/src/sgml/libpq2.sgml
  doc/src/sgml/logicaldecoding.sgml
  doc/src/sgml/monitoring.sgml
  doc/src/sgml/pgsurgery.sgml
  doc/src/sgml/ref/create_index.sgml
  doc/src/sgml/ref/psql-ref.sgml
  doc/src/sgml/release-16.sgml
  doc/src/sgml/sepgsql.sgml
  doc/src/sgml/textsearch.sgml
  doc/src/sgml/wal.sgml
  doc/src/sgml/xindex.sgml
Labels: 他にも誰か見て（レビュー済み）

#3002 remove 'nakaten' around 'archive'
  doc/src/sgml/archive-modules.sgml
  doc/src/sgml/backup.sgml
Labels: 他にも誰か見て（レビュー済み）

#3004 optimizerの訳語をオプティマイザにする
  doc/src/sgml/geqo.sgml
  doc/src/sgml/rules.sgml
Labels: 他にも誰か見て（レビュー済み）

#3006 response for 2989
  doc/src/sgml/ref/merge.sgml
Labels: 他にも誰か見て（レビュー済み）

#3001 fix translation of 'streaming replication'
  doc/src/sgml/logicaldecoding.sgml
Labels: レビュー待ち

#3011 fix typo-20240808
  doc/src/sgml/charset.sgml
  doc/src/sgml/config.sgml
  doc/src/sgml/config2.sgml
  doc/src/sgml/fdwhandler.sgml
  doc/src/sgml/libpq.sgml
  doc/src/sgml/libpq0.sgml
Labels: レビュー待ち

#3012 typo修正-20240809
  doc/src/sgml/high-availability.sgml
Labels: レビュー待ち

#3003 Issue #2973 対応です。
  doc/src/sgml/config.sgml
  doc/src/sgml/config0.sgml
  doc/src/sgml/config2.sgml
Labels: 指摘事項あり

#3014 config.sgmlの不要な空白を削除
  doc/src/sgml/config.sgml
  doc/src/sgml/config0.sgml
Labels: レビュー待ち

#3015 fix typo of 'option'
  doc/src/sgml/ref/alter_table.sgml
  doc/src/sgml/ref/select.sgml
Labels: レビュー待ち

#3016 typo修正、訳語違い修正
  doc/src/sgml/glossary.sgml
Labels: レビュー待ち

#3018 fix translation of 'tablespace'
  doc/src/sgml/config.sgml
  doc/src/sgml/config0.sgml
  doc/src/sgml/event-trigger.sgml
  doc/src/sgml/glossary.sgml
  doc/src/sgml/monitoring.sgml
  doc/src/sgml/protocol.sgml
Labels: レビュー待ち

#3020 fix typo
  doc/src/sgml/runtime.sgml
  doc/src/sgml/xaggr.sgml
Labels: レビュー待ち

#3021 fix typo - 2
  doc/src/sgml/btree.sgml
  doc/src/sgml/catalogs.sgml
  doc/src/sgml/catalogs2.sgml
Labels: レビュー待ち

#3007 deleteとupdateの翻訳を原文に沿うように修正
  doc/src/sgml/ref/delete.sgml
  doc/src/sgml/ref/update.sgml
Labels: 再レビュー待ち

#3013 ISSUES2992の対応（release-16.sgmlの斉藤さんからの指摘を反映）
  doc/src/sgml/release-16.sgml
Labels: 再レビュー待ち

#3022 greater thanの訳を修正
  doc/src/sgml/backup.sgml
Labels: レビュー待ち

#3025 remove extra ws from config
  doc/src/sgml/config.sgml
  doc/src/sgml/config0.sgml
Labels: レビュー待ち

#3027 update for 16.4 - part 1
  doc/src/sgml/ref/alter_materialized_view.sgml
  doc/src/sgml/ref/create_role.sgml
Labels: レビュー待ち

#3031 glossary.sgmlの16.4対応です
  doc/src/sgml/glossary.sgml
Labels: レビュー待ち

#3028 update for 16.4 - part 2
  doc/src/sgml/information_schema.sgml
  doc/src/sgml/monitoring.sgml
  doc/src/sgml/parallel.sgml
Labels: 他にも誰か見て（レビュー済み）

#3030 ddl.sgmlの16.4対応です
  doc/src/sgml/ddl.sgml
Labels: レビュー待ち

#3035 update drop_database for 16.4
  doc/src/sgml/ref/drop_database.sgml
Labels: マージ待ち（レビュー済み）

#3036 update client-auth for 16.4
  doc/src/sgml/client-auth.sgml
Labels: レビュー待ち

#3037 update runtime for 16.4
  doc/src/sgml/runtime.sgml
Labels: レビュー待ち

#3029 update logical-replication for 16.4
  doc/src/sgml/logical-replication.sgml
Labels: 再レビュー待ち

#3044 Update release-16.sgml for 16.4
  doc/src/sgml/release-16.sgml
Labels: マージ待ち（レビュー済み）

#3032 system-views.sgmlの16.4対応です
  doc/src/sgml/system-views.sgml
Labels: 再レビュー待ち

#3039 plpgsql.sgmlの16.4対応です
  doc/src/sgml/plpgsql.sgml
Labels: マージ待ち（レビュー済み）

#3041 interfaceの訳語修正
  .ng.list
  doc/src/sgml/logicaldecoding.sgml
Labels: レビュー待ち

#3045 typo修正
  doc/src/sgml/glossary.sgml
Labels: レビュー待ち

#3046 runtime.sgmlで訳抜けがありました
  doc/src/sgml/runtime.sgml
Labels: レビュー待ち

#3043 config.sgmlのPostgreSQL 16.4対応です。
  doc/src/sgml/config.sgml
  doc/src/sgml/config0.sgml
  doc/src/sgml/config1.sgml
  doc/src/sgml/config2.sgml
  doc/src/sgml/config3.sgml
Labels: 再レビュー待ち

#3048 fix translation of 'exclamation mark'
  doc/src/sgml/isn.sgml
Labels: レビュー待ち

#3033 update pg_dump for 16.4
  doc/src/sgml/ref/pg_dump.sgml
Labels: 再レビュー待ち

#3049 訳抜けとlocaleはロケールに修正
  doc/src/sgml/charset.sgml
Labels: レビュー待ち
