Repository pgsql-jp/jpug-doc, pull requests merged in 2024-06, with the labels that each got.

#2925 update create_subscription for 16.3
  doc/src/sgml/ref/create_subscription.sgml
Labels: レビュー待ち

#2926 update for 16.3 - part 6
  doc/src/sgml/install-windows.sgml
  doc/src/sgml/json.sgml
Labels: レビュー待ち

#2928 update create_table for 16.3
  doc/src/sgml/ref/create_table.sgml
Labels: レビュー待ち

#2929 fix traslation of 'commutator'
  doc/src/sgml/xoper.sgml
Labels: レビュー待ち

#2930 update grant for 16.3
  doc/src/sgml/ref/grant.sgml
Labels: レビュー待ち

#2931 update client-auth for 16.3
  doc/src/sgml/client-auth.sgml
Labels: レビュー待ち

#2932 glossary.sgmlの16.3対応です
  doc/src/sgml/glossary.sgml
Labels: レビュー待ち

#2933 ユリウス日のタイトル翻訳
  doc/src/sgml/datetime.sgml
Labels: 他にも誰か見て（レビュー済み）

#2934 update libpq for 16.3
  doc/src/sgml/libpq.sgml
  doc/src/sgml/libpq0.sgml
  doc/src/sgml/libpq1.sgml
  doc/src/sgml/libpq3.sgml
Labels: レビュー待ち

#2935 update pgcrypto for 16.3
  doc/src/sgml/pgcrypto.sgml
Labels: レビュー待ち

#2937 update storage for 16.3
  doc/src/sgml/storage.sgml
Labels: レビュー待ち

#2936 update indices for 16.3
  doc/src/sgml/indices.sgml
Labels: 再レビュー待ち

#2927 update pgstatstatements for 16.3
  doc/src/sgml/pgstatstatements.sgml
Labels: 再レビュー待ち

#2945 Doc ja master
  doc/src/sgml/catalogs0.sgml
  doc/src/sgml/catalogs1.sgml
  doc/src/sgml/indices.sgml
  doc/src/sgml/pgstatstatements.sgml
  doc/src/sgml/release-17.sgml
Labels: レビュー待ち, doc_ja_master

#2951 charset.sgmlの16.3対応です
  doc/src/sgml/charset.sgml
Labels: レビュー待ち

#2940 datatype.sgmlの16.3対応
  doc/src/sgml/datatype.sgml
Labels: 再レビュー待ち

#2942 func.sgmlのPostgreSQL 16.3対応です。
  doc/src/sgml/func.sgml
  doc/src/sgml/func1.sgml
  doc/src/sgml/func2.sgml
  doc/src/sgml/func3.sgml
  doc/src/sgml/func4.sgml
Labels: 再レビュー待ち

#2943 update create_role for 16.3
  doc/src/sgml/ref/create_role.sgml
Labels: マージ待ち（レビュー済み）

#2946 update for 16.3 - part 7
  doc/src/sgml/ref/create_foreign_table.sgml
  doc/src/sgml/ref/create_operator.sgml
  doc/src/sgml/ref/create_server.sgml
Labels: レビュー待ち

#2957 機械翻訳の追加、更新
  doc/src/sgml/config.sgml
  doc/src/sgml/config1.sgml
  doc/src/sgml/ddl.sgml
  doc/src/sgml/release-17.sgml
Labels: doc_ja_master
