Repository pgsql-jp/jpug-doc, pull requests merged in 2025-02, with the labels that each got.

#3217 update create_index for 17.0
  doc/src/sgml/ref/create_index.sgml
Labels: レビュー待ち

#3215 演算子クラスの必要性についての記述に対する訳を改善
  doc/src/sgml/xindex.sgml
Labels: レビュー待ち

#3170 update limits for 17.0
  doc/src/sgml/limits.sgml
Labels: 再レビュー待ち

#3213 文の数を合わせるように分割と移動
  doc/src/sgml/datetime.sgml
  doc/src/sgml/dml.sgml
  doc/src/sgml/ecpg.sgml
  doc/src/sgml/func.sgml
  doc/src/sgml/installation.sgml
  doc/src/sgml/intro.sgml
  doc/src/sgml/libpq.sgml
  doc/src/sgml/manage-ag.sgml
  doc/src/sgml/mvcc.sgml
  doc/src/sgml/perform.sgml
  doc/src/sgml/postgres-fdw.sgml
  doc/src/sgml/postgres.sgml
  doc/src/sgml/protocol.sgml
  doc/src/sgml/ref/copy.sgml
  doc/src/sgml/ref/create_view.sgml
  doc/src/sgml/ref/select.sgml
  doc/src/sgml/regress.sgml
  doc/src/sgml/rules.sgml
  doc/src/sgml/spgist.sgml
  doc/src/sgml/start.sgml
  doc/src/sgml/user-manag.sgml
  doc/src/sgml/xml2.sgml
Labels: 指摘事項あり, version 16

#3216 suffix prefixを接頭辞と接尾辞にする
  doc/src/sgml/func.sgml
  doc/src/sgml/func2.sgml
Labels: レビュー待ち, version 16

#3218 tupleがタプルになるように見直しました
  doc/src/sgml/brin.sgml
  doc/src/sgml/config.sgml
  doc/src/sgml/config1.sgml
  doc/src/sgml/dblink.sgml
Labels: 指摘事項あり, version 16

#3220 syntax.sgmlのPostgreSQL 17.0対応です。
  doc/src/sgml/syntax.sgml
Labels: マージ待ち（レビュー済み）

#3223 訳語の統一のため中点の削除
  .ng.list
  doc/src/sgml/backup.sgml
  doc/src/sgml/basebackup-to-shell.sgml
  doc/src/sgml/basic-archive.sgml
  doc/src/sgml/charset.sgml
  doc/src/sgml/config.sgml
  doc/src/sgml/config3.sgml
  doc/src/sgml/json.sgml
  doc/src/sgml/logical-replication.sgml
  doc/src/sgml/mvcc.sgml
  doc/src/sgml/protocol.sgml
Labels: レビュー待ち, version 16

#3224 Again,の訳修正
  doc/src/sgml/ddl.sgml
  doc/src/sgml/high-availability.sgml
  doc/src/sgml/libpq.sgml
  doc/src/sgml/libpq3.sgml
  doc/src/sgml/perform.sgml
  doc/src/sgml/ref/select.sgml
  doc/src/sgml/textsearch.sgml
  doc/src/sgml/xtypes.sgml
Labels: レビュー待ち, version 16

#3174 Update for release-17
  doc/src/sgml/release-17.sgml
Labels: 再レビュー待ち

#3199 ref/pg_dump.sgmlの翻訳改善（PR3185で改善し損ねたコメントの反映）
  doc/src/sgml/ref/pg_dump.sgml
Labels: レビュー待ち

#3214 ハッシュインデックスについての記述を改善
  doc/src/sgml/hash.sgml
Labels: 他にも誰か見て（レビュー済み）

#3219 update unaccent for 17.0
  doc/src/sgml/unaccent.sgml
Labels: 再レビュー待ち

#3227 段落の文の共通化（５）
  doc/src/sgml/ref/begin.sgml
  doc/src/sgml/ref/create_sequence.sgml
  doc/src/sgml/ref/end.sgml
  doc/src/sgml/ref/pg_amcheck.sgml
  doc/src/sgml/ref/pg_dumpall.sgml
  doc/src/sgml/ref/pg_isready.sgml
  doc/src/sgml/ref/pg_receivewal.sgml
  doc/src/sgml/ref/pg_recvlogical.sgml
  doc/src/sgml/ref/psql-ref.sgml
  doc/src/sgml/ref/rollback.sgml
Labels: レビュー待ち, version 16

#3228 #3215バックポートと #3170での問題修正
  doc/src/sgml/storage.sgml
  doc/src/sgml/xindex.sgml
Labels: レビュー待ち, version 16

#3229 pg_resetwal.sgmlのPostgreSQL17.0対応
  doc/src/sgml/ref/pg_resetwal.sgml
Labels: 他にも誰か見て（レビュー済み）

#3231 update user-manag for 17.0
  doc/src/sgml/user-manag.sgml
Labels: マージ待ち（レビュー済み）

#3235 全部がtypoとは言えないかもしれなけれど冗長なので修正
  doc/src/sgml/catalogs.sgml
  doc/src/sgml/catalogs0.sgml
  doc/src/sgml/datetime.sgml
  doc/src/sgml/json.sgml
Labels: レビュー待ち, version 16

#3236 dblink.sgmlの最修正とrefpurposeの見直し
  doc/src/sgml/dblink.sgml
  doc/src/sgml/ecpg.sgml
  doc/src/sgml/ref/do.sgml
  doc/src/sgml/ref/drop_owned.sgml
  doc/src/sgml/ref/drop_user_mapping.sgml
  doc/src/sgml/ref/pg_checksums.sgml
  doc/src/sgml/ref/pg_verifybackup.sgml
  doc/src/sgml/spi.sgml
Labels: レビュー待ち, version 16

#3232 update for 17.0 - part 13
  doc/src/sgml/ref/create_database.sgml
  doc/src/sgml/ref/createdb.sgml
Labels: マージ待ち（レビュー済み）

#3233 update cluster for 17.0
  doc/src/sgml/ref/cluster.sgml
Labels: 再レビュー待ち

#3240 IDENTITY列を識別列に統一
  doc/src/sgml/catalogs.sgml
  doc/src/sgml/catalogs0.sgml
  doc/src/sgml/func.sgml
  doc/src/sgml/func4.sgml
  doc/src/sgml/ref/alter_table.sgml
  doc/src/sgml/ref/copy.sgml
  doc/src/sgml/ref/create_table.sgml
  doc/src/sgml/ref/insert.sgml
  doc/src/sgml/ref/update.sgml
Labels: レビュー待ち

#3246 デカルト積に統一
  doc/src/sgml/perform.sgml
  doc/src/sgml/ref/select.sgml
Labels: レビュー待ち, version 16

#3247 see noteの訳抜けを修正
  doc/src/sgml/func.sgml
  doc/src/sgml/func3.sgml
  doc/src/sgml/func4.sgml
Labels: レビュー待ち, version 16

#3248 update dml for 17.0
  doc/src/sgml/dml.sgml
Labels: マージ待ち（レビュー済み）

#3249 update create_function for 17.0
  doc/src/sgml/ref/create_function.sgml
Labels: マージ待ち（レビュー済み）

#3250 update fdwhandler for 17.0
  doc/src/sgml/fdwhandler.sgml
Labels: レビュー待ち
