Repository pgsql-jp/jpug-doc, pull requests merged in 2025-03, with the labels that each got.

#3260 <entry>の分割（1）
  doc/src/sgml/brin.sgml
  doc/src/sgml/catalogs.sgml
  doc/src/sgml/catalogs0.sgml
  doc/src/sgml/catalogs3.sgml
  doc/src/sgml/ecpg.sgml
  doc/src/sgml/errcodes.sgml
  doc/src/sgml/extend.sgml
  doc/src/sgml/features.sgml
  doc/src/sgml/gin.sgml
  doc/src/sgml/gist.sgml
  doc/src/sgml/isn.sgml
  doc/src/sgml/json.sgml
  doc/src/sgml/limits.sgml
  doc/src/sgml/monitoring.sgml
  doc/src/sgml/pgcrypto.sgml
  doc/src/sgml/pgrowlocks.sgml
  doc/src/sgml/pgstattuple.sgml
  doc/src/sgml/plpgsql.sgml
  doc/src/sgml/ref/copy.sgml
  doc/src/sgml/ref/create_policy.sgml
  doc/src/sgml/ref/create_trigger.sgml
  doc/src/sgml/ref/pg_waldump.sgml
  doc/src/sgml/ref/pgbench.sgml
  doc/src/sgml/runtime.sgml
  doc/src/sgml/spgist.sgml
  doc/src/sgml/system-views.sgml
  doc/src/sgml/tablefunc.sgml
  doc/src/sgml/user-manag.sgml
  doc/src/sgml/xindex.sgml
  doc/src/sgml/xml2.sgml
Labels: レビュー待ち, version 16

#3261 <entry>の分割（2）
  doc/src/sgml/charset.sgml
  doc/src/sgml/config.sgml
  doc/src/sgml/config1.sgml
  doc/src/sgml/config2.sgml
  doc/src/sgml/func.sgml
  doc/src/sgml/func1.sgml
  doc/src/sgml/func2.sgml
  doc/src/sgml/func4.sgml
  doc/src/sgml/storage.sgml
  doc/src/sgml/syntax.sgml
  doc/src/sgml/textsearch.sgml
Labels: レビュー待ち, version 16

#3252 update ltree for 17.0
  doc/src/sgml/ltree.sgml
Labels: 再レビュー待ち

#3234 ddl.sgml の PG17 むけ日本語訳を記載。identity column を 識別列 とした。
  doc/src/sgml/ddl.sgml
Labels: 再レビュー待ち

#3245 wal-for-extensions.sgmlの17.0対応です。
  doc/src/sgml/wal-for-extensions.sgml
Labels: 再レビュー待ち

#3258 pgbuffercache.sgmlの17.0で発見した問題のバックポートです
  doc/src/sgml/pgbuffercache.sgml
Labels: レビュー待ち, version 16

#3251 update features for 17.0
  doc/src/sgml/features.sgml
Labels: 他にも誰か見て（レビュー済み）

#3253 update pg_receivewal for 17.0
  doc/src/sgml/ref/pg_receivewal.sgml
Labels: マージ待ち（レビュー済み）

#3254 update file-fdw for 17.0
  doc/src/sgml/file-fdw.sgml
Labels: マージ待ち（レビュー済み）

#3255 update 'update' for 17.0
  doc/src/sgml/ref/update.sgml
Labels: レビュー待ち

#3256 update create_view for 17.0
  doc/src/sgml/ref/create_view.sgml
Labels: 再レビュー待ち

#3259 update rule for 17.0
  doc/src/sgml/rules.sgml
Labels: 他にも誰か見て（レビュー済み）

#3257 pgbuffercache.sgmlの17.0対応です
  doc/src/sgml/pgbuffercache.sgml
Labels: 再レビュー待ち

#3274 doc_ja_17に入った既存訳のバックポート
  doc/src/sgml/catalogs.sgml
  doc/src/sgml/catalogs0.sgml
  doc/src/sgml/func.sgml
  doc/src/sgml/func4.sgml
  doc/src/sgml/hash.sgml
  doc/src/sgml/ref/alter_table.sgml
  doc/src/sgml/ref/copy.sgml
  doc/src/sgml/ref/create_table.sgml
  doc/src/sgml/ref/insert.sgml
  doc/src/sgml/ref/update.sgml
  doc/src/sgml/release-16.sgml
Labels: レビュー待ち, version 16

#3263 update explain for 17.0
  doc/src/sgml/ref/explain.sgml
Labels: 他にも誰か見て（レビュー済み）

#3264 regress.sgmlの17.0対応です
  doc/src/sgml/regress.sgml
Labels: レビュー待ち

#3281 deal with missing parts in ref/pg_amcheck.sgml
  doc/src/sgml/ref/pg_amcheck.sgml
Labels: レビュー待ち

#3266 update copy for 17.0
  doc/src/sgml/ref/copy.sgml
Labels: 他にも誰か見て（レビュー済み）

#3268 indexam.sgmlのPostgreSQL17.0対応
  doc/src/sgml/indexam.sgml
Labels: 他にも誰か見て（レビュー済み）

#3269 update trigger for 17.0
  doc/src/sgml/trigger.sgml
Labels: 他にも誰か見て（レビュー済み）

#3267 wal.sgmlの17.0対応です
  doc/src/sgml/wal.sgml
Labels: 再レビュー待ち

#3285 process the rest of protocol
  doc/src/sgml/protocol.sgml
Labels: マージ待ち（レビュー済み）
