Repository pgsql-jp/jpug-doc, pull requests merged in 2025-04, with the labels that each got.

#3277 17の修正のバックポートです
  doc/src/sgml/charset.sgml
  doc/src/sgml/planstats.sgml
  doc/src/sgml/ref/vacuumdb.sgml
  doc/src/sgml/unaccent.sgml
Labels: レビュー待ち, version 16

#3278 doc_ja_16の修正をフォワードポート （3-2）
  doc/src/sgml/gist.sgml
  doc/src/sgml/glossary.sgml
  doc/src/sgml/information_schema.sgml
  doc/src/sgml/installation.sgml
  doc/src/sgml/intro.sgml
  doc/src/sgml/json.sgml
  doc/src/sgml/logical-replication.sgml
  doc/src/sgml/logicaldecoding.sgml
  doc/src/sgml/maintenance.sgml
  doc/src/sgml/manage-ag.sgml
  doc/src/sgml/monitoring.sgml
  doc/src/sgml/mvcc.sgml
  doc/src/sgml/nls.sgml
  doc/src/sgml/pgcrypto.sgml
  doc/src/sgml/pgwalinspect.sgml
  doc/src/sgml/pltcl.sgml
  doc/src/sgml/postgres-fdw.sgml
  doc/src/sgml/queries.sgml
  doc/src/sgml/regress.sgml
  doc/src/sgml/rules.sgml
  doc/src/sgml/runtime.sgml
  doc/src/sgml/sources.sgml
  doc/src/sgml/spgist.sgml
  doc/src/sgml/start.sgml
  doc/src/sgml/storage.sgml
  doc/src/sgml/syntax.sgml
  doc/src/sgml/textsearch.sgml
  doc/src/sgml/user-manag.sgml
  doc/src/sgml/xml2.sgml
  doc/src/sgml/xoper.sgml
  doc/src/sgml/xtypes.sgml
Labels: レビュー待ち

#3279 doc_ja_16の修正をフォワードポート （3-3）
  doc/src/sgml/charset.sgml
  doc/src/sgml/datatype.sgml
  doc/src/sgml/datetime.sgml
  doc/src/sgml/dblink.sgml
  doc/src/sgml/ddl.sgml
  doc/src/sgml/ecpg.sgml
  doc/src/sgml/ltree.sgml
  doc/src/sgml/planstats.sgml
  doc/src/sgml/ref/alter_function.sgml
  doc/src/sgml/ref/alter_role.sgml
  doc/src/sgml/ref/alter_table.sgml
  doc/src/sgml/ref/alter_type.sgml
  doc/src/sgml/ref/alter_user.sgml
  doc/src/sgml/ref/analyze.sgml
  doc/src/sgml/ref/begin.sgml
  doc/src/sgml/ref/checkpoint.sgml
  doc/src/sgml/ref/cluster.sgml
  doc/src/sgml/ref/create_database.sgml
  doc/src/sgml/ref/create_group.sgml
  doc/src/sgml/ref/create_publication.sgml
  doc/src/sgml/ref/create_rule.sgml
  doc/src/sgml/ref/create_sequence.sgml
  doc/src/sgml/ref/create_table.sgml
  doc/src/sgml/ref/create_tablespace.sgml
  doc/src/sgml/ref/create_trigger.sgml
  doc/src/sgml/ref/create_view.sgml
  doc/src/sgml/ref/createdb.sgml
  doc/src/sgml/ref/do.sgml
  doc/src/sgml/ref/drop_owned.sgml
  doc/src/sgml/ref/drop_user_mapping.sgml
  doc/src/sgml/ref/ecpg-ref.sgml
  doc/src/sgml/ref/end.sgml
  doc/src/sgml/ref/explain.sgml
  doc/src/sgml/ref/fetch.sgml
  doc/src/sgml/ref/insert.sgml
  doc/src/sgml/ref/lock.sgml
  doc/src/sgml/ref/move.sgml
  doc/src/sgml/ref/pg_checksums.sgml
  doc/src/sgml/ref/pg_controldata.sgml
  doc/src/sgml/ref/pg_isready.sgml
  doc/src/sgml/ref/pg_receivewal.sgml
  doc/src/sgml/ref/pg_recvlogical.sgml
  doc/src/sgml/ref/pg_resetwal.sgml
  doc/src/sgml/ref/pg_verifybackup.sgml
  doc/src/sgml/ref/pg_waldump.sgml
  doc/src/sgml/ref/pgtestfsync.sgml
  doc/src/sgml/ref/pgtesttiming.sgml
  doc/src/sgml/ref/postgres-ref.sgml
  doc/src/sgml/ref/psql-ref.sgml
  doc/src/sgml/ref/reset.sgml
  doc/src/sgml/ref/rollback.sgml
  doc/src/sgml/ref/select.sgml
  doc/src/sgml/ref/show.sgml
  doc/src/sgml/ref/start_transaction.sgml
  doc/src/sgml/ref/vacuum.sgml
  doc/src/sgml/ref/vacuumdb.sgml
  doc/src/sgml/spi.sgml
Labels: レビュー待ち

#3270 event-trigger.sgml の PG17 むけ翻訳です。
  doc/src/sgml/event-trigger.sgml
Labels: 再レビュー待ち

#3283 update initdb for 17.0
  doc/src/sgml/ref/initdb.sgml
Labels: 他にも誰か見て（レビュー済み）

#3282 deal with missing parts in ref/create_function.sgml
  doc/src/sgml/ref/create_function.sgml
Labels: 他にも誰か見て（レビュー済み）

#3284 update plpgsql for 17.0
  doc/src/sgml/plpgsql.sgml
Labels: 他にも誰か見て（レビュー済み）

#3290 reindex v17の対応
  doc/src/sgml/ref/reindex.sgml
Labels: 他にも誰か見て（レビュー済み）

#3293 xindex.sgmlのv17対応
  doc/src/sgml/xindex.sgml
Labels: 他にも誰か見て（レビュー済み）

#3295 <entry>の分離のフォワードポート
  doc/src/sgml/brin.sgml
  doc/src/sgml/catalogs.sgml
  doc/src/sgml/catalogs0.sgml
  doc/src/sgml/catalogs3.sgml
  doc/src/sgml/ecpg.sgml
  doc/src/sgml/errcodes.sgml
  doc/src/sgml/extend.sgml
  doc/src/sgml/features.sgml
  doc/src/sgml/gin.sgml
  doc/src/sgml/gist.sgml
  doc/src/sgml/isn.sgml
  doc/src/sgml/json.sgml
  doc/src/sgml/limits.sgml
  doc/src/sgml/monitoring.sgml
  doc/src/sgml/pgcrypto.sgml
  doc/src/sgml/pgrowlocks.sgml
  doc/src/sgml/pgstattuple.sgml
  doc/src/sgml/ref/create_policy.sgml
  doc/src/sgml/ref/create_trigger.sgml
  doc/src/sgml/ref/pg_waldump.sgml
  doc/src/sgml/runtime.sgml
  doc/src/sgml/spgist.sgml
  doc/src/sgml/tablefunc.sgml
  doc/src/sgml/user-manag.sgml
  doc/src/sgml/xml2.sgml
Labels: レビュー待ち

#3272 release.sgmlのV17対応
  doc/src/sgml/release.sgml
Labels: 他にも誰か見て（レビュー済み）

#3298 reindexdb17の翻訳
  doc/src/sgml/ref/reindexdb.sgml
Labels: 他にも誰か見て（レビュー済み）

#3292 plpgsqlの翻訳改善
  doc/src/sgml/plpgsql.sgml
Labels: 他にも誰か見て（レビュー済み）

#3300 <entry>の分割（４）
  doc/src/sgml/charset.sgml
  doc/src/sgml/config.sgml
  doc/src/sgml/config1.sgml
  doc/src/sgml/config2.sgml
  doc/src/sgml/datatype.sgml
Labels: レビュー待ち

#3299 インデントや改行の修正
  doc/src/sgml/installation.sgml
  doc/src/sgml/ref/alter_extension.sgml
  doc/src/sgml/ref/commit.sgml
Labels: レビュー待ち

#3301 <entry>の分割（５）
  doc/src/sgml/datetime.sgml
  doc/src/sgml/ddl.sgml
  doc/src/sgml/func.sgml
  doc/src/sgml/func1.sgml
  doc/src/sgml/func2.sgml
  doc/src/sgml/func4.sgml
  doc/src/sgml/high-availability.sgml
  doc/src/sgml/ref/create_trigger.sgml
  doc/src/sgml/ref/pgbench.sgml
  doc/src/sgml/storage.sgml
  doc/src/sgml/syntax.sgml
  doc/src/sgml/textsearch.sgml
  doc/src/sgml/xindex.sgml
Labels: レビュー待ち

#3303 pg_dumpall.sgmlのPostgreSQL 17.0対応です。
  doc/src/sgml/ref/pg_dumpall.sgml
Labels: レビュー待ち

#3304 カタカナ語の再統一
  .ng.list
  doc/src/sgml/extend.sgml
  doc/src/sgml/plpgsql.sgml
  doc/src/sgml/protocol.sgml
Labels: レビュー待ち

#3294 system-views.sgmlの17.0対応です
  doc/src/sgml/system-views.sgml
Labels: 再レビュー待ち

#3307 #3305 の途中で見つかったtypoの修正
  doc/src/sgml/protocol.sgml
Labels: レビュー待ち

#3306 fix sql_features.txt
  src/backend/catalog/sql_features.txt.ja
Labels: レビュー待ち

#3265 update pgbench for 17.0
  doc/src/sgml/ref/pgbench.sgml
Labels: 指摘事項あり, 再レビュー待ち, 他にも誰か見て（レビュー済み）

#3271 perform.sgml を PG17 向けに翻訳
  doc/src/sgml/perform.sgml
Labels: 指摘事項あり

#3275 libpq.sgmlのPostgreSQL 17.0対応です。
  doc/src/sgml/libpq.sgml
  doc/src/sgml/libpq0.sgml
  doc/src/sgml/libpq1.sgml
  doc/src/sgml/libpq2.sgml
  doc/src/sgml/libpq3.sgml
Labels: 他にも誰か見て（レビュー済み）

#3286 pg_combinebackup.sgml と pg_basebackup.sgml を PG17 むけに翻訳
  doc/src/sgml/ref/pg_basebackup.sgml
  doc/src/sgml/ref/pg_combinebackup.sgml
Labels: 指摘事項あり

#3288 pg_restoreをPG17向けに翻訳
  doc/src/sgml/ref/pg_restore.sgml
Labels: 指摘事項あり

#3289 postgres.sgmlのファイルをPG17向けに翻訳
  doc/src/sgml/postgres.sgml
Labels: 指摘事項あり

#3291 update merge for 17.0
  doc/src/sgml/ref/merge.sgml
Labels: 他にも誰か見て（レビュー済み）

#3308 xfunc.sgmlの17.0対応です
  doc/src/sgml/xfunc.sgml
Labels: 再レビュー待ち
