Repository pgsql-jp/jpug-doc, pull requests merged in 2025-06, with the labels that each got.

#3367 update *_domain for 17.5
  doc/src/sgml/ref/alter_domain.sgml
  doc/src/sgml/ref/create_domain.sgml
Labels: マージ待ち（レビュー済み）

#3368 update *_index for 17.5
  doc/src/sgml/ref/alter_index.sgml
  doc/src/sgml/ref/create_index.sgml
Labels: マージ待ち（レビュー済み）

#3369 update *db for 17.5
  doc/src/sgml/ref/clusterdb.sgml
  doc/src/sgml/ref/reindexdb.sgml
  doc/src/sgml/ref/vacuumdb.sgml
Labels: マージ待ち（レビュー済み）

#3371 update history for 17.5
  doc/src/sgml/history.sgml
Labels: 他にも誰か見て（レビュー済み）

#3378 貢献者を追加
  doc/src/sgml/jpug-doc.sgml
Labels: レビュー待ち

#3373 update for 17.5 - part 5
  doc/src/sgml/json.sgml
  doc/src/sgml/maintenance.sgml
Labels: マージ待ち（レビュー済み）

#3375 update for 17.5 - part 6
  doc/src/sgml/ref/alter_table.sgml
  doc/src/sgml/ref/pg_receivewal.sgml
Labels: 他にも誰か見て（レビュー済み）

#3386 remove extra space in Japanese sentences
  doc/src/sgml/plpgsql.sgml
  doc/src/sgml/ref/alter_group.sgml
  doc/src/sgml/ref/pg_dump.sgml
  doc/src/sgml/runtime.sgml
Labels: レビュー待ち

#3357 queries.sgmlの17.5対応です
  doc/src/sgml/queries.sgml
Labels: 再レビュー待ち

#3381 installation.sgmlの17.5対応です
  doc/src/sgml/installation.sgml
Labels: 他にも誰か見て（レビュー済み）

#3383 update event-trigger for 17.5
  doc/src/sgml/event-trigger.sgml
Labels: 再レビュー待ち

#3390 untranslated title
  doc/src/sgml/func.sgml
  doc/src/sgml/func3.sgml
Labels: レビュー待ち

#3385 update pg_createsubscriber for 17.5
  doc/src/sgml/ref/pg_createsubscriber.sgml
Labels: 他にも誰か見て（レビュー済み）

#3392 。の抜けと不自然な日本語を修正
  doc/src/sgml/ref/pg_checksums.sgml
Labels: レビュー待ち
